load("//ts:defs.bzl", "ts_compile", "ts_test")

# keep
ts_compile(
    name = "self_reference",
    srcs = ["src/index.ts"],
    emit = True,  # keep
    package_scopes = ["package.json"],
)

# keep
ts_test(
    name = "self_reference_test",
    srcs = ["self_reference.test.ts"],
    emit = True,  # keep
    node_modules = "//tests/npm:node_modules",
    runner = "//ts/runners:node_test",
    deps = [
        ":self_reference",
        "@npm//:types_node",
    ],
)
