load("//npm:defs.bzl", "node_modules")

package(default_visibility = ["//tests/npm:__pkg__"])

# The importer app-a: ansi-regex@5 and ansi-styles resolved against it.
node_modules(
    name = "node_modules",
    parent = "//tests/npm/features:node_modules",
    deps = [
        "@npm_features//app-a:ansi-regex",
        "@npm_features//app-a:ansi-styles",
    ],
)
