// Package typescript implements a Gazelle language extension that generates
// Bazel BUILD files for TypeScript projects using rules_typescript.
//
// It supports ts_compile and ts_test rules from @rules_typescript//ts:defs.bzl,
// infers package boundaries from index.ts/tsx files, and resolves imports to
// Bazel labels via the rule index, npm mappings, and path alias configuration.
package typescript

import (
	"flag"

	"github.com/bazelbuild/bazel-gazelle/config"
	"github.com/bazelbuild/bazel-gazelle/label"
	"github.com/bazelbuild/bazel-gazelle/language"
	"github.com/bazelbuild/bazel-gazelle/repo"
	"github.com/bazelbuild/bazel-gazelle/resolve"
	"github.com/bazelbuild/bazel-gazelle/rule"
)

const languageName = "typescript"

// tsLang is the Gazelle language extension for TypeScript.
type tsLang struct{}

// NewLanguage returns a new instance of the TypeScript Gazelle language extension.
// Gazelle discovers extensions via this symbol.
func NewLanguage() language.Language {
	return &tsLang{}
}

// Name returns the canonical name of this language extension. It is used as a
// prefix when resolving import specs and when keying per-language config state.
func (l *tsLang) Name() string { return languageName }

// RegisterFlags registers command-line flags for the TypeScript extension.
// Currently no top-level flags are defined; configuration is driven by the
// gazelle_ts.json file and in-BUILD directives.
func (l *tsLang) RegisterFlags(_ *flag.FlagSet, _ string, _ *config.Config) {}

// CheckFlags validates flags after they have been parsed. No-op for now.
func (l *tsLang) CheckFlags(_ *flag.FlagSet, _ *config.Config) error { return nil }

// KnownDirectives lists the # gazelle: directives this extension understands.
// Gazelle emits a warning for unrecognised directives, so every directive
// that Configure interprets must be listed here.
func (l *tsLang) KnownDirectives() []string {
	return []string{
		// Control whether every dir or only index.ts dirs are package boundaries.
		directivePackageBoundary,
		// Suppress all TypeScript rule generation for this directory tree.
		directiveIgnore,
		// Override the target name for the primary ts_compile rule in this dir.
		directiveTargetName,
		// Emit a warning for imports that cannot be resolved to a Bazel label.
		directiveWarnUnresolved,
		// Control isolated_declarations on generated ts_compile rules.
		directiveIsolatedDeclarations,
		// Add a TypeScript path alias mapping (can appear multiple times).
		directivePathAlias,
		// Append a Bazel label to every ts_test deps list in this tree.
		directiveRuntimeDep,
		// Add a file glob pattern to exclude from source targets.
		directiveExclude,
		// Register a custom ts_codegen target via a directive.
		directiveCodegen,
	}
}

// Configure reads directives from the build file in directory rel and updates
// the per-directory tsConfig stored in c.Exts.
func (l *tsLang) Configure(c *config.Config, rel string, f *rule.File) {
	configureTsConfig(c, rel, f)
}

// Loads returns the load info for the rules generated by this extension.
// Deprecated in favour of ModuleAwareLanguage.ApparentLoads, but still
// required by Gazelle for compatibility.
func (l *tsLang) Loads() []rule.LoadInfo {
	return []rule.LoadInfo{
		{
			Name:    "@rules_typescript//ts:defs.bzl",
			Symbols: []string{"asset_library", "css_library", "css_module", "json_library", "ts_bundle", "ts_codegen", "ts_compile", "ts_dev_server", "ts_lint", "ts_test"},
		},
		{
			Name:    "@rules_typescript//npm:defs.bzl",
			Symbols: []string{"node_modules"},
		},
		{
			Name:    "@rules_typescript//vite:bundler.bzl",
			Symbols: []string{"vite_bundler"},
		},
	}
}

// ApparentLoads returns load info aware of the Bzlmod apparent repository name.
// This satisfies the ModuleAwareLanguage optional interface.
func (l *tsLang) ApparentLoads(moduleToApparentName func(string) string) []rule.LoadInfo {
	rulesTs := moduleToApparentName("rules_typescript")
	if rulesTs == "" {
		rulesTs = "rules_typescript"
	}
	return []rule.LoadInfo{
		{
			Name:    "@" + rulesTs + "//ts:defs.bzl",
			Symbols: []string{"asset_library", "css_library", "css_module", "json_library", "ts_bundle", "ts_codegen", "ts_compile", "ts_dev_server", "ts_lint", "ts_test"},
		},
		{
			Name:    "@" + rulesTs + "//npm:defs.bzl",
			Symbols: []string{"node_modules"},
		},
		{
			Name:    "@" + rulesTs + "//vite:bundler.bzl",
			Symbols: []string{"vite_bundler"},
		},
	}
}

// Kinds returns metadata about each rule kind this extension generates. Gazelle
// uses this metadata to match generated rules against existing rules and to
// determine which attributes are mergeable.
func (l *tsLang) Kinds() map[string]rule.KindInfo {
	return map[string]rule.KindInfo{
		"asset_library": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"srcs": true,
			},
			MergeableAttrs: map[string]bool{
				"srcs":       true,
				"deps":       true,
				"visibility": true,
			},
		},
		"css_library": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"srcs": true,
			},
			MergeableAttrs: map[string]bool{
				"srcs":       true,
				"deps":       true,
				"visibility": true,
			},
		},
		"css_module": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"srcs": true,
			},
			MergeableAttrs: map[string]bool{
				"srcs":       true,
				"deps":       true,
				"visibility": true,
			},
		},
		"json_library": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"srcs": true,
			},
			MergeableAttrs: map[string]bool{
				"srcs":       true,
				"deps":       true,
				"visibility": true,
			},
		},
		"ts_compile": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"srcs": true,
			},
			MergeableAttrs: map[string]bool{
				"srcs":                  true,
				"deps":                  true,
				"visibility":            true,
				"path_aliases":          true,
				"isolated_declarations": true,
			},
			ResolveAttrs: map[string]bool{
				"deps": true,
			},
		},
		"ts_test": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"srcs": true,
			},
			MergeableAttrs: map[string]bool{
				"srcs": true,
				"deps": true,
			},
			ResolveAttrs: map[string]bool{
				"deps": true,
			},
		},
		"ts_lint": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"srcs": true,
			},
			MergeableAttrs: map[string]bool{
				"srcs":           true,
				"linter":         true,
				"linter_binary":  true,
				"config":         true,
				"fail_on_warnings": true,
			},
		},
		// node_modules is no longer generated by Gazelle (ts_test auto-generates it
		// internally), but we keep it in Kinds so that Gazelle can still recognise
		// and delete stale node_modules rules from existing BUILD files during
		// migration.
		"node_modules": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"deps": true,
			},
			MergeableAttrs: map[string]bool{
				"deps": true,
			},
		},
		"ts_dev_server": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"entry_point": true,
			},
			MergeableAttrs: map[string]bool{
				"entry_point":  true,
				"port":         true,
				"host":         true,
				"open":         true,
				"node_modules": true,
				"plugin":       true,
				"bundler":      true,
				"visibility":   true,
			},
		},
		// ts_codegen is generated by auto-detection and # gazelle:ts_codegen directives.
		// srcs and node_modules are intentionally excluded from MergeableAttrs:
		//   - srcs: initial generation sets the correct value (files or a glob
		//     expression). Merging srcs would corrupt glob expressions that must
		//     remain as Starlark expressions in the BUILD file.
		//   - node_modules: the user may point to a specific node_modules target
		//     (e.g. //:router_generator_node_modules). Subsequent Gazelle runs
		//     should not override that with the generic ":node_modules" default.
		// outs and out_dir remain mergeable so Gazelle can update declared outputs
		// when the generator configuration changes.
		"ts_codegen": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"generator": true,
			},
			MergeableAttrs: map[string]bool{
				"outs":       true,
				"out_dir":    true,
				"visibility": true,
			},
		},
		// vite_bundler is generated at the workspace root when a Vite-based
		// framework is detected. node_modules and vite attrs are mergeable so
		// Gazelle can update them when the configuration changes.
		"vite_bundler": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"vite": true,
			},
			MergeableAttrs: map[string]bool{
				"vite":         true,
				"node_modules": true,
			},
		},
		// ts_bundle is generated at the workspace root for the primary
		// application bundle. staging_srcs, entry_point, and bundler are
		// mergeable; mode and html are typically stable after initial generation.
		"ts_bundle": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"entry_point": true,
			},
			MergeableAttrs: map[string]bool{
				"entry_point":  true,
				"bundler":      true,
				"staging_srcs": true,
				"vite_config":  true,
				"mode":         true,
				"html":         true,
				"minify":       true,
				"sourcemap":    true,
				"tags":         true,
			},
		},
		// filegroup is generated in stage-dir sub-packages to export sources
		// for ts_bundle.staging_srcs. Only the srcs attr is managed by Gazelle.
		"filegroup": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"srcs": true,
			},
			MergeableAttrs: map[string]bool{
				"srcs":       true,
				"visibility": true,
			},
		},
	}
}

// Fix repairs deprecated or obsolete usage in an existing build file. Called
// before the file is indexed. Only structural/rename fixes are applied here;
// fixes that delete rules are guarded by c.ShouldFix.
func (l *tsLang) Fix(_ *config.Config, _ *rule.File) {}

// GenerateRules produces the ts_compile and ts_test rules for the directory
// described by args. The heavy lifting lives in generate.go.
func (l *tsLang) GenerateRules(args language.GenerateArgs) language.GenerateResult {
	return generateRules(args)
}

// Imports returns the set of ImportSpecs that can be used to import the given
// rule. These are indexed by Gazelle and later queried by Resolve. For
// ts_compile targets we index by the package-relative import path that other
// TypeScript files would use to reference this target.
func (l *tsLang) Imports(c *config.Config, r *rule.Rule, f *rule.File) []resolve.ImportSpec {
	return importsForRule(c, r, f)
}

// Embeds returns labels of rules that the given rule embeds. TypeScript rules
// do not embed other rules, so this always returns nil.
func (l *tsLang) Embeds(_ *rule.Rule, _ label.Label) []label.Label { return nil }

// Resolve translates the opaque imports value (produced by GenerateRules via
// GenerateResult.Imports) into concrete Bazel deps on the rule r.
func (l *tsLang) Resolve(
	c *config.Config,
	ix *resolve.RuleIndex,
	rc *repo.RemoteCache,
	r *rule.Rule,
	imports any,
	from label.Label,
) {
	resolveImports(c, ix, r, imports, from)
}
