// Package typescript is the Gazelle language for rules_typescript: a package
// per tsconfig.json program, its targets from tsgo's listing.
package typescript

import (
	"flag"
	"fmt"
	"os"

	"github.com/bazelbuild/bazel-gazelle/config"
	"github.com/bazelbuild/bazel-gazelle/label"
	"github.com/bazelbuild/bazel-gazelle/language"
	"github.com/bazelbuild/bazel-gazelle/repo"
	"github.com/bazelbuild/bazel-gazelle/resolve"
	"github.com/bazelbuild/bazel-gazelle/rule"
)

const languageName = "typescript"

// tsLang is the Gazelle language extension for TypeScript.
type tsLang struct {
	language.BaseLifecycleManager
	programs *programStore
}

// NewLanguage returns a new instance of the TypeScript Gazelle language extension.
// Gazelle discovers extensions via this symbol.
func NewLanguage() language.Language {
	return &tsLang{}
}

// Name returns the canonical name of this language extension. It is used as a
// prefix when resolving import specs and when keying per-language config state.
func (l *tsLang) Name() string { return languageName }

func (l *tsLang) RegisterFlags(fs *flag.FlagSet, _ string, c *config.Config) {
	tc := defaultTsConfig()
	fs.StringVar(&tc.programs.tsgoFlag, "ts_tsgo", "",
		"the tsgo binary that lists each tsconfig.json program; the default is the toolchain's, in the Gazelle binary's runfiles")
	fs.BoolVar(&tc.programs.verbose, "ts_verbose", false,
		"say which tsgo lists the programs, one line per tsconfig.json with "+
			"what it listed or why it is not a package, how many are, and the "+
			".ts files no program lists")
	l.programs = tc.programs
	c.Exts[languageName] = tc
}

func (l *tsLang) CheckFlags(_ *flag.FlagSet, c *config.Config) error {
	if tsgo := getConfig(c).programs.tsgoFlag; tsgo != "" {
		if _, err := os.Stat(tsgo); err != nil {
			return fmt.Errorf("-ts_tsgo: %w", err)
		}
	}
	return nil
}

// KnownDirectives is empty: the tsconfig.json, the lockfile and the manifest
// say everything; # gazelle:exclude, # gazelle:resolve and # keep are core's.
func (l *tsLang) KnownDirectives() []string {
	return nil
}

// Configure lists the directory's program and records what its BUILD file
// declares; see configureTsConfig.
func (l *tsLang) Configure(c *config.Config, rel string, f *rule.File) {
	configureTsConfig(c, rel, f)
}

// tsDefsSymbols are the rule kinds this extension loads from //ts:defs.bzl.
// Loads and ApparentLoads must name the same set, so they read one list.
var tsDefsSymbols = []string{
	"ts_codegen", "ts_compile", "ts_config", "ts_lint", "ts_test",
}

// Loads returns the load info for the rules generated by this extension.
// Deprecated in favour of ModuleAwareLanguage.ApparentLoads, but still
// required by Gazelle for compatibility.
func (l *tsLang) Loads() []rule.LoadInfo {
	return []rule.LoadInfo{
		{
			Name:    "@rules_typescript//ts:defs.bzl",
			Symbols: tsDefsSymbols,
		},
	}
}

// ApparentLoads returns load info aware of the Bzlmod apparent repository name.
// This satisfies the ModuleAwareLanguage optional interface.
func (l *tsLang) ApparentLoads(moduleToApparentName func(string) string) []rule.LoadInfo {
	rulesTs := moduleToApparentName("rules_typescript")
	if rulesTs == "" {
		rulesTs = "rules_typescript"
	}
	return []rule.LoadInfo{
		{
			Name:    "@" + rulesTs + "//ts:defs.bzl",
			Symbols: tsDefsSymbols,
		},
	}
}

// Kinds returns metadata about each rule kind this extension generates. Gazelle
// uses this metadata to match generated rules against existing rules and to
// determine which attributes are mergeable.
func (l *tsLang) Kinds() map[string]rule.KindInfo {
	return map[string]rule.KindInfo{
		"ts_compile": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"srcs": true,
			},
			MergeableAttrs: map[string]bool{
				"srcs":       true,
				"deps":       true,
				"visibility": true,
				"tsconfig":   true,
			},
			ResolveAttrs: map[string]bool{
				"deps": true,
			},
		},
		"ts_test": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"srcs": true,
			},
			MergeableAttrs: map[string]bool{
				"srcs":     true,
				"deps":     true,
				"tsconfig": true,
				"config":   true,
			},
			// Written at Resolve, from the config's listing: its modules and
			// the pool's attributes.
			ResolveAttrs: map[string]bool{
				"deps":              true,
				"config_srcs":       true,
				"wrangler_config":   true,
				"coverage_provider": true,
			},
		},
		// ts_config makes a package's tsconfig.json a label. deps and jsx are
		// read out of the file, so both are Gazelle's; a hand value needs # keep.
		"ts_config": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"src": true,
			},
			MergeableAttrs: map[string]bool{
				"src":        true,
				"deps":       true,
				"jsx":        true,
				"visibility": true,
			},
		},
		"ts_lint": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"srcs": true,
			},
			MergeableAttrs: map[string]bool{
				"srcs":             true,
				"linter":           true,
				"linter_binary":    true,
				"config":           true,
				"fail_on_warnings": true,
			},
		},
		// ts_codegen is hand-written and never generated; a Kind so that its
		// out_dir is indexed (codegenTreeSpecs) and its outs are deps (D9).
		"ts_codegen": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
		},
		// filegroup makes a vitest config, or the wrangler config it names, a
		// label for the packages below it.
		"filegroup": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"srcs": true,
			},
			MergeableAttrs: map[string]bool{
				"srcs":       true,
				"visibility": true,
			},
		},
	}
}

// Fix repairs deprecated or obsolete usage in an existing build file. Called
// before the file is indexed. Only structural/rename fixes are applied here;
// fixes that delete rules are guarded by c.ShouldFix.
func (l *tsLang) Fix(_ *config.Config, _ *rule.File) {}

// GenerateRules produces the ts_compile and ts_test rules for the directory
// described by args. The heavy lifting lives in generate.go.
func (l *tsLang) GenerateRules(args language.GenerateArgs) language.GenerateResult {
	return generateRules(args)
}

func (l *tsLang) DoneGeneratingRules() {
	if l.programs != nil {
		l.programs.reportCensus()
		l.programs.reportUnlisted()
		l.programs.reportUnowned()
	}
}

// Imports indexes a rule's srcs by repository path, which is what Resolve
// looks an edge target up by; see importsForRule.
func (l *tsLang) Imports(c *config.Config, r *rule.Rule, f *rule.File) []resolve.ImportSpec {
	return importsForRule(c, r, f)
}

// Embeds returns labels of rules that the given rule embeds. TypeScript rules
// do not embed other rules, so this always returns nil.
func (l *tsLang) Embeds(_ *rule.Rule, _ label.Label) []label.Label { return nil }

// Resolve writes r's deps from the edges GenerateRules handed it.
func (l *tsLang) Resolve(
	c *config.Config,
	ix *resolve.RuleIndex,
	_ *repo.RemoteCache,
	r *rule.Rule,
	imports any,
	from label.Label,
) {
	if imps, ok := imports.(*ruleImports); ok && imps != nil {
		resolveEdges(c, ix, r, imps, from)
	}
}
