// Package typescript implements a Gazelle language extension that generates
// Bazel BUILD files for TypeScript projects using rules_typescript.
//
// It supports ts_compile and ts_test rules from @rules_typescript//ts:defs.bzl,
// infers package boundaries from index.ts/tsx files, and resolves imports to
// Bazel labels via the rule index, npm mappings, and path alias configuration.
package typescript

import (
	"context"
	"flag"

	"github.com/bazelbuild/bazel-gazelle/config"
	"github.com/bazelbuild/bazel-gazelle/label"
	"github.com/bazelbuild/bazel-gazelle/language"
	"github.com/bazelbuild/bazel-gazelle/repo"
	"github.com/bazelbuild/bazel-gazelle/resolve"
	"github.com/bazelbuild/bazel-gazelle/rule"
)

const languageName = "typescript"

// tsLang is the Gazelle language extension for TypeScript.
//
// cycles is the whole run's dep graph over the targets this extension
// generates. A cross-package cycle is not visible from any one GenerateRules
// call, and the resolver is where every edge becomes a label, so it is
// recorded there and read once the last one is in.
type tsLang struct {
	language.BaseLifecycleManager
	cycles cycleGraph
}

// NewLanguage returns a new instance of the TypeScript Gazelle language extension.
// Gazelle discovers extensions via this symbol.
func NewLanguage() language.Language {
	return &tsLang{}
}

// Name returns the canonical name of this language extension. It is used as a
// prefix when resolving import specs and when keying per-language config state.
func (l *tsLang) Name() string { return languageName }

// RegisterFlags registers command-line flags for the TypeScript extension.
// Currently no top-level flags are defined; configuration is driven by
// in-BUILD directives.
func (l *tsLang) RegisterFlags(_ *flag.FlagSet, _ string, _ *config.Config) {}

// CheckFlags validates flags after they have been parsed. No-op for now.
func (l *tsLang) CheckFlags(_ *flag.FlagSet, _ *config.Config) error { return nil }

// KnownDirectives lists the # gazelle: directives this extension understands.
// Gazelle emits a warning for unrecognised directives, so every directive
// that Configure interprets must be listed here.
func (l *tsLang) KnownDirectives() []string {
	return []string{
		// Control whether every dir or only index.ts dirs are package boundaries.
		directivePackageBoundary,
		// Suppress all TypeScript rule generation for this directory tree.
		directiveIgnore,
		// Override the target name for the primary ts_compile rule in this dir.
		directiveTargetName,
		// Emit a warning for imports that cannot be resolved to a Bazel label.
		directiveWarnUnresolved,
		// Select the .d.ts emitter on generated ts_compile rules.
		directiveDeclarations,
		// Add a TypeScript path alias mapping (can appear multiple times).
		directivePathAlias,
		// Append a Bazel label to every ts_test deps list in this tree.
		directiveRuntimeDep,
		// Append a Bazel label to every ts_compile and ts_test deps list here.
		directiveAmbientTypes,
		// Add a file glob pattern to exclude from source targets.
		directiveExclude,
		// Add a directory basename Gazelle does not enter.
		directiveExcludeDir,
		// Register a custom ts_codegen target via a directive.
		directiveCodegen,
		// Name the npm hub repo that bare specifiers in this tree resolve into.
		directiveNpmHub,
		// Overlay a hand-written npm name -> label mapping on the inventory.
		directiveNpmMapping,
		// Declare what an asset extension's import resolves to in this tree.
		directiveAssetDeclarationType,
		// Admit JavaScript sources of the named extensions into generated srcs.
		directiveJSSrcs,
	}
}

// Configure reads directives from the build file in directory rel and updates
// the per-directory tsConfig stored in c.Exts.
func (l *tsLang) Configure(c *config.Config, rel string, f *rule.File) {
	configureTsConfig(c, rel, f)
}

// tsDefsSymbols are the rule kinds this extension loads from //ts:defs.bzl.
// Loads and ApparentLoads must name the same set, so they read one list.
var tsDefsSymbols = []string{
	"asset_library", "css_library", "css_module", "json_library",
	"next_build", "next_dev_server", "sveltekit_build", "ts_add_package",
	"ts_bundle", "ts_codegen", "ts_compile", "ts_config", "ts_dev_server",
	"ts_lint", "ts_pnpm", "ts_test",
}

// Loads returns the load info for the rules generated by this extension.
// Deprecated in favour of ModuleAwareLanguage.ApparentLoads, but still
// required by Gazelle for compatibility.
func (l *tsLang) Loads() []rule.LoadInfo {
	return []rule.LoadInfo{
		{
			Name:    "@rules_typescript//ts:defs.bzl",
			Symbols: tsDefsSymbols,
		},
		{
			Name:    "@rules_typescript//npm:defs.bzl",
			Symbols: []string{"node_modules"},
		},
		{
			Name:    "@rules_typescript//vite:bundler.bzl",
			Symbols: []string{"vite_bundler"},
		},
	}
}

// ApparentLoads returns load info aware of the Bzlmod apparent repository name.
// This satisfies the ModuleAwareLanguage optional interface.
func (l *tsLang) ApparentLoads(moduleToApparentName func(string) string) []rule.LoadInfo {
	rulesTs := moduleToApparentName("rules_typescript")
	if rulesTs == "" {
		rulesTs = "rules_typescript"
	}
	return []rule.LoadInfo{
		{
			Name:    "@" + rulesTs + "//ts:defs.bzl",
			Symbols: tsDefsSymbols,
		},
		{
			Name:    "@" + rulesTs + "//npm:defs.bzl",
			Symbols: []string{"node_modules"},
		},
		{
			Name:    "@" + rulesTs + "//vite:bundler.bzl",
			Symbols: []string{"vite_bundler"},
		},
	}
}

// Kinds returns metadata about each rule kind this extension generates. Gazelle
// uses this metadata to match generated rules against existing rules and to
// determine which attributes are mergeable.
func (l *tsLang) Kinds() map[string]rule.KindInfo {
	return map[string]rule.KindInfo{
		"asset_library": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"srcs": true,
			},
			MergeableAttrs: map[string]bool{
				"srcs":       true,
				"deps":       true,
				"visibility": true,
			},
		},
		"css_library": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"srcs": true,
			},
			MergeableAttrs: map[string]bool{
				"srcs":       true,
				"deps":       true,
				"visibility": true,
			},
		},
		"css_module": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"srcs": true,
			},
			MergeableAttrs: map[string]bool{
				"srcs":       true,
				"deps":       true,
				"visibility": true,
			},
		},
		"json_library": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"srcs": true,
			},
			MergeableAttrs: map[string]bool{
				"srcs":       true,
				"deps":       true,
				"visibility": true,
			},
		},
		"ts_compile": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"srcs": true,
			},
			MergeableAttrs: map[string]bool{
				"srcs":            true,
				"deps":            true,
				"visibility":      true,
				"path_aliases":    true,
				"path_alias_srcs": true,
				"declarations":    true,
				"tsconfig":        true,
			},
			ResolveAttrs: map[string]bool{
				"deps":            true,
				"path_alias_srcs": true,
			},
		},
		"ts_test": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"srcs": true,
			},
			MergeableAttrs: map[string]bool{
				"srcs":            true,
				"deps":            true,
				"tsconfig":        true,
				"path_aliases":    true,
				"path_alias_srcs": true,
			},
			ResolveAttrs: map[string]bool{
				"deps":            true,
				"path_alias_srcs": true,
			},
		},
		// ts_config makes a package's hand-written tsconfig.json a label the
		// targets in its subpackages can name. `deps` is the extends chain
		// Gazelle reads out of the tsconfig, so it is Gazelle's to recompute and
		// a hand-written value needs a "# keep" to survive the next run.
		"ts_config": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"src": true,
			},
			MergeableAttrs: map[string]bool{
				"src":        true,
				"deps":       true,
				"visibility": true,
			},
		},
		"ts_lint": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"srcs": true,
			},
			MergeableAttrs: map[string]bool{
				"srcs":             true,
				"linter":           true,
				"linter_binary":    true,
				"config":           true,
				"fail_on_warnings": true,
			},
		},
		// node_modules is no longer generated by Gazelle (ts_test auto-generates it
		// internally), but we keep it in Kinds so that Gazelle can still recognise
		// and delete stale node_modules rules from existing BUILD files during
		// migration.
		"node_modules": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"deps": true,
			},
			MergeableAttrs: map[string]bool{
				"deps": true,
			},
		},
		"ts_dev_server": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"entry_point": true,
			},
			MergeableAttrs: map[string]bool{
				"entry_point":  true,
				"port":         true,
				"host":         true,
				"open":         true,
				"node_modules": true,
				"plugin":       true,
				"bundler":      true,
				"visibility":   true,
			},
		},
		// ts_codegen is generated by auto-detection and # gazelle:ts_codegen directives.
		// srcs and node_modules are intentionally excluded from MergeableAttrs:
		//   - srcs: initial generation sets the correct value (files or a glob
		//     expression). Merging srcs would corrupt glob expressions that must
		//     remain as Starlark expressions in the BUILD file.
		//   - node_modules: the user may point to a specific node_modules target
		//     holding only the generator's own deps. Subsequent Gazelle runs
		//     should not override that with the generic ":node_modules" default.
		// outs and out_dir remain mergeable so Gazelle can update declared outputs
		// when the generator configuration changes.
		"ts_codegen": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"generator": true,
			},
			MergeableAttrs: map[string]bool{
				"outs":       true,
				"out_dir":    true,
				"visibility": true,
			},
		},
		// vite_bundler is generated at the workspace root when a Vite-based
		// framework is detected. node_modules and vite attrs are mergeable so
		// Gazelle can update them when the configuration changes.
		"vite_bundler": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"vite": true,
			},
			MergeableAttrs: map[string]bool{
				"vite":         true,
				"node_modules": true,
			},
		},
		// Emitted on every run, so MergeableAttrs names exactly what the
		// generator writes: MergeRules deletes a mergeable attr a candidate omits.

		// srcs is absent because a glob() is not an expression the merger merges;
		// setGeneratedGlob writes that one straight onto the rule.
		"ts_bundle": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"entry_point": true,
			},
			MergeableAttrs: map[string]bool{
				"entry_point":  true,
				"bundler":      true,
				"staging_srcs": true,
				"vite_config":  true,
				"mode":         true,
				"html":         true,
			},
		},
		"next_build": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"node_modules": true,
			},
			MergeableAttrs: map[string]bool{
				"node_modules": true,
				"config":       true,
				"tsconfig":     true,
				"staging_srcs": true,
			},
		},
		// next_dev_server is generated beside next_build: `next dev` needs the
		// same npm tree and nothing else, since it reads its routes from source.
		"next_dev_server": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"node_modules": true,
			},
			MergeableAttrs: map[string]bool{
				"node_modules": true,
			},
		},
		"sveltekit_build": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"node_modules": true,
			},
			MergeableAttrs: map[string]bool{
				"node_modules":  true,
				"config":        true,
				"svelte_config": true,
				"staging_srcs":  true,
			},
		},
		// filegroup is generated twice: in stage-dir sub-packages to export
		// sources for ts_bundle.staging_srcs, and beside a tsconfig.json for
		// the declaration files it names in compilerOptions.types. Only the
		// srcs attr is managed by Gazelle.
		"filegroup": {
			MatchAny:   false,
			MatchAttrs: []string{"name"},
			NonEmptyAttrs: map[string]bool{
				"srcs": true,
			},
			MergeableAttrs: map[string]bool{
				"srcs":       true,
				"visibility": true,
			},
		},
		// ts_pnpm and ts_add_package are macros generated at the workspace root
		// when a pnpm-lock.yaml is detected. They wrap the hermetic pnpm binary.
		// They are kept in Kinds so that Gazelle can recognise and merge them
		// correctly; the only attr it manages is ts_add_package's pnpm_lock,
		// which names the hub whose lockfile the target edits.
		"ts_pnpm": {
			MatchAny:       false,
			MatchAttrs:     []string{"name"},
			NonEmptyAttrs:  map[string]bool{},
			MergeableAttrs: map[string]bool{},
		},
		"ts_add_package": {
			MatchAny:       false,
			MatchAttrs:     []string{"name"},
			NonEmptyAttrs:  map[string]bool{},
			MergeableAttrs: map[string]bool{"pnpm_lock": true},
		},
	}
}

// Fix repairs deprecated or obsolete usage in an existing build file. Called
// before the file is indexed. Only structural/rename fixes are applied here;
// fixes that delete rules are guarded by c.ShouldFix.
func (l *tsLang) Fix(_ *config.Config, _ *rule.File) {}

// GenerateRules produces the ts_compile and ts_test rules for the directory
// described by args. The heavy lifting lives in generate.go.
func (l *tsLang) GenerateRules(args language.GenerateArgs) language.GenerateResult {
	return generateRules(args)
}

// Imports returns the set of ImportSpecs that can be used to import the given
// rule. These are indexed by Gazelle and later queried by Resolve. For
// ts_compile targets we index by the package-relative import path that other
// TypeScript files would use to reference this target.
func (l *tsLang) Imports(c *config.Config, r *rule.Rule, f *rule.File) []resolve.ImportSpec {
	return importsForRule(c, r, f)
}

// Embeds returns labels of rules that the given rule embeds. TypeScript rules
// do not embed other rules, so this always returns nil.
func (l *tsLang) Embeds(_ *rule.Rule, _ label.Label) []label.Label { return nil }

// Resolve translates the opaque imports value (produced by GenerateRules via
// GenerateResult.Imports) into concrete Bazel deps on the rule r.
func (l *tsLang) Resolve(
	c *config.Config,
	ix *resolve.RuleIndex,
	rc *repo.RemoteCache,
	r *rule.Rule,
	imports any,
	from label.Label,
) {
	l.cycles.note(c, ix, r, from, resolveImports(c, ix, r, imports, from))
}

// AfterResolvingDeps runs the whole-graph checks, which is what this hook is
// for: cmd/gazelle calls it once, after the last Resolve and before any BUILD
// file is written.
func (l *tsLang) AfterResolvingDeps(_ context.Context) {
	l.cycles.reportCycles()
}
