package typescript

// The compilerOptions baseline Gazelle names, and the one question that decides
// whether it may: will Gazelle write a BUILD file into the directory holding
// the tsconfig.json? A label into a directory that never becomes a package
// fails analysis for the whole workspace, and a file in such a directory stats
// perfectly well -- so nothing short of asking about package-ness catches it.

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/bazelbuild/bazel-gazelle/rule"
)

// attrOf is the value of one attribute on one generated rule, and whether the
// rule is there at all.
func attrOf(t *testing.T, root, pkg, kind, name, attr string) (string, bool) {
	t.Helper()
	for _, r := range loadRules(t, root, pkg) {
		if r.Kind() == kind && r.Name() == name {
			return r.AttrString(attr), true
		}
	}
	return "", false
}

func hasBuildFile(root, pkg string) bool {
	_, err := os.Stat(filepath.Join(root, filepath.FromSlash(pkg), "BUILD.bazel"))
	return err == nil
}

// The layout that made the first attempt at this emit a dangling label: a pnpm
// workspace member whose root holds package.json and tsconfig.json and nothing
// else, with the sources one directory down. That root classifies no source, so
// generation there returns before it writes anything -- and the label a
// subpackage computes for the tsconfig has no package to resolve against.
func TestTsConfigBaselineResolvesInThePnpmLayout(t *testing.T) {
	root := t.TempDir()
	writeWorkspace(t, root, map[string]string{
		"package.json":                   `{"name":"w"}` + "\n",
		"pnpm-workspace.yaml":            "packages:\n  - packages/*\n",
		"packages/core/package.json":     `{"name":"@w/core"}` + "\n",
		"packages/core/tsconfig.json":    `{"compilerOptions":{"lib":["es2022"]}}` + "\n",
		"packages/core/src/index.ts":     "export * from \"./util\";\n",
		"packages/core/src/util.ts":      "export const util = 1;\n",
		"packages/core/src/util.test.ts": "export const t = 1;\n",
	})
	captureLog(t, func() { convergeGazelle(t, root) })

	if !hasBuildFile(root, "packages/core") {
		t.Fatalf("no BUILD file in packages/core, so //packages/core:%s names a target in a "+
			"package Bazel never loads", tsConfigTargetName)
	}
	want := "//packages/core:" + tsConfigTargetName
	for _, target := range []struct{ kind, name string }{{"ts_compile", "src"}, {"ts_test", "src_test"}} {
		got, ok := attrOf(t, root, "packages/core/src", target.kind, target.name, "tsconfig")
		if !ok {
			t.Fatalf("generation wrote no %s(%s) in packages/core/src", target.kind, target.name)
		}
		if got != want {
			t.Errorf("%s(%s).tsconfig = %q, want %q", target.kind, target.name, got, want)
		}
	}
	if src, _ := attrOf(t, root, "packages/core", "ts_config", tsConfigTargetName, "src"); src != "tsconfig.json" {
		t.Errorf("ts_config(%s).src = %q, want %q", tsConfigTargetName, src, "tsconfig.json")
	}
	if dangling := danglingLabels(t, root); len(dangling) > 0 {
		t.Errorf("%d label(s) no target satisfies:\n      %s",
			len(dangling), strings.Join(dangling, "\n      "))
	}
}

// The nearest file walking up, the way tsserver resolves one -- not the
// workspace root's for everything below it.
func TestTsConfigBaselineTakesTheNearestFile(t *testing.T) {
	root := t.TempDir()
	writeWorkspace(t, root, map[string]string{
		"package.json":                `{"name":"w"}` + "\n",
		"tsconfig.json":               `{"compilerOptions":{"strict":true}}` + "\n",
		"packages/core/tsconfig.json": `{"compilerOptions":{"lib":["es2022"]}}` + "\n",
		"packages/core/src/index.ts":  "export const core = 1;\n",
		"packages/app/src/main.ts":    "export const main = 1;\n",
	})
	captureLog(t, func() { convergeGazelle(t, root) })

	for pkg, want := range map[string]string{
		"packages/core/src": "//packages/core:" + tsConfigTargetName,
		"packages/app/src":  "//:" + tsConfigTargetName,
	} {
		got, ok := attrOf(t, root, pkg, "ts_compile", "src", "tsconfig")
		if !ok {
			t.Fatalf("generation wrote no ts_compile(src) in %s", pkg)
		}
		if got != want {
			t.Errorf("%s ts_compile(src).tsconfig = %q, want %q", pkg, got, want)
		}
	}
}

// A tsconfig.json ts_refresh_tsconfig wrote is built out of the very targets
// that would name it as their baseline.
func TestTsConfigBaselineSkipsTheGeneratedFile(t *testing.T) {
	root := t.TempDir()
	writeWorkspace(t, root, map[string]string{
		"package.json": `{"name":"w"}` + "\n",
		"tsconfig.json": `{"_comment":"Generated by 'bazel run //:refresh_tsconfig'. Do not edit manually.",` +
			`"compilerOptions":{"strict":true}}` + "\n",
		"src/index.ts": "export const a = 1;\n",
	})
	captureLog(t, func() { convergeGazelle(t, root) })

	if got, _ := attrOf(t, root, "src", "ts_compile", "src", "tsconfig"); got != "" {
		t.Errorf("ts_compile(src).tsconfig = %q, want no attribute: the file is generated", got)
	}
	if _, ok := attrOf(t, root, "", "ts_config", tsConfigTargetName, "src"); ok {
		t.Error("generation wrote a ts_config for a tsconfig.json it generates itself")
	}
}

// The repair the first attempt reached for and the reason it does not work: in a
// roll-up mode the walk stops at any directory that is a package of its own, so
// a BUILD file written just to hold the ts_config takes every source beneath it
// out of the target that was compiling them. Refusing to name the file is the
// alternative, and the sources have to still be there afterwards.
func TestTsConfigBaselineRefusesRatherThanBreakARollUp(t *testing.T) {
	root := t.TempDir()
	writeWorkspace(t, root, map[string]string{
		"BUILD.bazel":                 "# gazelle:ts_package_boundary index-only\n",
		"package.json":                `{"name":"w"}` + "\n",
		"packages/core/tsconfig.json": `{"compilerOptions":{"lib":["es2022"]}}` + "\n",
		"packages/core/src/index.ts":  "export const core = 1;\n",
		"packages/core/other/util.ts": "export const util = 1;\n",
	})
	logged := captureLog(t, func() { convergeGazelle(t, root) })

	if hasBuildFile(root, "packages/core") {
		t.Error("generation made packages/core a package in a roll-up mode, which drops every " +
			"source beneath it from the target above")
	}
	if got, _ := attrOf(t, root, "packages/core/src", "ts_compile", "src", "tsconfig"); got != "" {
		t.Errorf("ts_compile(src).tsconfig = %q, want no attribute: nothing writes that package", got)
	}
	if !strings.Contains(logged, "packages/core") || !strings.Contains(logged, "ts_package_boundary") {
		t.Errorf("the refusal was silent; log said:\n%s", logged)
	}

	// The roll-up the refusal protects: the source in the non-package directory
	// is still compiled by the package above it.
	var rolled bool
	for _, r := range loadRules(t, root, "") {
		if r.Kind() == "ts_compile" {
			for _, src := range r.AttrStrings("srcs") {
				if src == "packages/core/other/util.ts" {
					rolled = true
				}
			}
		}
	}
	if !rolled {
		t.Errorf("packages/core/other/util.ts is compiled by nothing:\n%s", buildFileText(t, root, ""))
	}
	if dangling := danglingLabels(t, root); len(dangling) > 0 {
		t.Errorf("%d label(s) no target satisfies:\n      %s",
			len(dangling), strings.Join(dangling, "\n      "))
	}
}

// Whether a package there costs anything depends on the boundary mode, so the
// directory holding the tsconfig and the one naming it have to agree on it. A
// directive between them means the mode inherited by the second says nothing
// about the first, and a guess either way is a label nothing writes.
func TestTsConfigBaselineRefusesWhenTheBoundaryModeIsOverriddenBetween(t *testing.T) {
	root := t.TempDir()
	writeWorkspace(t, root, map[string]string{
		"BUILD.bazel":         "# gazelle:ts_package_boundary index-only\n",
		"package.json":        `{"name":"w"}` + "\n",
		"lib/tsconfig.json":   `{"compilerOptions":{"strict":true}}` + "\n",
		"lib/sub/BUILD.bazel": "# gazelle:ts_package_boundary every-dir\n",
		"lib/sub/thing.ts":    "export const thing = 1;\n",
	})
	logged := captureLog(t, func() { convergeGazelle(t, root) })

	if got, _ := attrOf(t, root, "lib/sub", "ts_compile", "sub", "tsconfig"); got != "" {
		t.Errorf("ts_compile(sub).tsconfig = %q, want no attribute", got)
	}
	if !strings.Contains(logged, "ts_package_boundary directive between") {
		t.Errorf("the refusal was silent; log said:\n%s", logged)
	}
	if dangling := danglingLabels(t, root); len(dangling) > 0 {
		t.Errorf("%d label(s) no target satisfies:\n      %s",
			len(dangling), strings.Join(dangling, "\n      "))
	}
}

// labelResolves is what a green suite rests on, and file existence is not the
// question it has to answer.
func TestLabelResolvesAsksAboutPackages(t *testing.T) {
	root := t.TempDir()
	writeWorkspace(t, root, map[string]string{
		"pkg/tsconfig.json":     "{}\n",
		"pkg/sub/tsconfig.json": "{}\n",
	})

	if labelResolves(t, root, "pkg", "tsconfig.json") {
		t.Error("//pkg:tsconfig.json resolved with no BUILD file in pkg, so nothing distinguishes " +
			"a source of a package from a file in a directory Bazel never loads")
	}

	writeWorkspace(t, root, map[string]string{"pkg/BUILD.bazel": "\n"})
	if !labelResolves(t, root, "pkg", "tsconfig.json") {
		t.Error("//pkg:tsconfig.json did not resolve from the package that holds it")
	}
	if !labelResolves(t, root, "pkg", "sub/tsconfig.json") {
		t.Error("//pkg:sub/tsconfig.json did not resolve: sub is not a package of its own")
	}

	writeWorkspace(t, root, map[string]string{"pkg/sub/BUILD.bazel": "\n"})
	if labelResolves(t, root, "pkg", "sub/tsconfig.json") {
		t.Error("//pkg:sub/tsconfig.json resolved after sub became a package of its own, where " +
			"the file belongs to //pkg/sub and Bazel rejects the label")
	}
}

// A rule generated in the directory that holds the file names it without a
// package prefix, since the BUILD file making the label resolve is the one
// being written.
func TestTsConfigBaselineNamesItsOwnPackage(t *testing.T) {
	root := t.TempDir()
	writeWorkspace(t, root, map[string]string{
		"package.json":      `{"name":"w"}` + "\n",
		"lib/tsconfig.json": `{"compilerOptions":{"strict":true}}` + "\n",
		"lib/index.ts":      "export const a = 1;\n",
	})
	captureLog(t, func() { convergeGazelle(t, root) })

	want := ":" + tsConfigTargetName
	if got, _ := attrOf(t, root, "lib", "ts_compile", "lib", "tsconfig"); got != want {
		t.Errorf("ts_compile(lib).tsconfig = %q, want %q", got, want)
	}
	var found *rule.Rule
	for _, r := range loadRules(t, root, "lib") {
		if r.Kind() == "ts_config" {
			found = r
		}
	}
	if found == nil {
		t.Fatalf("generation wrote no ts_config in lib:\n%s", buildFileText(t, root, "lib"))
	}
}
