/**
 * TanStack Router configuration.
 *
 * Creates the router instance with the route tree. The route tree is normally
 * auto-generated by @tanstack/router-cli, but here we define it manually to
 * keep the example self-contained and buildable with Bazel.
 *
 * isolatedDeclarations: we wrap router creation in a function whose return
 * type is AnyRouter (a base interface exported by @tanstack/react-router).
 * This avoids annotating the complex parameterized Route<...> generics while
 * still satisfying the isolated declarations requirement for public exports.
 *
 * getRouter() is also exported to satisfy the TanStack Start framework API.
 * The Start plugin expects a router entry file that exports `getRouter()` — an
 * async function that creates a fresh router instance. During SSR, TanStack
 * Start calls getRouter() per request to get a clean router. For the SPA
 * singleton case, getRouter() simply resolves the shared `router` instance.
 */

import {
  createRouter,
  createRootRoute,
  createRoute,
  createMemoryHistory,
} from "@tanstack/react-router";
import type { AnyRouter } from "@tanstack/react-router";

// createAppRouter is a function (not a const) so oxc can infer its return type
// from the function body without needing a ReturnType<> annotation on a complex
// generic chain.  We export the type alias AppRouter for downstream consumers.
export type AppRouter = AnyRouter;

// Build the router and export it as the opaque AppRouter interface.
// Internal details (specific route types) are private to this module.
function buildRouter(): AppRouter {
  const rootRoute = createRootRoute();

  const indexRoute = createRoute({
    getParentRoute: () => rootRoute,
    path: "/",
  });

  const aboutRoute = createRoute({
    getParentRoute: () => rootRoute,
    path: "/about",
  });

  const usersRoute = createRoute({
    getParentRoute: () => rootRoute,
    path: "/users",
  });

  const routeTree = rootRoute.addChildren([indexRoute, aboutRoute, usersRoute]);

  const memoryHistory = createMemoryHistory({ initialEntries: ["/"] });

  return createRouter({ routeTree, history: memoryHistory });
}

// The singleton router instance used by the SPA entry point and tests.
export const router: AppRouter = buildRouter();

// getRouter is required by the TanStack Start framework plugin (@tanstack/react-start).
// The plugin's SSR client (hydrateStart.js) imports `getRouter` from the router
// entry file via the #tanstack-router-entry alias. For this SPA example, we
// simply return the shared singleton router.
export async function getRouter(): Promise<AppRouter> {
  return router;
}
