load("@rules_typescript//ts:defs.bzl", "ts_compile", "ts_config")

ts_compile(
    name = "app",
    srcs = ["index.ts"],
    node_modules = "//:node_modules",
    tsconfig = ":tsconfig",
    visibility = ["//visibility:public"],
    deps = ["//src/lib"],
)

ts_config(
    name = "tsconfig",
    src = "tsconfig.json",
    visibility = ["//visibility:public"],
    deps = ["//:tsconfig"],
)
