// workspace_consumer.ts — Tests that @npm//:shared (a workspace alias) resolves
// correctly to //packages/shared:shared via the alias generated by npm_translate_lock.
import { greet } from "shared";

export const message: string = greet("World");
