#!/usr/bin/env bash
# generate.sh — reads schema.txt, writes generated TypeScript.
#
# Usage: generate.sh <schema_file> <output_ts_file>
#
# Each non-comment line in the schema has the form: <name>:<type>
# The generator emits a TypeScript interface and a factory function.

set -euo pipefail

SCHEMA="$1"
OUT="$2"

# Start the output file with the header.
cat > "${OUT}" <<'HEADER'
// GENERATED FILE — do not edit manually.
// Generated by codegen/generate.sh from schema.txt.

export interface GeneratedRecord {
HEADER

# Append one field per schema line (skip blank lines and comments).
while IFS= read -r line; do
    [[ -z "${line}" || "${line}" =~ ^[[:space:]]*# ]] && continue
    name="${line%%:*}"
    type="${line##*:}"
    printf '  readonly %s: %s;\n' "${name}" "${type}" >> "${OUT}"
done < "${SCHEMA}"

# Append the closing brace and factory function.
cat >> "${OUT}" <<'FOOTER'
}

export function createRecord(fields: GeneratedRecord): GeneratedRecord {
  return fields;
}
FOOTER
