#!/usr/bin/env bash
# Writes a global declaration file, the shape `wrangler types` writes: a `.d.ts`
# out a consumer's tsconfig names in `types`.
set -euo pipefail

OUT_FILE=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --out) OUT_FILE="$2"; shift 2 ;;
    *) echo "generate_globals.sh: unknown argument: $1" >&2; exit 1 ;;
  esac
done
[[ -n "$OUT_FILE" ]] || { echo "generate_globals.sh: --out is required" >&2; exit 1; }
mkdir -p "$(dirname "$OUT_FILE")"
cat > "$OUT_FILE" <<'DTS'
// Generated by tests/codegen/generate_globals.sh
declare const GENERATED_STAMP: string;
DTS
