#!/usr/bin/env bash
# Simple test generator for ts_codegen.
# Reads a list of source files and writes a TypeScript barrel export file.
#
# Usage: generator.sh --srcs-dir <dir> --out <output.ts>
set -euo pipefail

SRCS_DIR=""
OUT_FILE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --srcs-dir) SRCS_DIR="$2"; shift 2 ;;
    --out)      OUT_FILE="$2"; shift 2 ;;
    *) echo "generator.sh: unknown argument: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$OUT_FILE" ]]; then
  echo "generator.sh: --out is required" >&2
  exit 1
fi

# Create the output directory if it does not yet exist.
mkdir -p "$(dirname "$OUT_FILE")"

# Write a generated TypeScript file containing a comment with the source dir
# and a simple exported constant so ts_compile can verify the output is valid.
cat > "$OUT_FILE" <<EOF
// Generated by tests/codegen/generator.sh
// srcs_dir: ${SRCS_DIR}

export const GENERATED = true;
export const SRCS_DIR = "${SRCS_DIR}";
EOF
