load("@rules_typescript//ts:defs.bzl", "ts_compile", "ts_test")

ts_compile(
    name = "components",
    srcs = [
        "Button.tsx",
        "Counter.tsx",
        "index.ts",
    ],
    node_modules = "//:node_modules",
    visibility = ["//visibility:public"],
    deps = [
        "//src/hooks",
        "@npm//:react",
    ],
)

ts_test(
    name = "components_test",
    srcs = ["Button.test.tsx"],
    node_modules = "//:node_modules",
    deps = [
        ":components",
        "//src/hooks",
        "@npm//:react",
        "@npm//:vitest",
    ],
)
