package worker_types_test

import (
	"fmt"
	"slices"
	"strings"
	"testing"

	"github.com/mikn/rules_typescript/tests/verify"
)

func TestGeneratedDeclarations(t *testing.T) {
	tree := verify.New(t)
	tree.File("tests/worker_types/worker-configuration.d.ts").Contains(
		"interface Env extends __BaseEnv_Env {}",
		"CACHE: KVNamespace;",
		"GREETING: string;",
		"// Begin runtime types",
		"interface KVNamespace",
	)
}

// wrangler.build.jsonc is wrangler.jsonc plus a build.command that fails. A
// generator that ran it would leave `main` unresolved and the mainModule line out.
func TestBuildCommandIsNotRun(t *testing.T) {
	tree := verify.New(t)
	plain := tree.File("tests/worker_types/worker-configuration.d.ts")
	withBuild := tree.File("tests/worker_types/worker-configuration.build.d.ts")
	const mainModule = `mainModule: typeof import("./src/index");`
	plain.Contains(mainModule)
	withBuild.Contains(mainModule)
	if got, want := withoutHeader(withBuild.Text()), withoutHeader(plain.Text()); got != want {
		t.Errorf("%s differs from %s below the header at %s",
			withBuild.Name(), plain.Name(), firstDifference(got, want))
	}
}

// The header echoes wrangler's argv, and only the build run passes `-c`.
func withoutHeader(text string) string {
	lines := slices.DeleteFunc(strings.Split(text, "\n"), func(line string) bool {
		return strings.HasPrefix(line, "// Generated by Wrangler by running")
	})
	return strings.Join(lines, "\n")
}

func firstDifference(got, want string) string {
	gotLines, wantLines := strings.Split(got, "\n"), strings.Split(want, "\n")
	for i := 0; i < len(gotLines) && i < len(wantLines); i++ {
		if gotLines[i] != wantLines[i] {
			return fmt.Sprintf("line %d:\n  got  %q\n  want %q", i+1, gotLines[i], wantLines[i])
		}
	}
	return fmt.Sprintf("the end: %d lines against %d", len(gotLines), len(wantLines))
}
