load("@rules_typescript//ts:defs.bzl", "ts_compile", "ts_test")

ts_compile(
    name = "validation",
    srcs = [
        "index.ts",
        "userSchema.ts",
    ],
    node_modules = "//:node_modules",
    visibility = ["//visibility:public"],
    deps = ["@npm//:zod"],
)

ts_test(
    name = "validation_test",
    srcs = ["userSchema.test.ts"],
    node_modules = "//:node_modules",
    deps = [
        ":validation",
        "@npm//:vitest",
        "@npm//:zod",
    ],
)
