"""A first-party package the dev servers' entry point imports."""

load("@rules_typescript//ts:defs.bzl", "ts_compile")

package(default_visibility = ["//tests/dev_server:__pkg__"])

# keep
ts_compile(
    name = "lib",
    srcs = ["index.ts"],
    emit = True,  # keep
    visibility = ["//visibility:public"],
)

# keep
ts_compile(
    name = "source_lib",
    srcs = ["index.ts"],
    emit = False,
)
