load("@bazel_binaries//:defs.bzl", "bazel_binaries")
load(
    "@rules_bazel_integration_test//bazel_integration_test:defs.bzl",
    "bazel_integration_test",
    "integration_test_utils",
)
load("//tests/integration:tags.bzl", "nested_bazel_tags")

bazel_integration_test(
    name = "consumer_crates_test",
    timeout = "eternal",
    bazel_binaries = bazel_binaries,
    bazel_version = bazel_binaries.versions.current,
    data = ["//:MODULE.bazel"],
    tags = nested_bazel_tags(),
    test_runner = "//tests/integration/runners:consumer_crates_runner",
    workspace_files = integration_test_utils.glob_workspace_files("workspace"),
    workspace_path = "workspace",
)
