#!/usr/bin/env bash
# test_runner.sh — Integration test: LSP / IDE tsconfig generation.
#
# The rules_bazel_integration_test framework provides:
#   BIT_BAZEL_BINARY  — absolute path to the Bazel binary to use
#   BIT_WORKSPACE_DIR — absolute path to the child workspace directory
#
# This test verifies that `bazel run //:refresh_tsconfig` generates a
# workspace-root tsconfig.json that:
#   1. Contains paths entries for npm packages (e.g. "zod") pointing at
#      real .d.ts files in the Bazel output base.
#   2. Contains paths entries for # gazelle:ts_path_alias directives
#      (e.g. "@/*" maps to "./src/*").
#
# Steps:
#   1. Derive RULES_TS_ROOT from BIT_WORKSPACE_DIR.
#   2. Copy workspace to a writable scratch dir in /tmp.
#   3. Patch MODULE.bazel.
#   4. Copy pnpm-lock.yaml from tests/npm/ in the checkout.
#   5. Run `bazel run //:gazelle` to generate BUILD files.
#   6. Run `bazel build @npm//...` to fetch and extract npm packages.
#   7. Run `bazel run //:refresh_tsconfig` to generate tsconfig.json.
#   8. Assert tsconfig.json contains:
#      a. "zod" entry in compilerOptions.paths pointing at a .d.ts file.
#      b. "@/*" entry in compilerOptions.paths mapping to ./src/*.

set -euo pipefail

# ── Validate framework env vars ───────────────────────────────────────────────
[[ -n "${BIT_BAZEL_BINARY:-}" ]]  || { echo "FAIL: BIT_BAZEL_BINARY not set" >&2; exit 1; }
[[ -n "${BIT_WORKSPACE_DIR:-}" ]] || { echo "FAIL: BIT_WORKSPACE_DIR not set" >&2; exit 1; }

echo "INFO: bazel           = ${BIT_BAZEL_BINARY}"
echo "INFO: workspace_dir   = ${BIT_WORKSPACE_DIR}"

# ── Portable realpath (macOS lacks readlink -f) ──────────────────────────────
_realpath() {
    python3 -c "import os,sys; print(os.path.realpath(sys.argv[1]))" "$1"
}

# ── Derive RULES_TS_ROOT ──────────────────────────────────────────────────────
_RUNFILES_MAIN="${BIT_WORKSPACE_DIR%/tests/integration/lsp}"
[[ "${_RUNFILES_MAIN}" != "${BIT_WORKSPACE_DIR}" ]] || {
    echo "FAIL: BIT_WORKSPACE_DIR does not end with expected suffix" >&2
    echo "      got: ${BIT_WORKSPACE_DIR}" >&2
    exit 1
}
_MODULE_IN_RUNFILES="${_RUNFILES_MAIN}/MODULE.bazel"

if [[ -L "${_MODULE_IN_RUNFILES}" ]]; then
    RULES_TS_ROOT="$(dirname "$(_realpath "${_MODULE_IN_RUNFILES}")")"
elif [[ -f "${_MODULE_IN_RUNFILES}" ]]; then
    RULES_TS_ROOT="$(_realpath "$(dirname "${_MODULE_IN_RUNFILES}")")"
else
    echo "FAIL: cannot locate MODULE.bazel relative to BIT_WORKSPACE_DIR" >&2
    echo "      Tried: ${_MODULE_IN_RUNFILES}" >&2
    exit 1
fi

[[ -d "${RULES_TS_ROOT}/oxc_cli" ]] || {
    echo "FAIL: RULES_TS_ROOT is wrong — oxc_cli dir not found:" >&2
    echo "      ${RULES_TS_ROOT}" >&2
    exit 1
}
echo "INFO: rules_ts_root   = ${RULES_TS_ROOT}"

NPM_LOCKFILE="${RULES_TS_ROOT}/tests/npm/pnpm-lock.yaml"
if [[ ! -f "${NPM_LOCKFILE}" ]]; then
    echo "FAIL: pnpm-lock.yaml not found at ${NPM_LOCKFILE}" >&2
    exit 1
fi

# ── Create writable scratch workspace in /tmp ─────────────────────────────────
SCRATCH_DIR=""
OUTPUT_BASE=""
cleanup() {
    [[ -n "${OUTPUT_BASE}" ]] && { chmod -R u+w "${OUTPUT_BASE}" 2>/dev/null || true; rm -rf "${OUTPUT_BASE}"; }
    [[ -n "${SCRATCH_DIR}" ]] && rm -rf "${SCRATCH_DIR}"
}
trap cleanup EXIT
SCRATCH_DIR="$(mktemp -d -t rules_ts_lsp.XXXXXX)"
OUTPUT_BASE="$(mktemp -d -t rules_ts_lsp_output.XXXXXX)"

cp -rL "${BIT_WORKSPACE_DIR}/." "${SCRATCH_DIR}/"
for f in "${BIT_WORKSPACE_DIR}"/.bazelrc "${BIT_WORKSPACE_DIR}"/.bazelversion; do
    [[ -e "${f}" ]] && cp -L "${f}" "${SCRATCH_DIR}/" || true
done

# ── Copy pnpm-lock.yaml ───────────────────────────────────────────────────────
cp "${NPM_LOCKFILE}" "${SCRATCH_DIR}/pnpm-lock.yaml"

# ── Patch MODULE.bazel ────────────────────────────────────────────────────────
sed -i "s|{RULES_TS_ROOT}|${RULES_TS_ROOT}|g" "${SCRATCH_DIR}/MODULE.bazel"

# ── Helpers ───────────────────────────────────────────────────────────────────
pass() { echo "PASS: $*"; }
fail() { echo "FAIL: $*" >&2; exit 1; }

cd "${SCRATCH_DIR}"

bazel_cmd() {
    env -u TEST_TMPDIR "${BIT_BAZEL_BINARY}" --output_base="${OUTPUT_BASE}" "$@"
}

# ── Step 1: run Gazelle to generate BUILD files ───────────────────────────────
echo "INFO: running gazelle..."
bazel_cmd run //:gazelle || fail "bazel run //:gazelle exited non-zero"
pass "bazel run //:gazelle"

[[ -f "src/models/BUILD.bazel" ]] || fail "Gazelle did not generate src/models/BUILD.bazel"
pass "src/models/BUILD.bazel generated"

[[ -f "src/components/BUILD.bazel" ]] || fail "Gazelle did not generate src/components/BUILD.bazel"
pass "src/components/BUILD.bazel generated"

# ── Step 2: trigger @npm repo rule so BUILD.bazel is generated ───────────────
# refresh_tsconfig reads the @npm BUILD.bazel from the output base.
# The BUILD.bazel is generated by npm_translate_lock when ANY target in @npm
# is resolved.  Querying //... forces resolution of the root workspace deps
# (including @npm references) without building all of @npm//:shared or other
# potentially broken workspace alias targets.
#
# We run `bazel build //...` rather than `bazel build @npm//...` because the
# latter would include the @npm//:shared workspace alias which references a
# packages/shared directory that does not exist in this child workspace.
echo "INFO: building workspace to trigger @npm repo rule..."
bazel_cmd build //... || fail "bazel build //... exited non-zero"
pass "bazel build //..."

# ── Step 3: run refresh_tsconfig ─────────────────────────────────────────────
echo "INFO: running refresh_tsconfig..."
bazel_cmd run //:refresh_tsconfig || fail "bazel run //:refresh_tsconfig exited non-zero"
pass "bazel run //:refresh_tsconfig"

[[ -f "tsconfig.json" ]] || fail "refresh_tsconfig did not generate tsconfig.json"
pass "tsconfig.json generated"

# ── Step 4: assert npm package paths ─────────────────────────────────────────
# The generated tsconfig.json must have a "zod" entry in compilerOptions.paths
# that points at a real .d.ts file.
echo "INFO: checking tsconfig.json for npm paths..."

python3 - "${SCRATCH_DIR}/tsconfig.json" "${OUTPUT_BASE}" << 'PYEOF'
import json
import os
import sys

tsconfig_path = sys.argv[1]
output_base = sys.argv[2]

with open(tsconfig_path) as f:
    tsconfig = json.load(f)

paths = tsconfig.get("compilerOptions", {}).get("paths", {})

# Check that "zod" is present
if "zod" not in paths:
    print("FAIL: 'zod' not found in compilerOptions.paths", file=sys.stderr)
    print(f"  Available paths keys: {sorted(paths.keys())}", file=sys.stderr)
    sys.exit(1)

zod_paths = paths["zod"]
if not zod_paths:
    print("FAIL: 'zod' paths entry is empty", file=sys.stderr)
    sys.exit(1)

zod_path = zod_paths[0]
print(f"INFO: zod path entry = {zod_path!r}")

# The path must point at a .d.ts file (or a directory containing one)
if not zod_path.endswith(".d.ts") and not os.path.isdir(zod_path):
    # Path may be absolute or relative. Accept both as long as the .d.ts exists.
    if not zod_path.endswith(".d.ts"):
        print(f"FAIL: 'zod' path does not end in .d.ts: {zod_path!r}", file=sys.stderr)
        sys.exit(1)

# Resolve: path can be absolute or relative to tsconfig dir
tsconfig_dir = os.path.dirname(tsconfig_path)
if os.path.isabs(zod_path):
    resolved = zod_path
else:
    resolved = os.path.join(tsconfig_dir, zod_path)

resolved = os.path.normpath(resolved)

if not os.path.exists(resolved):
    print(f"FAIL: 'zod' path does not exist on disk: {resolved!r}", file=sys.stderr)
    sys.exit(1)

print(f"PASS: 'zod' in paths → {zod_path!r} (exists)")
sys.exit(0)
PYEOF
pass "tsconfig.json has 'zod' in paths pointing at a real .d.ts file"

# ── Step 5: assert path alias entries ────────────────────────────────────────
# The root BUILD.bazel has: # gazelle:ts_path_alias @/ src/
# The generated tsconfig.json must have "@/*" in compilerOptions.paths
# that maps to "./src/*" (or an array containing "./src/*").
echo "INFO: checking tsconfig.json for path alias..."

python3 - "${SCRATCH_DIR}/tsconfig.json" << 'PYEOF'
import json
import sys

tsconfig_path = sys.argv[1]

with open(tsconfig_path) as f:
    tsconfig = json.load(f)

paths = tsconfig.get("compilerOptions", {}).get("paths", {})

# Check that "@/*" is present
if "@/*" not in paths:
    print("FAIL: '@/*' not found in compilerOptions.paths", file=sys.stderr)
    print(f"  Available paths keys: {sorted(paths.keys())}", file=sys.stderr)
    sys.exit(1)

alias_paths = paths["@/*"]
print(f"INFO: @/* path entries = {alias_paths!r}")

# At least one entry must map to ./src/* (or src/*)
found = any("src/*" in p for p in alias_paths)
if not found:
    print(f"FAIL: '@/*' paths do not contain 'src/*': {alias_paths!r}", file=sys.stderr)
    sys.exit(1)

print(f"PASS: '@/*' in paths → {alias_paths!r}")
sys.exit(0)
PYEOF
pass "tsconfig.json has '@/*' in paths mapping to src/*"

echo "ALL PASSED"
