"""asset_library rule — collects static assets and generates ambient TypeScript declarations.

Static assets (images, SVGs, fonts, text) are imported in TypeScript
applications as URL strings:

    import logo from "./logo.svg";       // → string URL at runtime
    import heroImage from "./hero.png";  // → string URL at runtime

TypeScript rejects these imports by default because it cannot resolve the type
of a non-TypeScript file extension.  When 'allowArbitraryExtensions' is enabled,
TypeScript looks for a <filename>.<ext>.d.ts ambient declaration next to the
source file.

This rule:
  1. Generates an ambient .d.ts for each asset file so TypeScript accepts the
     import without errors.
  2. Propagates asset files via AssetInfo so bundlers can copy/hash them.
  3. Exposes declarations via TsDeclarationInfo so ts_compile includes them.

NOTE: JSON files are NOT handled by asset_library. Use json_library instead,
which parses the JSON at build time and generates a fully-typed .d.ts:

    json_library(
        name = "config",
        srcs = ["config.json"],
    )

A URL string is the default because that is what a bundler hands back when it
does not transform the file. It is not universal: a project running an
svgr-style transform gets a component from '*.svg', and a project that
inlines text gets the file's contents. `declaration_type` is how such a
project says so, per extension.

A wildcard ambient the project writes -- `declare module "*.svg"` -- does NOT
override what this rule generates. TypeScript prefers the concrete
<filename>.<ext>.d.ts beside the asset over any pattern, so the generated
declaration wins and the ambient never applies.
"""

load("//ts/private:providers.bzl", "AssetInfo", "TsDeclarationInfo")

# ── The per-asset declaration ────────────────────────────────────────────────

_DTS_TEMPLATE = """\
// Auto-generated by {label}; the type below came from {source}.
// TypeScript (allowArbitraryExtensions: true) resolves this file beside the
// asset, in preference to any `declare module "*{ext}"` the project writes.
declare const asset: {type};
export default asset;
"""

def _declaration_types(ctx):
    """Validates `declaration_type` and returns it keyed by extension."""
    out = {}
    for ext, type_expr in ctx.attr.declaration_type.items():
        if ext not in _ASSET_EXTENSIONS:
            fail(
                "asset_library {}: declaration_type key {} is not an asset extension.\n".format(
                    ctx.label,
                    repr(ext),
                ) +
                "Write the leading dot, and pick one of: " + ", ".join(_ASSET_EXTENSIONS),
            )
        if not type_expr.strip():
            fail("asset_library {}: declaration_type[{}] is empty.".format(ctx.label, repr(ext)))
        out[ext] = type_expr.strip()
    return out

def _asset_library_impl(ctx):
    asset_files = ctx.files.srcs
    declaration_type = _declaration_types(ctx)

    dts_outputs = []

    # A copy in bazel-bin, not the source file, for the reason css_library
    # copies too: the importer is the compiled .js beside it, so a relative
    # import resolves in the output tree rather than in the source tree.
    bin_asset_files = []
    for asset_file in asset_files:
        # The .d.ts must be named <basename>.d.ts so that TypeScript resolves
        # it when allowArbitraryExtensions is enabled:
        #   logo.svg  →  logo.svg.d.ts
        ext = "." + asset_file.extension
        dts = ctx.actions.declare_file(asset_file.basename + ".d.ts", sibling = asset_file)
        ctx.actions.write(output = dts, content = _DTS_TEMPLATE.format(
            label = ctx.label,
            ext = ext,
            source = (
                "its declaration_type[{}]".format(repr(ext)) if ext in declaration_type else "asset_library's default"
            ),
            type = declaration_type.get(ext, "string"),
        ))
        dts_outputs.append(dts)

        # A generated src is already in bazel-bin, and declaring an output at a
        # path another rule owns is an error rather than a copy.
        if asset_file.is_source:
            bin_asset = ctx.actions.declare_file(asset_file.basename, sibling = asset_file)
            ctx.actions.expand_template(
                template = asset_file,
                output = bin_asset,
                substitutions = {},
            )
            bin_asset_files.append(bin_asset)
        else:
            bin_asset_files.append(asset_file)

    # Build transitive depsets from any asset_library deps.
    transitive_asset_sets = []
    transitive_dts_sets = []
    npm_closure_sets = []
    global_entry_sets = []
    for dep in ctx.attr.deps:
        if AssetInfo in dep:
            transitive_asset_sets.append(dep[AssetInfo].transitive_asset_files)
        if TsDeclarationInfo in dep:
            transitive_dts_sets.append(dep[TsDeclarationInfo].transitive_declaration_files)
            npm_closure_sets.append(dep[TsDeclarationInfo].transitive_npm_packages)
            global_entry_sets.append(dep[TsDeclarationInfo].transitive_global_entry_files)

    direct_assets = depset(bin_asset_files)
    transitive_assets = depset(bin_asset_files, transitive = transitive_asset_sets, order = "postorder")
    direct_dts = depset(dts_outputs)
    transitive_dts = depset(dts_outputs, transitive = transitive_dts_sets, order = "postorder")

    return [
        DefaultInfo(files = depset(bin_asset_files + dts_outputs)),
        AssetInfo(
            asset_files = direct_assets,
            transitive_asset_files = transitive_assets,
        ),
        TsDeclarationInfo(
            declaration_files = direct_dts,
            transitive_declaration_files = transitive_dts,
            transitive_npm_packages = depset(transitive = npm_closure_sets, order = "postorder"),
            global_entry_files = depset(),
            transitive_global_entry_files = depset(transitive = global_entry_sets, order = "postorder"),
        ),
    ]

# Accepted file extensions for asset_library.
# NOTE: .json is intentionally excluded. Use json_library for JSON files so
# that TypeScript callers get a fully-typed declaration instead of `unknown`.
# .jsonc stays here because no bundler parses that extension as JSON: the
# import yields a URL, which is what asset_library declares.
_ASSET_EXTENSIONS = [
    ".svg",
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".webp",
    ".woff",
    ".woff2",
    ".ttf",
    ".eot",
    ".md",
    ".txt",
    ".jsonc",
]

asset_library = rule(
    implementation = _asset_library_impl,
    attrs = {
        "srcs": attr.label_list(
            doc = "Static asset source files: images, SVGs, fonts and text. JSON goes to json_library.",
            allow_files = _ASSET_EXTENSIONS,
            mandatory = True,
        ),
        "deps": attr.label_list(
            doc = "Other asset_library targets this target depends on.",
            providers = [[AssetInfo]],
        ),
        "declaration_type": attr.string_dict(
            doc = """What an import of each extension resolves to, as a TypeScript type expression.

Keyed by extension, leading dot included; an extension left out keeps the
`string` URL default. The value is written into the generated declaration
verbatim, so a name it uses has to resolve from there: use an `import("pkg")`
type query rather than a top-level import, and keep the package in the
*consuming* ts_compile target's deps.

    asset_library(
        name = "icons",
        srcs = ["logo.svg"],
        declaration_type = {
            ".svg": 'import("react").FC<import("react").SVGProps<SVGSVGElement>>',
        },
    )

Set this when a bundler plugin transforms the extension into something other
than a URL -- svgr turning `.svg` into a component is the usual case. A
`declare module "*.svg"` in the project does not do it: TypeScript prefers the
concrete declaration this rule writes beside the asset over any pattern.

A key that is not an asset extension fails the build. The type expression is
unchecked, and a name that does not resolve does not error either: the
declaration is a .d.ts and this ruleset compiles with `skipLibCheck`, so the
import silently widens to `any`. To surface it, build with
`--//ts:lib_check`, or the consuming target alone with
`compiler_options = {"skipLibCheck": False}` -- the error then names the
generated `<asset>.d.ts`, whose header names this target and this attribute.""",
        ),
    },
    doc = """Collects static asset files and generates ambient TypeScript declarations.

An asset_library target provides AssetInfo and TsDeclarationInfo (with
generated ambient .d.ts declarations) so that:

  1. TypeScript (allowArbitraryExtensions: true) does not error when a .tsx
     or .ts file imports an asset file like './logo.svg'.
  2. ts_compile targets can declare an asset dependency without failing.
  3. The asset files are copied untransformed into bazel-bin beside the
     compiled .js that imports them, which is what lets a bundler resolve the
     relative import and then copy, hash and reference the asset.

Supported file types:
  Images:  .svg, .png, .jpg, .jpeg, .gif, .webp
  Fonts:   .woff, .woff2, .ttf, .eot
  Text:    .md, .txt, .jsonc

NOTE: JSON files are handled by json_library (not asset_library). json_library
generates a fully-typed .d.ts by parsing the JSON structure at build time.

Generated declarations:
  By default every extension → declare const asset: string; export default asset;
  `declaration_type` replaces that type per extension.

Example:
    asset_library(
        name = "icons",
        srcs = ["logo.svg", "close.svg"],
    )

    ts_compile(
        name = "header",
        srcs = ["Header.tsx"],
        deps = [":icons"],
    )
""",
)
