load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

package(default_visibility = [
    "//npm:__subpackages__",
    "//ts:__subpackages__",
    "//vite:__subpackages__",
])

exports_files([
    "node_test_hook.mjs",
    "vitest_workers_pool.mjs",
    "wrangler_test_config.mjs",
])

bzl_library(
    name = "providers",
    srcs = ["providers.bzl"],
)

bzl_library(
    name = "asset_library",
    srcs = ["asset_library.bzl"],
    deps = [
        ":providers",
    ],
)

bzl_library(
    name = "css_library",
    srcs = ["css_library.bzl"],
    deps = [
        ":providers",
    ],
)

bzl_library(
    name = "css_module",
    srcs = ["css_module.bzl"],
    deps = [
        ":providers",
        ":runtime",
    ],
)

bzl_library(
    name = "json_library",
    srcs = ["json_library.bzl"],
    deps = [
        ":providers",
        ":runtime",
    ],
)

bzl_library(
    name = "pnpm",
    srcs = ["pnpm.bzl"],
    deps = [
        "@rules_shell//shell:rules_bzl",
    ],
)

bzl_library(
    name = "ts_codegen",
    srcs = ["ts_codegen.bzl"],
    deps = [
        ":runtime",
    ],
)

bzl_library(
    name = "ts_compile",
    srcs = ["ts_compile.bzl"],
    deps = [
        ":providers",
        ":toolchain",
    ],
)

bzl_library(
    name = "ts_config",
    srcs = ["ts_config.bzl"],
    deps = [
        ":providers",
    ],
)

bzl_library(
    name = "ts_test",
    srcs = ["ts_test.bzl"],
    deps = [
        ":node_modules",
        ":providers",
        ":runtime",
        ":ts_compile",
    ],
)

bzl_library(
    name = "bundle_action",
    srcs = ["bundle_action.bzl"],
    deps = [
        ":providers",
    ],
)

bzl_library(
    name = "ts_binary",
    srcs = ["ts_binary.bzl"],
    deps = [
        ":bundle_action",
        ":providers",
        ":runtime",
    ],
)

bzl_library(
    name = "ts_dev_server",
    srcs = ["ts_dev_server.bzl"],
    deps = [
        ":providers",
        ":runtime",
    ],
)

bzl_library(
    name = "ts_npm_package",
    srcs = ["ts_npm_package.bzl"],
    deps = [
        ":providers",
    ],
)

bzl_library(
    name = "node_modules",
    srcs = ["node_modules.bzl"],
    deps = [
        ":providers",
        ":runtime",
    ],
)

bzl_library(
    name = "toolchain",
    srcs = ["toolchain.bzl"],
    deps = [
        "//npm/private:npmrc_auth",
        "//platforms",
    ],
)

bzl_library(
    name = "tsgo_lock",
    srcs = ["tsgo_lock.bzl"],
    deps = [
        "//npm/private:npm_translate_lock",
        "//platforms",
    ],
)

bzl_library(
    name = "runtime",
    srcs = ["runtime.bzl"],
    deps = [
        "//platforms",
    ],
)

bzl_library(
    name = "ts_lint",
    srcs = ["ts_lint.bzl"],
    deps = [
        ":providers",
    ],
)

bzl_library(
    name = "tsconfig_aspect",
    srcs = ["tsconfig_aspect.bzl"],
    deps = [
        ":providers",
        "@bazel_skylib//rules:diff_test",
    ],
)
