"""The bundle action behind ts_binary's optional `bundler` attr.

A target providing BundlerInfo is run over the entry point's transitive .js
graph in whichever of the provider's two modes it declares:

Standard CLI (BundlerInfo.use_generated_config = False):
  <bundler_binary>
    --entry  <path/to/entry.js>
    --out-dir <output/dir>
    --format esm|cjs|iife
    [--external <pkg>]...
    [--sourcemap]
    [--config <config_file>]

Generated config (BundlerInfo.use_generated_config = True):
  <bundler_binary> <vite.config.mjs> <entry.js> <out_dir> <bundle.css>
  All four exec-root-relative. The config is a Vite lib-mode build that reads
  the entry and outDir back from VITE_ENTRY_PATH and VITE_OUT_DIR and rebuilds
  every path from EXEC_ROOT, so the binary sets those three before running
  Vite. A .css, a .module.css and an asset reach the bundler the same way the
  .js does -- through the entry point's CssInfo, CssModuleInfo and AssetInfo.
  Outputs follow Vite's lib-mode names:
    <bundle_name>.es.js     (for format=esm)
    <bundle_name>.cjs.js    (for format=cjs)
    <bundle_name>.iife.js   (for format=iife)
    <bundle_name>.es.js.map (if sourcemap=True)
    <bundle_name>.css       (always declared; the binary creates it up front)
"""

load("//ts/private:providers.bzl", "AssetInfo", "BundlerInfo", "CssInfo", "CssModuleInfo")

_VITE_FORMAT_SUFFIX = {
    "esm": "es",
    "cjs": "cjs",
    "iife": "iife",
}

def _js_string(s):
    return s.replace("\\", "\\\\").replace("\n", "\\n").replace("\r", "\\r").replace('"', '\\"')

def _generate_vite_config(ctx, bundle_filename, transitive_js_files, css_module_plugin):
    """The vite.config.mjs for a lib-mode build of the entry point.

    Args:
        ctx: The rule context, carrying format, sourcemap, external and define.
        bundle_filename: The bundle output filename stem (without extension).
        transitive_js_files: Depset of every compiled .js, each of which becomes
            a resolve.alias entry so Vite finds the bazel-bin output an import
            names.
        css_module_plugin: The bundled File exporting cssModulesPlugin, which
            makes the class names in the bundle the ones the css_module .d.ts
            declares.

    Returns:
        The config file's content.
    """
    vite_format = _VITE_FORMAT_SUFFIX.get(ctx.attr.format, "es")

    externals_js = "[" + ", ".join([
        '"{}"'.format(e.replace('"', '\\"'))
        for e in ctx.attr.external
    ]) + "]"

    define_entries = [
        '  "{}": {}'.format(k.replace('"', '\\"'), v)
        for k, v in ctx.attr.define.items()
    ]
    define_js = "{\n" + ",\n".join(define_entries) + "\n}" if define_entries else "{}"

    sourcemap_js = "true" if ctx.attr.sourcemap else "false"

    # Vite derives the extension from the nearest package.json "type", which no
    # directory in the output tree declares, so the name is forced.
    filename_fn = '() => "' + bundle_filename + "." + vite_format + '.js"'

    # Keyed by both the exec-root path and the short path, minus .js: an importer
    # in bazel-bin spells its neighbour either way.
    alias_entries = []
    seen_alias_keys = {}
    for js_file in transitive_js_files.to_list():
        path_no_ext = js_file.path[:-3] if js_file.path.endswith(".js") else js_file.path
        short_no_ext = js_file.short_path[:-3] if js_file.short_path.endswith(".js") else js_file.short_path
        abs_target = '" + process.env["EXEC_ROOT"] + "/' + _js_string(js_file.path) + '"'
        for key in [path_no_ext, short_no_ext]:
            if key not in seen_alias_keys:
                seen_alias_keys[key] = True
                alias_entries.append('    "{}": "'.format(_js_string(key)) + abs_target + ",")
    alias_js = "{\n" + "\n".join(alias_entries) + "\n  }" if alias_entries else "{}"

    # Absolute via EXEC_ROOT: the ruleset is wherever the sandbox put it, not
    # beside this config.
    css_module_plugin_import = (
        "const { cssModulesPlugin } = await import(\n" +
        "  process.env[\"EXEC_ROOT\"] + \"/\" + \"" +
        css_module_plugin.path.replace('"', '\\"') + "\",\n" +
        ");\n"
    )

    return (
        "// Generated by rules_typescript ts_binary for " + str(ctx.label) + "\n" +
        "// DO NOT EDIT — regenerated on every build.\n" +
        "import { defineConfig } from \"vite\";\n" +
        "\n" +
        "const entryPath = process.env[\"VITE_ENTRY_PATH\"];\n" +
        "const outDir = process.env[\"VITE_OUT_DIR\"];\n" +
        "\n" +
        "if (!entryPath) throw new Error(\"VITE_ENTRY_PATH env var not set\");\n" +
        "if (!outDir) throw new Error(\"VITE_OUT_DIR env var not set\");\n" +
        "\n" +
        css_module_plugin_import +
        "\n" +
        "export default defineConfig({\n" +
        "  plugins: [cssModulesPlugin()],\n" +
        "  build: {\n" +
        "    lib: {\n" +
        "      entry: entryPath,\n" +
        '      name: "' + bundle_filename + '",\n' +
        '      formats: ["' + vite_format + '"],\n' +
        "      fileName: " + filename_fn + ",\n" +
        # Lib mode derives the CSS filename from package.json's name, and the
        # output tree has no package.json.
        '      cssFileName: "' + bundle_filename + '",\n' +
        "    },\n" +
        "    outDir: outDir,\n" +
        "    sourcemap: " + sourcemap_js + ",\n" +
        "    minify: true,\n" +
        "    emptyOutDir: false,\n" +
        "    rollupOptions: {\n" +
        "      external: " + externals_js + ",\n" +
        "    },\n" +
        "  },\n" +
        "  resolve: {\n" +
        "    alias: " + alias_js + ",\n" +
        "  },\n" +
        "  define: " + define_js + ",\n" +
        "  logLevel: \"warn\",\n" +
        "});\n"
    )

BUNDLE_ACTION_ATTRS = {
    "_css_module_plugin": attr.label(
        default = Label("//ts/private/css:css_module_vite_plugin"),
        allow_single_file = True,
    ),
}

def create_bundle_action(ctx, entry_js_info, bundle_filename):
    """Runs ctx.attr.bundler over the entry point's .js graph.

    Args:
        ctx: The rule context. Carries BUNDLE_ACTION_ATTRS plus entry_point,
             bundler, format, sourcemap, external and define.
        entry_js_info: JsInfo from the entry_point target.
        bundle_filename: Filename stem (without .js extension) for the bundle.

    Returns:
        struct(bundle_out = File, outputs = list of File): the bundle and every
        declared output beside it.
    """
    all_js = entry_js_info.transitive_js_files
    all_js_maps = entry_js_info.transitive_js_map_files

    # Every non-JS file the entry graph imports has to be in the sandbox, or
    # Vite resolves a relative import onto a bazel-bin path holding nothing.
    entry_point_target = ctx.attr.entry_point
    non_js_inputs = []
    if CssInfo in entry_point_target:
        non_js_inputs.append(entry_point_target[CssInfo].transitive_css_files)
    if CssModuleInfo in entry_point_target:
        non_js_inputs.append(entry_point_target[CssModuleInfo].transitive_css_files)

        # The plugin reads the scoped names out of these rather than deriving
        # them a second time, so they are inputs wherever the stylesheets are.
        non_js_inputs.append(entry_point_target[CssModuleInfo].transitive_exports_files)
    if AssetInfo in entry_point_target:
        non_js_inputs.append(entry_point_target[AssetInfo].transitive_asset_files)

    bundler_info = ctx.attr.bundler[BundlerInfo]

    entry_js_files = entry_js_info.js_files.to_list()
    if not entry_js_files:
        fail(
            "ts_binary: entry_point '{ep}' provides JsInfo but has no direct .js outputs.\n".format(ep = ctx.attr.entry_point.label) +
            "Ensure the ts_compile target at entry_point has at least one .ts source file in srcs.",
        )
    if len(entry_js_files) != 1:
        fail(
            "ts_binary: with a bundler, entry_point '{ep}' must produce exactly 1 .js file (the entry), but it produces {n}.\n".format(
                ep = ctx.attr.entry_point.label,
                n = len(entry_js_files),
            ) +
            "Use a ts_compile target with a single source file as the entry point, " +
            "e.g. srcs = [\"index.ts\"].",
        )
    entry_js_file = entry_js_files[0]

    out_dir_rel = "{}_bundle".format(ctx.label.name)

    if getattr(bundler_info, "use_generated_config", False):
        vite_js_name = "{}.{}.js".format(bundle_filename, _VITE_FORMAT_SUFFIX.get(ctx.attr.format, "es"))
        bundle_out = ctx.actions.declare_file("{}/{}".format(out_dir_rel, vite_js_name))
        outputs = [bundle_out]
        if ctx.attr.sourcemap:
            outputs.append(ctx.actions.declare_file("{}/{}.map".format(out_dir_rel, vite_js_name)))

        # Lib mode extracts CSS into one stylesheet the .js never references, so
        # only declaring it keeps it: an undeclared output goes out with the
        # sandbox. Unconditional, since gating it on a CSS dep would materialise
        # the transitive depset; the binary creates the file up front.
        css_out = ctx.actions.declare_file("{}/{}.css".format(out_dir_rel, bundle_filename))
        outputs.append(css_out)

        config_file = ctx.actions.declare_file("{}/vite.config.mjs".format(out_dir_rel))
        ctx.actions.write(
            output = config_file,
            content = _generate_vite_config(ctx, bundle_filename, all_js, ctx.file._css_module_plugin),
        )

        ctx.actions.run(
            inputs = depset(
                [entry_js_file, config_file, ctx.file._css_module_plugin],
                transitive = [all_js, all_js_maps, bundler_info.runtime_deps] + non_js_inputs,
            ),
            outputs = outputs,
            executable = bundler_info.bundler_binary,
            arguments = [config_file.path, entry_js_file.path, bundle_out.dirname, css_out.path],
            mnemonic = "TsBundleVite",
            progress_message = "TsBundleVite %{label}",
        )
    else:
        bundle_out = ctx.actions.declare_file("{}/{}.js".format(out_dir_rel, bundle_filename))

        args = ctx.actions.args()
        args.add("--entry", entry_js_file)
        args.add("--out-dir", bundle_out.dirname)
        args.add("--format", ctx.attr.format)
        for ext in ctx.attr.external:
            args.add("--external", ext)
        if ctx.attr.sourcemap:
            args.add("--sourcemap")
        for k, v in ctx.attr.define.items():
            args.add("--define", "{}={}".format(k, v))
        if bundler_info.config_file:
            args.add("--config", bundler_info.config_file)

        outputs = [bundle_out]
        if ctx.attr.sourcemap:
            outputs.append(ctx.actions.declare_file("{}/{}.js.map".format(out_dir_rel, bundle_filename)))

        ctx.actions.run(
            inputs = depset(
                [entry_js_file],
                transitive = [all_js, all_js_maps, bundler_info.runtime_deps] + non_js_inputs +
                             ([depset([bundler_info.config_file])] if bundler_info.config_file else []),
            ),
            outputs = outputs,
            executable = bundler_info.bundler_binary,
            arguments = [args],
            mnemonic = "TsBundle",
            progress_message = "TsBundle %{label}",
        )

    return struct(bundle_out = bundle_out, outputs = outputs)
