"""json_library rule — reads a JSON file at build time and generates a typed .d.ts.

The file is read as JSONC -- comments and trailing commas -- through the same
//gazelle/jsonc stripper Gazelle decodes tsconfig.json with, so the rule and the
BUILD generator cannot disagree about what a file says.

Unlike asset_library which emits `declare const data: unknown`, json_library
parses the JSON structure and generates a fully-typed declaration so that
TypeScript callers get type-safe access to each property.

Example JSON:

    { "name": "Alice", "age": 30, "active": true }

Generated .d.ts:

    declare const data: {
      readonly name: string;
      readonly age: number;
      readonly active: boolean;
    };
    export default data;

The typed declaration is generated by a small Node.js script that runs
at build time. Node.js is always available for json_library targets because
the rule requires the js_tool toolchain (Node on the exec platform).

JSON → TypeScript type mapping:
  string  → string
  number  → number
  boolean → boolean
  null    → null
  array   → readonly <element_type>[]  (element type from first item, or unknown)
  object  → { readonly key: type; ... }

Supported import syntax (requires allowArbitraryExtensions in tsconfig):

    import config from "./config.json";
    console.log(config.name);  // TypeScript knows this is a string
"""

load("//ts/private:providers.bzl", "TsDeclarationInfo")
load("//ts/private:runtime.bzl", "JS_TOOL_TOOLCHAIN_TYPE", "get_js_tool")

# ── Node.js script that reads JSON and emits a typed .d.ts ────────────────────
#
# The script is written inline so json_library has no dependency on a separate
# script file in the repo. It is written to a declared file, then executed.
#
# The type generator:
#   - Maps JSON scalar types to TypeScript primitives.
#   - Recursively maps object keys to their field types with `readonly`.
#   - Maps arrays to `readonly <elem>[]`, inferring element type from the
#     first element (or `unknown` for empty arrays).
#   - Uses JSON.stringify for the full nested type shape, not just top-level.

_JSON_TO_DTS_SCRIPT = """\
// Auto-generated by rules_typescript json_library.
// Reads a JSON file and emits a typed TypeScript .d.ts declaration.
import { readFileSync, writeFileSync } from 'node:fs';

const jsonFile = process.argv[2];
const dtsFile  = process.argv[3];

const sourceName = process.argv[4] ?? jsonFile;

let data;
try {
  data = JSON.parse(readFileSync(jsonFile, 'utf8'));
} catch (e) {
  process.stderr.write('json_library: failed to parse ' + sourceName + ': ' + e.message + '\\n');
  process.exit(1);
}

// The declaration has to mean what `resolveJsonModule` means for the same
// file, or a target that switches between them changes type. Two rules carry
// most of that: an array's element type is the union of its elements, not the
// first one; and nothing is `readonly`, because a JSON module is not.
function model(v) {
  if (v === null) return { k: 's', name: 'null' };
  const t = typeof v;
  if (t === 'string' || t === 'number' || t === 'boolean') return { k: 's', name: t };
  if (Array.isArray(v)) return { k: 'a', elems: v.map(model) };
  if (t === 'object') {
    return {
      k: 'o',
      fields: Object.keys(v).map((key) => ({ key, type: model(v[key]), optional: false })),
    };
  }
  return { k: 's', name: 'unknown' };
}

// TypeScript normalises a union of object literals by giving every member the
// union's whole key set, filling an absent key with `?: undefined`. That is
// what makes `xs[1].b` read as `number | undefined` rather than an error, and
// it is why sampling the first element erased keys the later ones carried.
function normalise(models) {
  const objs = models.filter((m) => m.k === 'o');
  if (objs.length < 2) return;
  const order = [];
  for (const o of objs) {
    for (const f of o.fields) if (!order.includes(f.key)) order.push(f.key);
  }
  for (const o of objs) {
    const have = new Map(o.fields.map((f) => [f.key, f]));
    o.fields = order.map(
      (key) => have.get(key) ?? { key, type: { k: 's', name: 'undefined' }, optional: true },
    );
  }
  for (const key of order) {
    normalise(
      objs
        .map((o) => o.fields.find((f) => f.key === key))
        .filter((f) => f && !f.optional)
        .map((f) => f.type),
    );
  }
}

function render(m, indent) {
  if (m.k === 's') return m.name;
  if (m.k === 'a') return renderUnion(m.elems, indent, true) + '[]';
  if (m.fields.length === 0) return '{}';
  const next = indent + '  ';
  const fields = m.fields.map(
    (f) => next + JSON.stringify(f.key) + (f.optional ? '?' : '') + ': ' + render(f.type, next) + ';',
  );
  return '{\\n' + fields.join('\\n') + '\\n' + indent + '}';
}

function renderUnion(models, indent, parenthesise) {
  if (models.length === 0) return 'never';
  normalise(models);
  const seen = [];
  for (const m of models) {
    const text = render(m, indent);
    if (!seen.includes(text)) seen.push(text);
  }
  const nullish = seen.filter((t) => t === 'null' || t === 'undefined');
  const parts = seen.filter((t) => t !== 'null' && t !== 'undefined').concat(nullish);
  if (parts.length === 1) return parts[0];
  const joined = parts.join(' | ');
  return parenthesise ? '(' + joined + ')' : joined;
}

const type = render(model(data), '');
const dts = 'declare const data: ' + type + ';\\nexport default data;\\n';
writeFileSync(dtsFile, dts, 'utf8');
"""

def _json_library_impl(ctx):
    json_files = ctx.files.srcs

    js_tool = get_js_tool(ctx)

    # Write the generator script once per target (shared across all .json srcs).
    generator_script = ctx.actions.declare_file(
        "_json_dts_gen_{}.mjs".format(ctx.label.name),
    )
    ctx.actions.write(output = generator_script, content = _JSON_TO_DTS_SCRIPT)

    dts_outputs = []
    for json_file in json_files:
        # TypeScript accepts comments and trailing commas wherever it reads
        # JSON, so the rule reads the same dialect Gazelle does rather than a
        # stricter one.
        plain = ctx.actions.declare_file(
            json_file.basename + ".plain.json",
            sibling = json_file,
        )
        ctx.actions.run(
            inputs = [json_file],
            outputs = [plain],
            executable = ctx.executable._jsonc_strip,
            arguments = [json_file.path, plain.path],
            mnemonic = "JsonLibraryStrip",
            progress_message = "JsonLibraryStrip %{label}",
        )

        # The .d.ts must be named <basename>.d.ts so TypeScript resolves it
        # when allowArbitraryExtensions is enabled:
        #   config.json  →  config.json.d.ts
        dts = ctx.actions.declare_file(json_file.basename + ".d.ts", sibling = json_file)

        ctx.actions.run(
            inputs = [plain, generator_script],
            outputs = [dts],
            executable = js_tool.runtime_binary,
            arguments = js_tool.args_prefix + [
                generator_script.path,
                plain.path,
                dts.path,
                json_file.short_path,
            ],
            mnemonic = "JsonLibraryDts",
            progress_message = "JsonLibraryDts %{label}",
        )
        dts_outputs.append(dts)

    # Build transitive depsets from any json_library deps.
    transitive_dts_sets = []
    global_entry_sets = []
    for dep in ctx.attr.deps:
        if TsDeclarationInfo in dep:
            transitive_dts_sets.append(dep[TsDeclarationInfo].transitive_declaration_files)
            global_entry_sets.append(dep[TsDeclarationInfo].transitive_global_entry_files)

    direct_dts = depset(dts_outputs)
    transitive_dts = depset(dts_outputs, transitive = transitive_dts_sets, order = "postorder")

    return [
        DefaultInfo(files = depset(json_files + dts_outputs)),
        TsDeclarationInfo(
            declaration_files = direct_dts,
            transitive_declaration_files = transitive_dts,
            global_entry_files = depset(),
            transitive_global_entry_files = depset(transitive = global_entry_sets, order = "postorder"),
        ),
    ]

json_library = rule(
    implementation = _json_library_impl,
    attrs = {
        "srcs": attr.label_list(
            doc = "JSON source files.",
            allow_files = [".json"],
            mandatory = True,
        ),
        "deps": attr.label_list(
            doc = "Other json_library targets this target depends on.",
            providers = [[TsDeclarationInfo]],
        ),
        "_jsonc_strip": attr.label(
            default = Label("//gazelle/jsonc/strip"),
            executable = True,
            cfg = "exec",
        ),
    },
    toolchains = [
        config_common.toolchain_type(JS_TOOL_TOOLCHAIN_TYPE, mandatory = True),
    ],
    doc = """Reads JSON files at build time and generates typed TypeScript declarations.

Unlike asset_library (which emits `declare const data: unknown`), json_library
parses the JSON structure and generates a fully-typed .d.ts so that TypeScript
callers have type-safe access to every property.

Requires the js_tool toolchain (Node.js on the exec platform) to be registered.

Example:

    json_library(
        name = "config",
        srcs = ["config.json"],
    )

    ts_compile(
        name = "app",
        srcs = ["app.ts"],
        deps = [":config"],
    )

In app.ts:

    import config from "./config.json";
    console.log(config.name);  // typed as string (or whatever the JSON has)

The generated .d.ts varies by JSON content:

    // config.json: { "host": "localhost", "port": 8080 }
    declare const data: {
      readonly "host": string;
      readonly "port": number;
    };
    export default data;

JSON → TypeScript type mapping:
  string  → string
  number  → number
  boolean → boolean
  null    → null
  array   → readonly <element_type>[]
  object  → { readonly key: type; ... }
""",
)
