"""json_library rule — reads a JSON file at build time and generates a typed .d.ts.

Unlike asset_library which emits `declare const data: unknown`, json_library
parses the JSON structure and generates a fully-typed declaration so that
TypeScript callers get type-safe access to each property.

Example JSON:

    { "name": "Alice", "age": 30, "active": true }

Generated .d.ts:

    declare const data: {
      readonly name: string;
      readonly age: number;
      readonly active: boolean;
    };
    export default data;

The typed declaration is generated by a small Node.js script that runs
at build time. Node.js is always available for json_library targets because
the rule uses the js_runtime toolchain.

JSON → TypeScript type mapping:
  string  → string
  number  → number
  boolean → boolean
  null    → null
  array   → readonly <element_type>[]  (element type from first item, or unknown)
  object  → { readonly key: type; ... }

Supported import syntax (requires allowArbitraryExtensions in tsconfig):

    import config from "./config.json";
    console.log(config.name);  // TypeScript knows this is a string
"""

load("//ts/private:providers.bzl", "TsDeclarationInfo")
load("//ts/private:runtime.bzl", "JS_RUNTIME_TOOLCHAIN_TYPE", "get_js_runtime")

# ── Node.js script that reads JSON and emits a typed .d.ts ────────────────────
#
# The script is written inline so json_library has no dependency on a separate
# script file in the repo. It is written to a declared file, then executed.
#
# The type generator:
#   - Maps JSON scalar types to TypeScript primitives.
#   - Recursively maps object keys to their field types with `readonly`.
#   - Maps arrays to `readonly <elem>[]`, inferring element type from the
#     first element (or `unknown` for empty arrays).
#   - Uses JSON.stringify for the full nested type shape, not just top-level.

_JSON_TO_DTS_SCRIPT = """\
// Auto-generated by rules_typescript json_library.
// Reads a JSON file and emits a typed TypeScript .d.ts declaration.
import { readFileSync, writeFileSync } from 'node:fs';

const jsonFile = process.argv[2];
const dtsFile  = process.argv[3];

let data;
try {
  data = JSON.parse(readFileSync(jsonFile, 'utf8'));
} catch (e) {
  process.stderr.write('json_library: failed to parse ' + jsonFile + ': ' + e.message + '\\n');
  process.exit(1);
}

function typeOf(v, indent) {
  if (v === null) return 'null';
  const t = typeof v;
  if (t === 'string' || t === 'number' || t === 'boolean') return t;
  if (Array.isArray(v)) {
    const elemType = v.length > 0 ? typeOf(v[0], indent + '  ') : 'unknown';
    return 'readonly ' + elemType + '[]';
  }
  if (t === 'object') {
    const keys = Object.keys(v);
    if (keys.length === 0) return 'Record<string, unknown>';
    const nextIndent = indent + '  ';
    const fields = keys.map((k) =>
      nextIndent + 'readonly ' + JSON.stringify(k) + ': ' + typeOf(v[k], nextIndent) + ';'
    );
    return '{\\n' + fields.join('\\n') + '\\n' + indent + '}';
  }
  return 'unknown';
}

const type = typeOf(data, '');
const dts = 'declare const data: ' + type + ';\\nexport default data;\\n';
writeFileSync(dtsFile, dts, 'utf8');
"""

def _json_library_impl(ctx):
    json_files = ctx.files.srcs

    # Resolve the JS runtime to run the type-generation script.
    runtime_info = get_js_runtime(ctx)
    if not runtime_info:
        fail(
            "json_library requires a JS runtime toolchain. " +
            "Register a Node.js toolchain in MODULE.bazel:\n" +
            "    register_toolchains(\n" +
            "        \"@rules_typescript//ts/toolchain:node_linux_amd64\",\n" +
            "        ...\n" +
            "    )\n",
        )

    # Write the generator script once per target (shared across all .json srcs).
    generator_script = ctx.actions.declare_file(
        "_json_dts_gen_{}.mjs".format(ctx.label.name),
    )
    ctx.actions.write(output = generator_script, content = _JSON_TO_DTS_SCRIPT)

    dts_outputs = []
    for json_file in json_files:
        # The .d.ts must be named <basename>.d.ts so TypeScript resolves it
        # when allowArbitraryExtensions is enabled:
        #   config.json  →  config.json.d.ts
        dts = ctx.actions.declare_file(json_file.basename + ".d.ts", sibling = json_file)

        ctx.actions.run(
            inputs = [json_file, generator_script],
            outputs = [dts],
            executable = runtime_info.runtime_binary,
            arguments = runtime_info.args_prefix + [
                generator_script.path,
                json_file.path,
                dts.path,
            ],
            mnemonic = "JsonLibraryDts",
            progress_message = "JsonLibraryDts %{label}",
        )
        dts_outputs.append(dts)

    # Build transitive depsets from any json_library deps.
    transitive_dts_sets = []
    for dep in ctx.attr.deps:
        if TsDeclarationInfo in dep:
            transitive_dts_sets.append(dep[TsDeclarationInfo].transitive_declaration_files)

    direct_dts = depset(dts_outputs)
    transitive_dts = depset(dts_outputs, transitive = transitive_dts_sets, order = "postorder")

    return [
        DefaultInfo(files = depset(json_files + dts_outputs)),
        TsDeclarationInfo(
            declaration_files = direct_dts,
            transitive_declaration_files = transitive_dts,
            type_roots = depset([]),
        ),
    ]

json_library = rule(
    implementation = _json_library_impl,
    attrs = {
        "srcs": attr.label_list(
            doc = "JSON source files.",
            allow_files = [".json"],
            mandatory = True,
        ),
        "deps": attr.label_list(
            doc = "Other json_library targets this target depends on.",
            providers = [[TsDeclarationInfo]],
        ),
    },
    toolchains = [
        config_common.toolchain_type(JS_RUNTIME_TOOLCHAIN_TYPE, mandatory = True),
    ],
    doc = """Reads JSON files at build time and generates typed TypeScript declarations.

Unlike asset_library (which emits `declare const data: unknown`), json_library
parses the JSON structure and generates a fully-typed .d.ts so that TypeScript
callers have type-safe access to every property.

Requires a JS runtime toolchain (Node.js) to be registered.

Example:

    json_library(
        name = "config",
        srcs = ["config.json"],
    )

    ts_compile(
        name = "app",
        srcs = ["app.ts"],
        deps = [":config"],
    )

In app.ts:

    import config from "./config.json";
    console.log(config.name);  // typed as string (or whatever the JSON has)

The generated .d.ts varies by JSON content:

    // config.json: { "host": "localhost", "port": 8080 }
    declare const data: {
      readonly "host": string;
      readonly "port": number;
    };
    export default data;

JSON → TypeScript type mapping:
  string  → string
  number  → number
  boolean → boolean
  null    → null
  array   → readonly <element_type>[]
  object  → { readonly key: type; ... }
""",
)
