"""Rule for executable npm bin script targets.

npm_bin wraps a bin script from an npm package as a Bazel executable target.
It resolves Node.js from the js_runtime toolchain (or falls back to system node)
and invokes the specified script entry point with any provided arguments.

Generated by npm_translate_lock for each entry in a package's "bin" field.

Usage (generated by npm_translate_lock):
    npm_bin(
        name = "vitest_bin",
        package = ":vitest",
        entry_script = "vitest.mjs",
        package_dir = "vitest__3_0_9",
    )

Users can then:
    bazel run @npm//:vitest_bin -- --version
"""

load("//ts/private:providers.bzl", "NpmPackageInfo")
load("//ts/private:runtime.bzl", "JS_RUNTIME_TOOLCHAIN_TYPE", "get_js_runtime")

def _shell_escape(s):
    """Escapes a string for safe embedding in a double-quoted shell string."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("`", "\\`")

def _npm_bin_impl(ctx):
    # Resolve the JS runtime from the toolchain or fall back to system node.
    runtime_binary = None
    runtime_args = []
    if ctx.file.runtime:
        runtime_binary = ctx.file.runtime
    else:
        js_runtime = get_js_runtime(ctx)
        if js_runtime:
            runtime_binary = js_runtime.runtime_binary
            runtime_args = js_runtime.args_prefix

    # Helper: convert a file's short_path to its runfiles-tree-relative path.
    # Bazel runfiles layout with --nolegacy_external_runfiles (bzlmod default):
    #   $RUNFILES_DIR/_main/<short_path>          for main-workspace files
    #   $RUNFILES_DIR/<repo_name>/<path>          for external-repo files
    # File.short_path encoding:
    #   main-workspace:   "path/to/file"   (no prefix)
    #   external-repo:    "../repo_name/path"  (leading "../")
    def _rl(short_path):
        if short_path.startswith("../"):
            return short_path[3:]  # strip leading "../"
        return "_main/" + short_path

    # Locate the entry script from the package files.
    # The package_dir attribute holds the package.json file; the entry script
    # is a sibling file (relative to the package root).
    entry_script_file = None
    entry_script = ctx.attr.entry_script
    for f in ctx.files.package_files:
        # Match the file whose path ends with the entry_script (relative path within package).
        # package_dir.path example: external/+npm+npm/vitest__3_0_9/package.json
        # entry file path example:  external/+npm+npm/vitest__3_0_9/vitest.mjs
        if f.basename == entry_script or f.path.endswith("/" + entry_script):
            entry_script_file = f
            break

    if not entry_script_file:
        available = [f.basename for f in ctx.files.package_files]
        fail(
            "npm_bin: entry script '{}' not found in package files for target '{}'.\n".format(
                entry_script,
                ctx.label,
            ) +
            "This usually means the npm package's 'bin' field references a file that " +
            "was not included in package_files, or the entry_script path is wrong.\n" +
            "Available files: {}".format(", ".join(available[:20]) + (" ..." if len(available) > 20 else "")),
        )

    runtime_path = _rl(runtime_binary.short_path) if runtime_binary else ""
    entry_path = _rl(entry_script_file.short_path)
    runtime_args_str = " ".join(["\"{}\"".format(_shell_escape(a)) for a in runtime_args])

    runner = ctx.actions.declare_file("{}_bin_runner.sh".format(ctx.label.name))
    runner_content = (
        "#!/usr/bin/env bash\n" +
        "# Bazel-generated npm bin runner for " + str(ctx.label) + "\n" +
        "set -euo pipefail\n" +
        "\n" +
        "# Resolve the runfiles root.\n" +
        "# Bazel sets RUNFILES_DIR for both 'bazel run' and 'bazel test'.\n" +
        "# TEST_SRCDIR is the legacy name used in tests.\n" +
        "if [[ -n \"${RUNFILES_DIR:-}\" ]]; then\n" +
        "  : # RUNFILES_DIR already set by Bazel\n" +
        "elif [[ -n \"${TEST_SRCDIR:-}\" ]]; then\n" +
        "  RUNFILES_DIR=\"$TEST_SRCDIR\"\n" +
        "else\n" +
        "  # Determine runfiles dir from the script's location.\n" +
        "  # Bazel places the .runfiles dir alongside the script binary.\n" +
        "  SCRIPT_PATH=\"${BASH_SOURCE[0]}\"\n" +
        "  # Resolve symlinks to find the real script location.\n" +
        "  while [[ -L \"$SCRIPT_PATH\" ]]; do\n" +
        "    SCRIPT_PATH=\"$(readlink \"$SCRIPT_PATH\")\"\n" +
        "  done\n" +
        "  RUNFILES_DIR=\"${SCRIPT_PATH}.runfiles\"\n" +
        "  if [[ ! -d \"$RUNFILES_DIR\" ]]; then\n" +
        "    # Fallback: look relative to the original script.\n" +
        "    RUNFILES_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)/$(basename \"${BASH_SOURCE[0]}\").runfiles\"\n" +
        "  fi\n" +
        "fi\n" +
        "cd \"${RUNFILES_DIR}\"\n" +
        "\n" +
        "RUNTIME=\"" + runtime_path + "\"\n" +
        "RUNTIME_ARGS=(" + runtime_args_str + ")\n" +
        "if [[ -z \"$RUNTIME\" ]]; then\n" +
        "  RUNTIME=\"node\"\n" +
        "fi\n" +
        "\n" +
        "ENTRY=\"" + entry_path + "\"\n" +
        "\n" +
        "exec \"$RUNTIME\" ${RUNTIME_ARGS[@]+\"${RUNTIME_ARGS[@]}\"} \"$ENTRY\" \"$@\"\n"
    )

    ctx.actions.write(
        output = runner,
        content = runner_content,
        is_executable = True,
    )

    # Collect all runfiles: the runner, entry script, all package files, and the runtime.
    runfiles_files = [entry_script_file]
    if runtime_binary:
        runfiles_files.append(runtime_binary)

    # Also include the full package files so Node can resolve modules inside the package.
    runfiles = ctx.runfiles(
        files = runfiles_files,
        transitive_files = depset(ctx.files.package_files),
    )

    return [
        DefaultInfo(
            executable = runner,
            runfiles = runfiles,
        ),
    ]

npm_bin = rule(
    implementation = _npm_bin_impl,
    executable = True,
    attrs = {
        "package_files": attr.label_list(
            doc = "All files in the npm package directory (from the ts_npm_package target).",
            allow_files = True,
        ),
        "entry_script": attr.string(
            doc = "The relative path within the package to the bin entry script (e.g. 'vitest.mjs').",
            mandatory = True,
        ),
        "runtime": attr.label(
            doc = "Per-target override for the JS runtime binary. " +
                  "When set, takes priority over the js_runtime toolchain.",
            allow_single_file = True,
            executable = True,
            cfg = "exec",
        ),
    },
    toolchains = [
        config_common.toolchain_type(JS_RUNTIME_TOOLCHAIN_TYPE, mandatory = False),
    ],
    doc = """Exposes an npm package's bin script as an executable Bazel target.

Generated by npm_translate_lock for each entry in the package's 'bin' field.
Resolves Node.js from the js_runtime toolchain (or falls back to system node).

Example usage:
    bazel run @npm//:vitest_bin -- --version
    bazel run @npm//:tsx -- script.ts
""",
)
