"""Per-package npm repositories: one external repo per package, plus an alias hub.

Why this shape rather than one big repo
---------------------------------------
A single repository holding every package has to download and extract all of
them before it can generate any BUILD file, because it reads `bin` and `exports`
out of each extracted `package.json`. On a real 2731-package lockfile that is
~5 minutes and ~5 GB, paid in full even by a target whose only npm dependency is
vitest, in one serial Starlark loop with no resume: a single bad tarball restarts
everything.

Here each package is its own repository rule, so it reads its OWN package.json
and writes its OWN BUILD file. Bazel then fetches repositories on demand, which
gives four things the monolith cannot:

  - Laziness. Only packages in the requested targets' transitive closure are
    fetched. `@npm//:vitest` pulls vitest's subtree, not the lockfile.
  - Parallelism. Bazel fetches independent repositories concurrently instead of
    looping in Starlark.
  - Per-package caching and invalidation. Bumping one package invalidates one
    repository, not all of them.
  - Isolated failure. A malformed tarball fails its own package.

`npm_hub` is the stable label surface (`@npm//:zod`, `@npm//:types_react`,
`@npm//:vitest_bin`). It contains only `alias` targets and downloads nothing, so
it is cheap to regenerate whenever the lockfile changes. Repositories created by
one module extension can reference each other by apparent name, which is what
lets the hub point at spokes without constructing canonical repo names.

What still lives in the extension, not here
-------------------------------------------
The extension parses the lockfile once (no network) and hands each spoke a
resolved, ACYCLIC dependency list. Cycle breaking cannot move into the spokes:
npm has genuine circular peer dependencies, Bazel target graphs may not cycle,
and a spoke only knows about itself. Platform filtering, multi-version label
assignment and @types pairing stay there for the same reason -- they are
whole-graph decisions.
"""

_NPM_BUILD_HEADER = '''# Generated by npm_import. Do not edit.
load("@rules_typescript//ts/private:ts_npm_package.bzl", "ts_npm_package")
'''

def _detect_tarball_prefix(rctx, tarball_path):
    """Returns the archive's actual top-level directory, or "" if undetectable.

    npm tarballs conventionally extract under `package/`, but DefinitelyTyped
    ships `<name>/` and some ship `<name> v<major>.<minor>/`. Predicting the
    prefix from the package name means maintaining a table of exceptions, and a
    miss is not a warning -- it aborts the fetch. Reading the archive is cheap
    and always right.
    """
    result = rctx.execute(["tar", "-tzf", str(tarball_path)])
    if result.return_code != 0:
        return ""
    for line in result.stdout.split("\n"):
        entry = line.strip()
        if not entry:
            continue
        slash = entry.find("/")
        return entry[:slash] if slash > 0 else entry
    return ""

def _bin_entries(pkg_json):
    """Normalises package.json `bin` into {name: relative_path}.

    npm allows either a string (implying the package's own name) or a mapping.
    """
    raw = pkg_json.get("bin")
    if not raw:
        return {}
    if type(raw) == "string":
        name = pkg_json.get("name", "")
        if name.startswith("@") and "/" in name:
            name = name.split("/")[-1]
        return {name: raw} if name else {}
    if type(raw) == "dict":
        return {k: v for k, v in raw.items() if type(v) == "string"}
    return {}

def _exports_types(pkg_json):
    """Returns the .d.ts that exports["."] designates, or "".

    Preferred over globbing every .d.ts because a package's own exports map is
    the only authority on which declaration is its entry point.
    """
    exports = pkg_json.get("exports")
    if type(exports) != "dict":
        return ""
    root = exports.get(".")
    if type(root) == "string":
        return ""
    if type(root) != "dict":
        return ""
    for key in ("types", "typings"):
        value = root.get(key)
        if type(value) == "string":
            return value.removeprefix("./")
        if type(value) == "dict":
            for nested in ("import", "require", "default"):
                inner = value.get(nested)
                if type(inner) == "string":
                    return inner.removeprefix("./")
    return ""

def _primary_bin_name(package, bins):
    """The bin a bare `bazel run @npm//:<pkg>_bin` should mean.

    npm's own convention: the entry named after the package, else the only one.
    An ambiguous multi-bin package has no primary; callers name the script.
    """
    if not bins:
        return ""
    unscoped = package.split("/")[-1] if package.startswith("@") else package
    if unscoped in bins:
        return unscoped
    if len(bins) == 1:
        return list(bins.keys())[0]
    return ""

def _quote_list(items, indent = "        "):
    return "".join(['{}"{}",\n'.format(indent, i) for i in items])

def _apply_patch(rctx):
    """Applies the package's pnpm patch, failing the fetch if it does not land.

    The tarball just downloaded is byte-identical to the unpatched publish, so a
    patch that quietly fails to apply leaves nothing downstream able to tell the
    difference until production. Hence two loud gates: the digest below, and
    rctx.patch itself, which fails on any hunk that does not apply.
    """
    patch = rctx.attr.patch

    # An attr.label is not by itself a dependency of the fetch, and neither is
    # rctx.path on it: without this, editing a patch file leaves the already
    # fetched repository in place and the build keeps the old patch.
    rctx.watch(patch)

    if not rctx.attr.patch_sha256:
        rctx.patch(patch, strip = 1)
        return

    # Copied through the downloader purely to get its digest -- Starlark has no
    # hashing builtin. Deliberately WITHOUT download's own sha256 argument: a
    # checksummed request is served from the content-addressed repository cache
    # without reading the file at all, so an edited patch would be silently
    # replaced by the locked bytes on a warm cache and rejected on a cold one.
    local = "_pnpm.patch"
    result = rctx.download(url = "file://" + str(rctx.path(patch)), output = local)
    if result.sha256 != rctx.attr.patch_sha256:
        fail(
            "npm: {} does not match the sha256 recorded for {} in the lockfile's ".format(
                patch,
                rctx.attr.package,
            ) +
            "patchedDependencies:\n  lockfile: {}\n  file:     {}\n".format(
                rctx.attr.patch_sha256,
                result.sha256,
            ) +
            "pnpm records that digest when it writes the patch, so the two disagreeing " +
            "means the patch changed without `pnpm install` being re-run. Bazel would " +
            "apply a patch pnpm never saw.",
        )
    rctx.patch(local, strip = 1)
    rctx.delete(local)

def _npm_import_impl(rctx):
    tarball = "_pkg.tgz"
    if rctx.attr.integrity:
        rctx.download(url = rctx.attr.url, output = tarball, integrity = rctx.attr.integrity)
    else:
        rctx.download(url = rctx.attr.url, output = tarball)

    prefix = _detect_tarball_prefix(rctx, rctx.path(tarball))
    rctx.extract(archive = tarball, stripPrefix = prefix if prefix else rctx.attr.expected_prefix)
    rctx.delete(tarball)

    # Before package.json is read: a patch may change `bin` or `exports`, and
    # pnpm links the patched manifest, so the generated targets must describe
    # the patched package rather than the published one.
    if rctx.attr.patch:
        _apply_patch(rctx)

    pkg_json = {}
    pkg_json_path = rctx.path("package.json")
    if pkg_json_path.exists:
        pkg_json = json.decode(rctx.read(pkg_json_path))

    lines = [_NPM_BUILD_HEADER]
    bins = _bin_entries(pkg_json)
    if bins:
        lines.append('load("@rules_typescript//ts/private:npm_bin.bzl", "npm_bin")\n')
    lines.append('package(default_visibility = ["//visibility:public"])\n')
    lines.append('exports_files(["package.json"])\n')

    exports_types = _exports_types(pkg_json)

    def _package_stanza(target_name, package_name):
        stanza = [
            "ts_npm_package(",
            '    name = "{}",'.format(target_name),
            '    package_name = "{}",'.format(package_name),
            '    package_version = "{}",'.format(rctx.attr.version),
            '    package_dir = "package.json",',
            '    package_files = glob(["**/*"], exclude_directories = 1, allow_empty = True),',
        ]
        if rctx.attr.deps:
            stanza.append("    deps = [")
            stanza.append(_quote_list(rctx.attr.deps).rstrip("\n"))
            stanza.append("    ],")
        if rctx.attr.types_dep:
            stanza.append('    types_dep = "{}",'.format(rctx.attr.types_dep))
        if rctx.attr.is_types_package:
            stanza.append("    is_types_package = True,")
        if exports_types:
            stanza.append('    exports_types = "{}",'.format(exports_types))
        stanza.append(")\n")
        return "\n".join(stanza)

    lines.append(_package_stanza("pkg", rctx.attr.package))

    # An npm alias (`h3-v2: npm:h3@2.0.1`) is the same files installed under a
    # second name. package_name is what the node_modules tree builder writes on
    # disk, so the alias needs its own target: node_modules/h3-v2 is where
    # `import "h3-v2"` looks, and pointing a Bazel alias at :pkg would produce
    # node_modules/h3 instead.
    for target_name, alias_package in rctx.attr.aliases.items():
        lines.append(_package_stanza(target_name, alias_package))

    # Native binaries a bin script resolves at runtime live in sibling
    # repositories, so they are declared as targets rather than located by
    # directory name inside one shared repository.
    for bin_name, bin_path in bins.items():
        bin_stanza = [
            "npm_bin(",
            '    name = "{}",'.format(bin_name),
            '    entry_script = "{}",'.format(bin_path.removeprefix("./")),
            '    package_files = glob(["**/*"], exclude_directories = 1, allow_empty = True),',
        ]
        if rctx.attr.optional_dep_packages:
            bin_stanza.append("    optional_dep_packages = [")
            bin_stanza.append(_quote_list(rctx.attr.optional_dep_packages).rstrip("\n"))
            bin_stanza.append("    ],")
        bin_stanza.append(")\n")
        lines.append("\n".join(bin_stanza))

    # The hub aliases <label>_bin without being able to see whether a package has
    # a bin -- knowing that is exactly what downloading it would cost. So the
    # package exposes a fixed ":bin" name for its primary script, and the hub's
    # alias resolves only if something actually asks for it.
    primary_bin = _primary_bin_name(rctx.attr.package, bins)
    if primary_bin:
        lines.append('alias(\n    name = "bin",\n    actual = ":{}",\n)\n'.format(primary_bin))

    rctx.file("BUILD.bazel", "\n".join(lines))

npm_import = repository_rule(
    implementation = _npm_import_impl,
    attrs = {
        "package": attr.string(mandatory = True, doc = "npm package name, e.g. '@types/react'."),
        "version": attr.string(mandatory = True, doc = "Resolved version."),
        "url": attr.string(mandatory = True, doc = "Tarball URL."),
        "integrity": attr.string(doc = "SRI hash from the lockfile's resolution.integrity."),
        "expected_prefix": attr.string(
            default = "package",
            doc = "Fallback strip prefix, used only when the archive cannot be inspected.",
        ),
        "deps": attr.string_list(
            doc = "Apparent labels of sibling npm_import repos this package depends on, " +
                  "already cycle-broken and platform-filtered by the extension.",
        ),
        "types_dep": attr.string(doc = "Apparent label of the @types/* package for this one."),
        "is_types_package": attr.bool(default = False),
        "optional_dep_packages": attr.string_list(
            doc = "Apparent labels of sibling npm_import repos holding platform-specific " +
                  "native binaries this package's bin scripts resolve at runtime.",
        ),
        "aliases": attr.string_dict(
            doc = "Target name -> npm package name for each additional name this package " +
                  "is imported under (npm alias specifiers). The extension names the " +
                  "targets so the hub and the spoke agree without duplicating the " +
                  "name-to-label rule.",
        ),
        "patch": attr.label(
            allow_single_file = True,
            doc = "The pnpm patch to apply to this package, from patchedDependencies.",
        ),
        "patch_sha256": attr.string(
            doc = "sha256 of the patch file as recorded in the lockfile's " +
                  "patchedDependencies. Empty when the lockfile records the digest " +
                  "in some other form, which skips the content check.",
        ),
    },
    doc = "Fetches one npm package into its own repository and generates its BUILD file.",
)

def _npm_hub_impl(rctx):
    lines = [
        "# Generated by npm_hub. Do not edit.",
        "#",
        "# Aliases only: this repository downloads nothing, so it stays cheap to",
        "# regenerate when the lockfile changes, and referencing one alias fetches",
        "# only that package's own repository.",
        'package(default_visibility = ["//visibility:public"])',
        "",
    ]
    for alias_name in sorted(rctx.attr.aliases.keys()):
        lines.append("alias(")
        lines.append('    name = "{}",'.format(alias_name))
        lines.append('    actual = "{}",'.format(rctx.attr.aliases[alias_name]))
        lines.append(")")
        lines.append("")
    if rctx.attr.broken_cycle_edges:
        lines.append("# Circular npm dependency edges removed for an acyclic target graph.")
        lines.append("# These packages rely on Node's CJS cycle tolerance at runtime.")
        for edge in rctx.attr.broken_cycle_edges:
            lines.append("#   CYCLE BROKEN: {}".format(edge))
    rctx.file("BUILD.bazel", "\n".join(lines) + "\n")

npm_hub = repository_rule(
    implementation = _npm_hub_impl,
    attrs = {
        "aliases": attr.string_dict(
            mandatory = True,
            doc = "Label name -> apparent label of the target it forwards to.",
        ),
        "broken_cycle_edges": attr.string_list(
            doc = "Human-readable record of edges the extension removed.",
        ),
    },
    doc = "Alias-only hub giving npm packages stable @npm//:<name> labels.",
)
