"""Rule for executable npm bin script targets.

npm_bin wraps a bin script from an npm package as a Bazel executable target.
It resolves Node.js from the js_runtime toolchain (or falls back to system node)
and invokes the specified script entry point with any provided arguments.

Generated by npm_translate_lock for each entry in a package's "bin" field.

Usage (generated by npm_translate_lock):
    npm_bin(
        name = "vitest_bin",
        package = ":vitest",
        entry_script = "vitest.mjs",
        package_dir = "vitest__3_0_9",
    )

Users can then:
    bazel run @npm//:vitest_bin -- --version
"""

load("//ts/private:providers.bzl", "NpmPackageInfo")
load("//ts/private:runtime.bzl", "JS_RUNTIME_TOOLCHAIN_TYPE", "get_js_runtime")

def _shell_escape(s):
    """Escapes a string for safe embedding in a double-quoted shell string."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("`", "\\`")

def _npm_bin_impl(ctx):
    # Resolve the JS runtime from the toolchain or fall back to system node.
    runtime_binary = None
    runtime_args = []
    if ctx.file.runtime:
        runtime_binary = ctx.file.runtime
    else:
        js_runtime = get_js_runtime(ctx)
        if js_runtime:
            runtime_binary = js_runtime.runtime_binary
            runtime_args = js_runtime.args_prefix

    # Helper: convert a file's short_path to its runfiles-tree-relative path.
    # Bazel runfiles layout with --nolegacy_external_runfiles (bzlmod default):
    #   $RUNFILES_DIR/_main/<short_path>          for main-workspace files
    #   $RUNFILES_DIR/<repo_name>/<path>          for external-repo files
    # File.short_path encoding:
    #   main-workspace:   "path/to/file"   (no prefix)
    #   external-repo:    "../repo_name/path"  (leading "../")
    def _rl(short_path):
        if short_path.startswith("../"):
            return short_path[3:]  # strip leading "../"
        return "_main/" + short_path

    # Locate the entry script from the package files.
    # The package_dir attribute holds the package.json file; the entry script
    # is a sibling file (relative to the package root).
    entry_script_file = None
    entry_script = ctx.attr.entry_script
    for f in ctx.files.package_files:
        # Match the file whose path ends with the entry_script (relative path within package).
        # package_dir.path example: external/+npm+npm/vitest__3_0_9/package.json
        # entry file path example:  external/+npm+npm/vitest__3_0_9/vitest.mjs
        if f.basename == entry_script or f.path.endswith("/" + entry_script):
            entry_script_file = f
            break

    if not entry_script_file:
        available = [f.basename for f in ctx.files.package_files]
        fail(
            "npm_bin: entry script '{}' not found in package files for target '{}'.\n".format(
                entry_script,
                ctx.label,
            ) +
            "This usually means the npm package's 'bin' field references a file that " +
            "was not included in package_files, or the entry_script path is wrong.\n" +
            "Available files: {}".format(", ".join(available[:20]) + (" ..." if len(available) > 20 else "")),
        )

    runtime_path = _rl(runtime_binary.short_path) if runtime_binary else ""
    entry_path = _rl(entry_script_file.short_path)
    runtime_args_str = " ".join(["\"{}\"".format(_shell_escape(a)) for a in runtime_args])

    # Build the optional-dependency node_modules setup block.
    # Some npm packages (e.g. oxlint) use platform-specific native binaries
    # referenced via require.resolve('@scope/platform-pkg/binary').  Node.js
    # module resolution walks parent directories looking for node_modules/.
    # When the entry script runs inside a Bazel runfiles tree (or action sandbox),
    # packages live in a flat layout (e.g. repo/pkg__ver/) that does not
    # match the expected node_modules/ structure.
    #
    # optional_dep_info: list of "npm_package_name:dir_name" strings where
    # dir_name is the Bazel package directory name (e.g. "oxlint_linux-x64-gnu__0_16_6").
    # The runner derives the full runfiles path by finding a file with that dir
    # in package_files, then creates node_modules/ symlinks.
    optional_dep_setup_lines = []
    if ctx.attr.optional_dep_info:
        # Build a map: dir_name → runfiles_dir_path
        # by scanning package_files for files whose path contains each dir_name.
        dir_name_to_rl_path = {}
        for info in ctx.attr.optional_dep_info:
            colon_idx = info.find(":")
            if colon_idx == -1:
                continue
            dir_name = info[colon_idx + 1:]
            # Find a file in package_files that lives in this directory.
            for f in ctx.files.package_files:
                # File path: external/+npm+npm/dir_name/file
                # or: +npm+npm/dir_name/file (relative exec path)
                # We look for "/<dir_name>/" in the path.
                if ("/" + dir_name + "/") in f.path:
                    # The runfiles path for the directory:
                    # _rl(short_path) gives "repo_name/dir_name/file"
                    # Strip the "/file" suffix to get "repo_name/dir_name"
                    rl_file = _rl(f.short_path)
                    # Find "/<dir_name>/" in rl_file and take everything up to end of dir_name
                    marker = "/" + dir_name + "/"
                    idx = rl_file.find(marker)
                    if idx >= 0:
                        dir_name_to_rl_path[dir_name] = rl_file[:idx + len(marker) - 1]
                    break

        if dir_name_to_rl_path:
            optional_dep_setup_lines += [
                "# Set up node_modules symlinks for optional platform dependencies.\n",
                "# Enables require.resolve('@scope/pkg/binary') to work.\n",
                "#\n",
                "# We use a temp directory for the node_modules tree so that the\n",
                "# symlinks are always writable — both in Bazel action sandboxes\n",
                "# (where RUNFILES_DIR for tools is read-only) and for bazel run\n",
                "# (where the runfiles tree is immutable after build).\n",
                '_TMPNM="$(mktemp -d)"\n',
            ]
            for info in ctx.attr.optional_dep_info:
                colon_idx = info.find(":")
                if colon_idx == -1:
                    continue
                npm_name = info[:colon_idx]
                dir_name = info[colon_idx + 1:]
                rl_path = dir_name_to_rl_path.get(dir_name)
                if not rl_path:
                    continue
                escaped_rl_path = _shell_escape(rl_path)
                if npm_name.startswith("@"):
                    slash = npm_name.find("/")
                    if slash != -1:
                        scope = npm_name[:slash]        # e.g. "@oxlint"
                        pkg = npm_name[slash + 1:]      # e.g. "linux-x64-gnu"
                        escaped_scope = _shell_escape(scope)
                        escaped_pkg = _shell_escape(pkg)
                        optional_dep_setup_lines += [
                            'mkdir -p "$_TMPNM/' + escaped_scope + '"\n',
                            'ln -sfn "${RUNFILES_DIR}/' + escaped_rl_path + '" "$_TMPNM/' + escaped_scope + "/" + escaped_pkg + '"\n',
                        ]
                else:
                    escaped_npm_name = _shell_escape(npm_name)
                    optional_dep_setup_lines.append(
                        'ln -sfn "${RUNFILES_DIR}/' + escaped_rl_path + '" "$_TMPNM/' + escaped_npm_name + '"\n',
                    )
    # When optional deps are present, emit a NODE_PATH export so that
    # require.resolve() finds the node_modules symlinks even when Node.js
    # resolves the entry script's __filename through symlinks to an absolute
    # path outside the runfiles tree.  We point NODE_PATH at the temp dir
    # so it works both in actions (read-only RUNFILES_DIR) and bazel run.
    node_path_export = ""
    if optional_dep_setup_lines:
        node_path_export = 'export NODE_PATH="$_TMPNM:${NODE_PATH:-}"\n'

    optional_dep_setup = "".join(optional_dep_setup_lines)

    runner = ctx.actions.declare_file("{}_bin_runner.sh".format(ctx.label.name))
    runner_content = (
        "#!/usr/bin/env bash\n" +
        "# Bazel-generated npm bin runner for " + str(ctx.label) + "\n" +
        "set -euo pipefail\n" +
        "\n" +
        "# Resolve the runfiles root.\n" +
        "# Bazel sets RUNFILES_DIR for both 'bazel run' and 'bazel test'.\n" +
        "# TEST_SRCDIR is the legacy name used in tests.\n" +
        "if [[ -n \"${RUNFILES_DIR:-}\" ]]; then\n" +
        "  : # RUNFILES_DIR already set by Bazel\n" +
        "elif [[ -n \"${TEST_SRCDIR:-}\" ]]; then\n" +
        "  RUNFILES_DIR=\"$TEST_SRCDIR\"\n" +
        "else\n" +
        "  # Determine runfiles dir from the script's location.\n" +
        "  # Bazel places the .runfiles dir alongside the script binary.\n" +
        "  SCRIPT_PATH=\"${BASH_SOURCE[0]}\"\n" +
        "  # Resolve symlinks to find the real script location.\n" +
        "  while [[ -L \"$SCRIPT_PATH\" ]]; do\n" +
        "    SCRIPT_PATH=\"$(readlink \"$SCRIPT_PATH\")\"\n" +
        "  done\n" +
        "  RUNFILES_DIR=\"${SCRIPT_PATH}.runfiles\"\n" +
        "  if [[ ! -d \"$RUNFILES_DIR\" ]]; then\n" +
        "    # Fallback: look relative to the original script.\n" +
        "    RUNFILES_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)/$(basename \"${BASH_SOURCE[0]}\").runfiles\"\n" +
        "  fi\n" +
        "fi\n" +
        "\n" +
        optional_dep_setup +
        node_path_export +
        "\n" +
        "cd \"${RUNFILES_DIR}\"\n" +
        "\n" +
        "RUNTIME=\"" + runtime_path + "\"\n" +
        "RUNTIME_ARGS=(" + runtime_args_str + ")\n" +
        "if [[ -z \"$RUNTIME\" ]]; then\n" +
        "  RUNTIME=\"node\"\n" +
        "fi\n" +
        "\n" +
        "ENTRY=\"" + entry_path + "\"\n" +
        "\n" +
        (
            # When optional deps are set up in a tmpdir, we cannot use exec
            # (which would replace the shell before the trap can clean up).
            # Instead run the command, capture the exit code, clean up, and exit.
            "_exit=0\n" +
            "\"$RUNTIME\" ${RUNTIME_ARGS[@]+\"${RUNTIME_ARGS[@]}\"} \"$ENTRY\" \"$@\" || _exit=$?\n" +
            'rm -rf "$_TMPNM" 2>/dev/null || true\n' +
            "exit $_exit\n"
            if optional_dep_setup_lines else
            "exec \"$RUNTIME\" ${RUNTIME_ARGS[@]+\"${RUNTIME_ARGS[@]}\"} \"$ENTRY\" \"$@\"\n"
        )
    )

    ctx.actions.write(
        output = runner,
        content = runner_content,
        is_executable = True,
    )

    # Collect all runfiles: the runner, entry script, all package files, and the runtime.
    runfiles_files = [entry_script_file]
    if runtime_binary:
        runfiles_files.append(runtime_binary)

    # Also include the full package files so Node can resolve modules inside the package.
    runfiles = ctx.runfiles(
        files = runfiles_files,
        transitive_files = depset(ctx.files.package_files),
    )

    return [
        DefaultInfo(
            executable = runner,
            runfiles = runfiles,
        ),
    ]

npm_bin = rule(
    implementation = _npm_bin_impl,
    executable = True,
    attrs = {
        "package_files": attr.label_list(
            doc = "All files in the npm package directory (from the ts_npm_package target).",
            allow_files = True,
        ),
        "entry_script": attr.string(
            doc = "The relative path within the package to the bin entry script (e.g. 'vitest.mjs').",
            mandatory = True,
        ),
        "optional_dep_info": attr.string_list(
            doc = """Optional dependency information for platform-specific native binaries.

Each entry is a colon-separated string: "npm_package_name:bazel_dir_name".
Example: "@oxlint/linux-x64-gnu:oxlint_linux-x64-gnu__0_16_6"

At runtime, the runner creates node_modules/ symlinks for each entry so that
require.resolve('@oxlint/linux-x64-gnu/oxlint') works correctly inside Bazel
action sandboxes and runfiles trees.
""",
            default = [],
        ),
        "runtime": attr.label(
            doc = "Per-target override for the JS runtime binary. " +
                  "When set, takes priority over the js_runtime toolchain.",
            allow_single_file = True,
            executable = True,
            cfg = "exec",
        ),
    },
    toolchains = [
        config_common.toolchain_type(JS_RUNTIME_TOOLCHAIN_TYPE, mandatory = False),
    ],
    doc = """Exposes an npm package's bin script as an executable Bazel target.

Generated by npm_translate_lock for each entry in the package's 'bin' field.
Resolves Node.js from the js_runtime toolchain (or falls back to system node).

Example usage:
    bazel run @npm//:vitest_bin -- --version
    bazel run @npm//:tsx -- script.ts
""",
)
