"""Repository rule and macros for hermetic pnpm.

pnpm publishes standalone single-file executables that require no Node.js.
This module downloads the appropriate binary and exposes :pnpm and
:add_package run targets for workspace-level package management.

Usage in MODULE.bazel:
    npm = use_extension("@rules_typescript//npm:extensions.bzl", "npm")
    npm.pnpm(version = "10.32.1")  # optional; defaults to DEFAULT_PNPM_VERSION
    npm.translate_lock(pnpm_lock = "//:pnpm-lock.yaml")
    use_repo(npm, "npm", "pnpm")

Usage targets generated by ts_pnpm() / ts_add_package():
    bazel run //:pnpm -- --version
    bazel run //:pnpm -- add zod --lockfile-only
    bazel run //:add_package -- zod
"""

load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

# ─── constants ────────────────────────────────────────────────────────────────

# Default pnpm version downloaded when the consumer does not call npm.pnpm().
# Exported as a public constant so the npm module extension can reference it
# without duplicating the value.
DEFAULT_PNPM_VERSION = "10.32.1"

# Private alias for use within this file.
_DEFAULT_PNPM_VERSION = DEFAULT_PNPM_VERSION

# Platform keys match PLATFORM_CONSTRAINTS in toolchain.bzl.
# The pnpm project uses:
#   pnpm-linux-x64, pnpm-linux-arm64
#   pnpm-macos-x64, pnpm-macos-arm64
#   pnpm-win-x64.exe, pnpm-win-arm64.exe
_PNPM_PLATFORMS = {
    "linux_amd64": struct(
        binary_name = "pnpm-linux-x64",
        os = "@platforms//os:linux",
        cpu = "@platforms//cpu:x86_64",
        exe = "",
    ),
    "linux_arm64": struct(
        binary_name = "pnpm-linux-arm64",
        os = "@platforms//os:linux",
        cpu = "@platforms//cpu:aarch64",
        exe = "",
    ),
    "darwin_amd64": struct(
        binary_name = "pnpm-macos-x64",
        os = "@platforms//os:macos",
        cpu = "@platforms//cpu:x86_64",
        exe = "",
    ),
    "darwin_arm64": struct(
        binary_name = "pnpm-macos-arm64",
        os = "@platforms//os:macos",
        cpu = "@platforms//cpu:aarch64",
        exe = "",
    ),
}

# sha256 checksums for pnpm standalone binaries.
# Format: { "VERSION": { "platform_key": "sha256" } }
# To add a new version: download each binary and compute sha256.
_PNPM_CHECKSUMS = {
    "10.32.1": {
        "linux_amd64": "c5607a86bfb948297e96b393a53c90107766fe56329e62967b1f239d861d4363",
        "linux_arm64": "c0db0b837971fde6f9781af8914e54eb163721193a36d35cbcf1794b3474a407",
        "darwin_amd64": "8b83277343bbc400fdb90608bd51b4f56e380e6624ac5fd0e11d6c08815e3f04",
        "darwin_arm64": "b0904b4e0cf36704fcdc24bcdb5f03388799a631510d1fb0d459ea69c7b1e2d9",
    },
}

# ─── repository rule ──────────────────────────────────────────────────────────

def _pnpm_repo_impl(repository_ctx):
    """Downloads pnpm standalone binaries for all supported platforms.

    Each platform binary is placed in a subdirectory named after the platform
    key (e.g. linux_amd64/pnpm) and exposed via exports_files. A select()-based
    alias named :pnpm_bin resolves to the correct binary at analysis time.
    """
    version = repository_ctx.attr.version
    checksums = _PNPM_CHECKSUMS.get(version, {})

    build_lines = [
        '# Auto-generated by pnpm_repo repository rule.',
        'package(default_visibility = ["//visibility:public"])',
        "",
    ]

    for platform, info in _PNPM_PLATFORMS.items():
        binary_name = info.binary_name + info.exe
        url = "https://github.com/pnpm/pnpm/releases/download/v{version}/{binary}".format(
            version = version,
            binary = binary_name,
        )
        output_path = "{}/pnpm{}".format(platform, info.exe)

        download_kwargs = {
            "url": url,
            "output": output_path,
            "executable": True,
        }
        checksum = checksums.get(platform, "")
        if checksum:
            download_kwargs["sha256"] = checksum
        else:
            # buildifier: disable=print
            print("WARNING: No sha256 checksum for pnpm platform '{}' version '{}'. Set _PNPM_CHECKSUMS for reproducible builds.".format(platform, version))

        repository_ctx.download(**download_kwargs)

        build_lines.append('exports_files(["{output}"])'.format(output = output_path))
        build_lines.append("")

    # A config_setting per platform so we can use select() in sh_binary data.
    for platform, info in _PNPM_PLATFORMS.items():
        build_lines.append(
            """\
config_setting(
    name = "is_{platform}",
    constraint_values = [
        "{os}",
        "{cpu}",
    ],
)
""".format(platform = platform, os = info.os, cpu = info.cpu),
        )

    # An alias that resolves to the host-platform binary.
    # The select() maps each config_setting to the corresponding binary path.
    # Note: alias.actual requires a string label, not a list.
    select_arms = ""
    for platform, info in _PNPM_PLATFORMS.items():
        select_arms += '        ":is_{platform}": ":{platform}/pnpm{exe}",\n'.format(
            platform = platform,
            exe = info.exe,
        )

    build_lines.append(
        """\
# Resolves to the correct pnpm binary for the host execution platform.
alias(
    name = "pnpm_bin",
    actual = select({{
{arms}    }}),
)
""".format(arms = select_arms),
    )

    repository_ctx.file("BUILD.bazel", "\n".join(build_lines))

pnpm_repo = repository_rule(
    implementation = _pnpm_repo_impl,
    attrs = {
        "version": attr.string(
            doc = "pnpm version to download (e.g. '10.32.1').",
            mandatory = True,
        ),
    },
    doc = """\
Downloads the pnpm standalone binary for all supported platforms.

The standalone binary is self-contained (no Node.js required). Each platform
binary is downloaded into a subdirectory and exposed via exports_files.
A :pnpm_bin alias selects the correct binary for the host platform at
analysis time.

Checksums are embedded for known versions. When a new version is needed, add
its sha256 values to _PNPM_CHECKSUMS in ts/private/pnpm.bzl.
""",
)

# ─── workspace macros ─────────────────────────────────────────────────────────

def ts_pnpm(name = "pnpm", pnpm_repo_name = "pnpm"):
    """Generates a :pnpm run target that executes pnpm in the workspace root.

    Usage:
        bazel run //:pnpm -- --version
        bazel run //:pnpm -- add zod --lockfile-only
        bazel run //:pnpm -- install --frozen-lockfile

    The target changes to $BUILD_WORKSPACE_DIRECTORY before running pnpm,
    so it operates on the source tree (not the sandbox) as expected.

    Args:
        name: Target name (default "pnpm").
        pnpm_repo_name: Name of the external repo created by pnpm_repo
                        (default "pnpm", matching npm.pnpm() in MODULE.bazel).
    """
    sh_binary(
        name = name,
        srcs = ["@rules_typescript//tools:pnpm_wrapper.sh"],
        data = ["@{}//:pnpm_bin".format(pnpm_repo_name)],
        env = {"PNPM_BIN": "$(rootpath @{}//:pnpm_bin)".format(pnpm_repo_name)},
        visibility = ["//visibility:public"],
    )

def ts_add_package(name = "add_package", pnpm_repo_name = "pnpm"):
    """Generates an :add_package run target for adding npm packages.

    Automatically appends --lockfile-only so pnpm updates pnpm-lock.yaml
    without creating a node_modules directory.

    Usage:
        bazel run //:add_package -- zod
        bazel run //:add_package -- -D typescript

    Args:
        name: Target name (default "add_package").
        pnpm_repo_name: Name of the external repo created by pnpm_repo
                        (default "pnpm", matching npm.pnpm() in MODULE.bazel).
    """
    sh_binary(
        name = name,
        srcs = ["@rules_typescript//tools:add_package_wrapper.sh"],
        data = ["@{}//:pnpm_bin".format(pnpm_repo_name)],
        env = {"PNPM_BIN": "$(rootpath @{}//:pnpm_bin)".format(pnpm_repo_name)},
        visibility = ["//visibility:public"],
    )
