"""ts_npm_package: one downloaded npm package, as npm_import writes it.

The target's TsInfo stages nothing by path -- a consumer reaches the package
through the node_modules tree its forest builds -- and names the package's
closure in `npm_packages`; NpmPackageInfo is what lays that tree out and
carries the snapshot's store, `NpmPackageInfo.store`. The `@types/*` package
paired through `types_dep` travels in the closure, so a forest links the two
side by side, where TypeScript looks for them.
"""

load("//npm/private:store.bzl", "NpmStoreInfo")
load("//ts/private:providers.bzl", "NpmPackageInfo", "ts_info")

def _ts_npm_package_impl(ctx):
    package_dir = ctx.file.package_dir
    all_files = ctx.files.package_files

    direct_npm_dep_infos = []
    transitive_npm_dep_sets = []
    for dep in ctx.attr.deps:
        info = dep[NpmPackageInfo]
        direct_npm_dep_infos.append(info)
        transitive_npm_dep_sets.append(info.transitive_deps)
    if ctx.attr.types_dep:
        types_npm = ctx.attr.types_dep[NpmPackageInfo]
        transitive_npm_dep_sets.append(
            depset([types_npm], transitive = [types_npm.transitive_deps]),
        )

    npm_info = NpmPackageInfo(
        package_name = ctx.attr.package_name,
        package_version = ctx.attr.package_version,
        peer_id = ctx.attr.peer_id,
        package_dir = package_dir,
        package_root = package_dir.dirname,
        all_files = depset(all_files),
        direct_deps = direct_npm_dep_infos,
        transitive_deps = depset(
            direct_npm_dep_infos,
            transitive = transitive_npm_dep_sets,
            order = "postorder",
        ),
        store = ctx.attr.store[NpmStoreInfo],
    )
    return [
        DefaultInfo(files = depset(all_files)),
        ts_info(npm_packages = npm_info.transitive_deps),
        npm_info,
    ]

ts_npm_package = rule(
    implementation = _ts_npm_package_impl,
    attrs = {
        "package_name": attr.string(
            doc = "The npm package name, e.g. 'react' or '@types/react'.",
            mandatory = True,
        ),
        "package_version": attr.string(
            doc = "The resolved npm package version.",
            mandatory = True,
        ),
        "peer_id": attr.string(
            doc = "Filesystem-safe token naming the peer set this resolution was made " +
                  "against, empty when pnpm resolved the package only one way. Written by " +
                  "npm_import from the snapshot key's peer suffix; two snapshots sharing " +
                  "name@version differ only here.",
        ),
        "package_dir": attr.label(
            doc = "The package.json at the root of the extracted npm package; its directory is the package root.",
            allow_single_file = True,
            mandatory = True,
        ),
        "package_files": attr.label_list(
            doc = "All files in the package directory.",
            allow_files = True,
            mandatory = True,
        ),
        "deps": attr.label_list(
            doc = "Other ts_npm_package targets that this package depends on.",
            providers = [NpmPackageInfo],
        ),
        "types_dep": attr.label(
            doc = "The @types/* package that provides declarations for this package (if separate).",
            providers = [NpmPackageInfo],
        ),
        "store": attr.label(
            doc = "This snapshot's store target in the lockfile's package, " +
                  "`node_modules/.pnpm/<key>/node_modules/<name>`.",
            providers = [NpmStoreInfo],
            mandatory = True,
        ),
    },
    doc = """Wraps a downloaded npm package as a Bazel target.

Provides TsInfo and NpmPackageInfo, so ts_compile targets depend on npm
packages through the same `deps` as on first-party targets and the forest
links the package under its name.

Example (generated by npm_import):
    ts_npm_package(
        name = "pkg",
        package_name = "react",
        package_version = "19.0.0",
        package_dir = ":node_modules/react/package.json",
        package_files = glob(["node_modules/react/**/*"]),
        store = "@@//:node_modules/.pnpm/react@19.0.0/node_modules/react",
        types_dep = "@npm__types_react__19_0_0//:pkg",
    )
""",
)
