load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "remix",
    srcs = [
        "plugin.go",
        "routes.go",
    ],
    importpath = "github.com/mikn/rules_typescript/gazelle/remix",
    visibility = ["//gazelle:__pkg__"],
    deps = [
        "@com_github_bazelbuild_buildtools//build",
        "@gazelle//language",
        "@gazelle//rule",
    ],
)

go_test(
    name = "remix_test",
    srcs = ["plugin_test.go"],
    embed = [":remix"],
    deps = [
        "@gazelle//config",
        "@gazelle//language",
        "@gazelle//rule",
    ],
)
