load("@rules_typescript//ts:defs.bzl", "ts_compile", "ts_config", "ts_test")

ts_compile(
    name = "schema",
    srcs = [
        "index.ts",
        "user.ts",
    ],
    node_modules = "//:node_modules",
    tsconfig = ":tsconfig",
    visibility = ["//visibility:public"],
    deps = ["@npm//:zod"],
)

ts_test(
    name = "schema_test",
    srcs = ["user.test.ts"],
    node_modules = "//:node_modules",
    tsconfig = ":tsconfig",
    deps = [
        ":schema",
        "@npm//:vite",
        "@npm//:vitest",
        "@npm//:zod",
    ],
)

ts_config(
    name = "tsconfig",
    src = "tsconfig.json",
    visibility = ["//visibility:public"],
    deps = ["//:tsconfig"],
)
