load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

# gazelle:prefix github.com/mikn/rules_typescript/tools/changelog

go_library(
    name = "changelog_lib",
    srcs = ["main.go"],
    importpath = "github.com/mikn/rules_typescript/tools/changelog",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "changelog",
    embed = [":changelog_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "changelog_test",
    size = "small",
    srcs = ["main_test.go"],
    data = ["//changelog.d:fragments"],
    embed = [":changelog_lib"],
    env = {"CHANGELOG_FRAGMENTS": "$(rlocationpaths //changelog.d:fragments)"},
    deps = ["@rules_go//go/runfiles"],
)
