// Package tanstack implements a Gazelle plugin for TanStack Start framework
// conventions. It augments the base TypeScript extension with route-aware rule
// generation so that TanStack Start projects get correct BUILD files with zero
// manual edits.
//
// TanStack Start conventions recognised:
//
//   - routes/ directory tree: each route file gets a ts_compile target.
//   - __root.tsx: root layout; treated as a regular source file in its package.
//   - routeTree.gen.ts: generated by the TanStack Router CLI; excluded from
//     all source targets by the base extension via the isGeneratedFile check.
//   - Route files gain an implicit dep on their nearest ancestor route package
//     when they import from it transitively.
//   - $param.tsx / $param/: files/directories whose basename starts with "$"
//     are dynamic route segments (e.g. $userId.tsx → /:userId).
//
// This plugin operates as a post-processor on top of the base generation logic:
// the base extension generates rules, and this plugin adjusts them if the
// directory is inside (or is) a routes/ tree.
package tanstack

import (
	"path"
	"strings"

	"github.com/bazelbuild/bazel-gazelle/language"
	"github.com/bazelbuild/bazel-gazelle/rule"
)

// ---- constants -------------------------------------------------------------

const (
	// routesDirName is the conventional directory name for TanStack Start routes.
	routesDirName = "routes"

	// rootLayoutFile is the root layout component file name.
	rootLayoutFile = "__root.tsx"

	// routeTreeGenFile is the generated route tree file that must be excluded
	// from source targets.
	routeTreeGenFile = "routeTree.gen.ts"

	// sharedComponentsLabel is the default Bazel label for shared components.
	// Projects can override this via the gazelle_ts.json configuration.
	sharedComponentsLabel = "//src/components"

	// routeTargetKey is the private attribute key used to mark ts_compile rules
	// that represent TanStack Start route targets.
	routeTargetKey = "tanstack_route_target"

	// routeInfoKey stores the RouteInfo for the rule, enabling downstream
	// tooling to read route metadata without re-parsing file names.
	routeInfoKey = "tanstack_route_info"
)

// ---- RouteInfo -------------------------------------------------------------

// RouteInfo holds metadata about a TanStack Start route target. It is stored
// as a private attribute on ts_compile rules inside the routes/ tree and can
// be read by downstream rules or analysis tools.
type RouteInfo struct {
	// RoutePattern is the URL pattern this route handles, derived from the
	// file/directory path relative to the routes/ root. Dynamic segments
	// ($param) are represented with a leading colon, e.g. "/:userId".
	//
	// Examples:
	//   routes/index.tsx          → "/"
	//   routes/about.tsx          → "/about"
	//   routes/users/$userId.tsx  → "/users/:userId"
	//   routes/__root.tsx         → "" (root layout, no own URL pattern)
	RoutePattern string

	// IsRootLayout is true for the __root.tsx file.
	IsRootLayout bool

	// DynamicSegments lists the names of dynamic route parameters found in the
	// path, in order. For routes/users/$userId/posts/$postId.tsx this would be
	// ["userId", "postId"].
	DynamicSegments []string
}

// ---- Plugin API ------------------------------------------------------------

// AdjustGenerateResult post-processes the GenerateResult produced by the base
// TypeScript extension for directories inside a TanStack Start routes tree.
//
// args is the original GenerateArgs, result is the result from the base
// extension. The adjusted result is returned.
//
// If the directory is not part of a TanStack Start routes tree, the original
// result is returned unchanged.
func AdjustGenerateResult(args language.GenerateArgs, result language.GenerateResult) language.GenerateResult {
	if !isInsideRoutesDir(args.Rel) {
		return result
	}

	return adjustRouteRules(args, result)
}

// ---- route detection -------------------------------------------------------

// isInsideRoutesDir returns true if rel is inside a "routes" directory, i.e.,
// the path contains a "routes" component.
func isInsideRoutesDir(rel string) bool {
	for _, part := range strings.Split(rel, "/") {
		if part == routesDirName {
			return true
		}
	}
	return false
}

// isRootLayoutDir returns true if this directory contains __root.tsx, making
// it the root layout directory.
func isRootLayoutDir(args language.GenerateArgs) bool {
	for _, f := range args.RegularFiles {
		if f == rootLayoutFile {
			return true
		}
	}
	return false
}

// relativeToRoutesRoot returns the path relative to the innermost "routes/"
// directory. For example, "src/routes/users/$userId" returns "users/$userId".
// Returns "" if no routes/ component is found.
func relativeToRoutesRoot(rel string) string {
	parts := strings.Split(rel, "/")
	for i := len(parts) - 1; i >= 0; i-- {
		if parts[i] == routesDirName {
			return strings.Join(parts[i+1:], "/")
		}
	}
	return ""
}

// routePatternFromRel derives the URL route pattern from a workspace-relative
// path inside the routes/ tree. Dynamic segments ($param) become :param.
//
// Mapping rules (consistent with TanStack Router file-based routing):
//   - ""           (routes/ root itself) → "/"
//   - "index"      (index route)         → "/"  within parent
//   - "$userId"    (dynamic segment)     → ":userId"
//   - "__root"     (root layout)         → "" (no URL segment)
//   - flat segment                       → "/segment"
func routePatternFromRel(routesRel string) string {
	if routesRel == "" {
		return "/"
	}

	parts := strings.Split(routesRel, "/")
	var segments []string

	for _, p := range parts {
		// Strip file extension from the last segment.
		base := p
		for _, ext := range []string{".tsx", ".ts"} {
			if strings.HasSuffix(base, ext) {
				base = base[:len(base)-len(ext)]
				break
			}
		}

		switch {
		case base == "__root":
			// Root layout has no URL segment.
			continue
		case base == "index":
			// Index file resolves to the parent route, no extra segment.
			continue
		case strings.HasPrefix(base, "$"):
			// Dynamic segment: $userId → :userId
			segments = append(segments, ":"+base[1:])
		default:
			segments = append(segments, base)
		}
	}

	if len(segments) == 0 {
		return "/"
	}
	return "/" + strings.Join(segments, "/")
}

// dynamicSegmentsFromRel returns the parameter names for dynamic route
// segments in a path relative to the routes/ root.
//
// Example: "users/$userId/posts/$postId" → ["userId", "postId"]
func dynamicSegmentsFromRel(routesRel string) []string {
	var params []string
	for _, part := range strings.Split(routesRel, "/") {
		// Strip extension from the final segment.
		base := part
		for _, ext := range []string{".tsx", ".ts"} {
			if strings.HasSuffix(base, ext) {
				base = base[:len(base)-len(ext)]
				break
			}
		}
		if strings.HasPrefix(base, "$") {
			params = append(params, base[1:])
		}
	}
	return params
}

// buildRouteInfo constructs a RouteInfo for the given generate args. It uses
// the path relative to the routes/ root to derive the URL pattern and dynamic
// segment list.
func buildRouteInfo(args language.GenerateArgs) RouteInfo {
	routesRel := relativeToRoutesRoot(args.Rel)
	isRoot := isRootLayoutDir(args)

	if isRoot {
		return RouteInfo{
			RoutePattern: "",
			IsRootLayout: true,
		}
	}

	return RouteInfo{
		RoutePattern:    routePatternFromRel(routesRel),
		IsRootLayout:    false,
		DynamicSegments: dynamicSegmentsFromRel(routesRel),
	}
}

// ---- rule adjustment -------------------------------------------------------

// adjustRouteRules modifies rules generated for a directory inside the routes
// tree. Specifically:
//
//  1. Root layout directory (__root.tsx present): the ts_compile target gets
//     an explicit dep on shared components so that the root layout can import
//     the app shell, nav, etc.
//
//  2. Non-root route directories: each ts_compile target is tagged as a route
//     target via a private attribute so the dep resolver can reference it.
//
//  3. routeTree.gen.ts is guaranteed to be absent from all srcs (the base
//     extension already excludes *.gen.ts files via isGeneratedFile, but we
//     double-check here for safety).
//
//  4. RouteInfo metadata is attached to each rule as a private attribute so
//     that downstream analysis tools can read route patterns without parsing
//     file names again.
//
//  5. A comment block is added to ts_compile rules inside the routes/ tree
//     documenting the route pattern, so the generated BUILD file is
//     self-documenting.
func adjustRouteRules(args language.GenerateArgs, result language.GenerateResult) language.GenerateResult {
	info := buildRouteInfo(args)

	for _, r := range result.Gen {
		if r.Kind() != "ts_compile" {
			continue
		}

		// Remove any accidentally included generated files from srcs.
		removeGeneratedFromSrcs(r)

		// Mark as a route target for downstream dep resolution.
		r.SetPrivateAttr(routeTargetKey, true)

		// Attach route info for analysis tools.
		r.SetPrivateAttr(routeInfoKey, info)

		// Add a route metadata comment to the rule so the BUILD file is
		// self-documenting.
		addRouteComment(r, info)

		if info.IsRootLayout {
			// Root layout: add shared components dep.
			addSharedComponentsDep(r)
		}
	}
	return result
}

// addRouteComment adds a comment to a ts_compile rule documenting the
// TanStack route pattern it represents. This makes generated BUILD files
// self-documenting, especially useful in large route trees.
//
// For root layouts:
//
//	# TanStack Start: root layout (wraps all routes)
//
// For index routes (pattern == "/"):
//
//	# TanStack Start route: / (index)
//
// For routes with dynamic segments:
//
//	# TanStack Start route: /users/:userId  [params: userId]
//
// For static routes:
//
//	# TanStack Start route: /about
func addRouteComment(r *rule.Rule, info RouteInfo) {
	var comment string
	switch {
	case info.IsRootLayout:
		comment = "# TanStack Start: root layout (wraps all routes)"
	case len(info.DynamicSegments) > 0:
		comment = "# TanStack Start route: " + info.RoutePattern +
			"  [params: " + strings.Join(info.DynamicSegments, ", ") + "]"
	case info.RoutePattern == "/":
		comment = "# TanStack Start route: / (index)"
	default:
		comment = "# TanStack Start route: " + info.RoutePattern
	}

	r.AddComment(comment)
}

// removeGeneratedFromSrcs removes generated files (*.gen.ts, *.gen.tsx) from
// the srcs attribute of a rule as a safety net.
func removeGeneratedFromSrcs(r *rule.Rule) {
	srcs := r.AttrStrings("srcs")
	if len(srcs) == 0 {
		return
	}

	var filtered []string
	for _, s := range srcs {
		// Drop the well-known generated file and any *.gen.ts/*.gen.tsx files.
		if s == routeTreeGenFile {
			continue
		}
		base := strings.TrimSuffix(strings.TrimSuffix(s, ".tsx"), ".ts")
		if strings.HasSuffix(base, ".gen") {
			continue
		}
		filtered = append(filtered, s)
	}

	if len(filtered) != len(srcs) {
		r.SetAttr("srcs", filtered)
	}
}

// addSharedComponentsDep adds the shared components label to the deps of a
// root layout ts_compile rule, if it is not already present.
func addSharedComponentsDep(r *rule.Rule) {
	existing := r.AttrStrings("deps")
	for _, dep := range existing {
		if dep == sharedComponentsLabel {
			return
		}
	}
	r.SetAttr("deps", append(existing, sharedComponentsLabel))
}

// ---- route tree introspection (used by dep resolver) -----------------------

// IsRouteTarget returns true if the rule was tagged as a route target by
// AdjustGenerateResult.
func IsRouteTarget(r *rule.Rule) bool {
	v := r.PrivateAttr(routeTargetKey)
	if v == nil {
		return false
	}
	b, ok := v.(bool)
	return ok && b
}

// GetRouteInfo returns the RouteInfo attached to a rule by AdjustGenerateResult.
// The second return value is false when no RouteInfo is present (e.g. for rules
// outside the routes/ tree).
func GetRouteInfo(r *rule.Rule) (RouteInfo, bool) {
	v := r.PrivateAttr(routeInfoKey)
	if v == nil {
		return RouteInfo{}, false
	}
	info, ok := v.(RouteInfo)
	return info, ok
}

// NearestRoutesPackage returns the workspace-relative package path of the
// nearest ancestor "routes" directory for a given rel path.
// Returns "" if rel is not inside a routes tree.
func NearestRoutesPackage(rel string) string {
	parts := strings.Split(rel, "/")
	for i := len(parts) - 1; i >= 0; i-- {
		if parts[i] == routesDirName {
			return strings.Join(parts[:i+1], "/")
		}
	}
	return ""
}

// RoutePatternForFile derives the TanStack Router URL pattern for a single
// route file path relative to the workspace root. It is a convenience wrapper
// around routePatternFromRel for use in tests and external tooling.
//
// Example:
//
//	RoutePatternForFile("src/routes/users/$userId.tsx") → "/users/:userId"
func RoutePatternForFile(wsRelPath string) string {
	// Find the routes/ component and take everything after it.
	routesRel := ""
	parts := strings.Split(path.Clean(wsRelPath), "/")
	for i, p := range parts {
		if p == routesDirName {
			routesRel = strings.Join(parts[i+1:], "/")
			break
		}
	}
	if routesRel == "" {
		return ""
	}
	return routePatternFromRel(routesRel)
}
