load("//ts:defs.bzl", "ts_compile", "ts_test")

ts_compile(
    name = "shard",
    srcs = ["shard.ts"],
    emit = True,  # keep
    node_modules = "//tests/npm:node_modules",
    deps = ["@npm//:types_node"],
)

# keep
ts_test(
    name = "sharding_test",
    size = "small",
    srcs = [
        "alpha.test.ts",
        "bravo.test.ts",
        "charlie.test.ts",
        "delta.test.ts",
        "echo.test.ts",
        "foxtrot.test.ts",
    ],
    emit = True,  # keep
    node_modules = "//tests/npm:node_modules",
    runner = "//ts/runners:node_test",
    shard_count = 3,
    deps = [
        ":shard",
        "@npm//:types_node",
    ],
)
