load("@rules_go//go:def.bzl", "go_test")
load("//ts:defs.bzl", "css_module")

css_module(
    name = "scope_module_css",
    srcs = ["scope.module.css"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "css_module_scope_test",
    size = "small",
    srcs = ["css_module_scope_test.go"],
    data = [":scope_module_css"],
    deps = ["//tests/verify"],
)
