/**
 * Root route component — wraps the entire application.
 *
 * In TanStack Router, __root.tsx is the layout that wraps all routes.
 * The Outlet renders the matched child route's component.
 *
 * Note: routeTree.gen.ts is normally auto-generated by @tanstack/router-cli.
 * Since we define routes manually in src/lib/router.ts, this file shows the
 * pattern without the code-gen step.
 */

import type { ReactElement } from "react";
import { Outlet } from "@tanstack/react-router";
import { Layout } from "../components";

export function RootComponent(): ReactElement {
  return (
    <Layout>
      <Outlet />
    </Layout>
  );
}
