load("@rules_rs//rs:rust_binary.bzl", "rust_binary")
load("@rules_rs//rs:rust_test.bzl", "rust_test")

rust_binary(
    name = "oxc-bazel",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        "@rules_typescript_crates//:clap",
        "@rules_typescript_crates//:miette",
        "@rules_typescript_crates//:oxc_allocator",
        "@rules_typescript_crates//:oxc_codegen",
        "@rules_typescript_crates//:oxc_diagnostics",
        "@rules_typescript_crates//:oxc_isolated_declarations",
        "@rules_typescript_crates//:oxc_parser",
        "@rules_typescript_crates//:oxc_semantic",
        "@rules_typescript_crates//:oxc_span",
        "@rules_typescript_crates//:oxc_transformer",
        "@rules_typescript_crates//:rayon",
    ],
)

rust_test(
    name = "oxc-bazel_test",
    crate = ":oxc-bazel",
)
