#!/usr/bin/env bash
# test_vite_bundle.sh — Bootstrap test: production bundling with Vite from scratch.
#
# Verifies the end-to-end Vite bundling flow (lib mode):
#   1. Create a workspace with rules_typescript + npm extension.
#   2. Copy tests/npm/pnpm-lock.yaml (has vite 6.4.1).
#   3. Write a multi-package TypeScript project (lib + app).
#   4. Write a root BUILD.bazel with hand-authored node_modules, vite_bundler,
#      and ts_bundle targets (these are NOT generated by Gazelle).
#   5. Run Gazelle to generate BUILD files for the src/ packages.
#   6. Run `bazel build //:bundle` — verify the Vite bundle is produced.
#   7. Check the output .es.js bundle file exists.
#
# Note: ts_bundle, vite_bundler, and node_modules are hand-written in the root
# BUILD.bazel — this is the realistic pattern for production apps.

set -euo pipefail

# ---------------------------------------------------------------------------
# Avoid TEST_TMPDIR interference with nested Bazel.
# ---------------------------------------------------------------------------
unset TEST_TMPDIR

# ---------------------------------------------------------------------------
# Locate the rules_typescript checkout.
# ---------------------------------------------------------------------------
RULES_TS_ROOT=""

if [[ -n "${RULES_TYPESCRIPT_ROOT:-}" ]]; then
    RULES_TS_ROOT="$RULES_TYPESCRIPT_ROOT"
fi

if [[ -z "$RULES_TS_ROOT" && -f "$(pwd)/MODULE.bazel" ]]; then
    candidate="$(pwd)"
    if grep -q '"rules_typescript"' "$candidate/MODULE.bazel" 2>/dev/null; then
        RULES_TS_ROOT="$candidate"
    fi
fi

if [[ -z "$RULES_TS_ROOT" ]]; then
    dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    while [[ "$dir" != "/" ]]; do
        if [[ -f "$dir/MODULE.bazel" ]] && grep -q '"rules_typescript"' "$dir/MODULE.bazel" 2>/dev/null; then
            RULES_TS_ROOT="$dir"
            break
        fi
        dir="$(dirname "$dir")"
    done
fi

if [[ -z "$RULES_TS_ROOT" ]]; then
    echo "FAIL: cannot locate rules_typescript checkout" >&2
    echo "      Set RULES_TYPESCRIPT_ROOT or run from within the repo." >&2
    exit 1
fi

echo "INFO: rules_typescript root = $RULES_TS_ROOT"

NPM_LOCKFILE="$RULES_TS_ROOT/tests/npm/pnpm-lock.yaml"
if [[ ! -f "$NPM_LOCKFILE" ]]; then
    echo "FAIL: pnpm-lock.yaml not found at $NPM_LOCKFILE" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
pass() { echo "PASS: $*"; }
fail() { echo "FAIL: $*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Create isolated temp workspace
# ---------------------------------------------------------------------------
TMP_DIR="$(mktemp -d)"
OUTPUT_BASE="$(mktemp -d)"
cleanup() {
    chmod -R u+w "$OUTPUT_BASE" 2>/dev/null || true
    rm -rf "$TMP_DIR" "$OUTPUT_BASE"
}
trap cleanup EXIT

echo "INFO: workspace    = $TMP_DIR"
echo "INFO: output_base  = $OUTPUT_BASE"
cd "$TMP_DIR"

bazel_run() {
    bazel --output_base="$OUTPUT_BASE" "$@"
}

# ---------------------------------------------------------------------------
# Copy the lockfile from tests/npm/ — includes vite 6.4.1
# ---------------------------------------------------------------------------
cp "$NPM_LOCKFILE" pnpm-lock.yaml

# ---------------------------------------------------------------------------
# Write workspace files
# ---------------------------------------------------------------------------
cat > .bazelversion <<'EOF'
9.0.0
EOF

cat > WORKSPACE.bazel <<'EOF'
# Bzlmod only.
EOF

cat > .bazelrc <<'EOF'
# Bootstrap test workspace — no @rules_rust flags (internal to rules_typescript)
build --incompatible_strict_action_env
build --nolegacy_external_runfiles
build --output_groups=+_validation
test --test_output=errors
test --test_summary=terse
EOF

cat > MODULE.bazel <<EOF
"""Bootstrap test: production Vite bundling from scratch."""

module(
    name = "bootstrap_vite_bundle",
    version = "0.0.0",
    compatibility_level = 0,
)

bazel_dep(name = "rules_typescript", version = "0.0.0")
bazel_dep(name = "gazelle", version = "0.47.0")

local_path_override(
    module_name = "rules_typescript",
    path = "$RULES_TS_ROOT",
)

register_toolchains("@rules_typescript//ts/toolchain:all")

npm = use_extension("@rules_typescript//npm:extensions.bzl", "npm")
npm.translate_lock(pnpm_lock = "//:pnpm-lock.yaml")
use_repo(npm, "npm")
EOF

# Root BUILD.bazel: gazelle only.  The node_modules, vite_bundler, and
# ts_bundle targets all live in //tools/ so:
#  1. The node_modules tree artifact is at bazel-bin/tools/node_modules/
#     (physically named "node_modules") — no conflict with a workspace-root
#     node_modules/ directory, and Node.js ESM resolution works without any
#     symlink indirection.
#  2. The vite.config.mjs generated by ts_bundle is co-located with the
#     bundler's node_modules/ tree, so `import { defineConfig } from "vite"`
#     resolves correctly at config-load time.
cat > BUILD.bazel <<'EOF'
"""Root BUILD file."""

load("@gazelle//:def.bzl", "gazelle")

# gazelle:ts_package_boundary every-dir

gazelle(
    name = "gazelle",
    gazelle = "@rules_typescript//gazelle:gazelle_ts",
)
EOF

# tools/BUILD.bazel: node_modules + vite_bundler + ts_bundle.
# All bundler-related targets live in the same package so the generated
# vite.config.mjs is co-located with the node_modules/ tree artifact.
# This ensures `import { defineConfig } from "vite"` in the config resolves
# correctly at Vite config-load time.
mkdir -p tools
cat > tools/BUILD.bazel <<'EOF'
"""tools BUILD file — vite bundler wiring and bundle target."""

load("@rules_typescript//npm:defs.bzl", "node_modules")
load("@rules_typescript//ts:defs.bzl", "ts_bundle")
load("@rules_typescript//vite:bundler.bzl", "vite_bundler")

# Collect vite and its transitive deps into a node_modules tree artifact.
# Named "node_modules" so Node.js ESM resolution finds vite's transitive deps
# (picomatch, rollup, esbuild, etc.) by walking up the directory tree.
node_modules(
    name = "node_modules",
    deps = ["@npm//:vite"],
)

# Wire Vite into the ts_bundle bundler interface.
vite_bundler(
    name = "vite",
    vite = "@npm//:vite",
    node_modules = ":node_modules",
)

# Produce the bundled output (lib mode — single .es.js file).
# The entry_point is a cross-package reference to the Gazelle-generated
# ts_compile target in src/app/.
ts_bundle(
    name = "bundle",
    entry_point = "//src/app",
    bundler = ":vite",
    format = "esm",
    sourcemap = False,
    minify = False,
)
EOF

# ---------------------------------------------------------------------------
# Write TypeScript sources
# ---------------------------------------------------------------------------
mkdir -p src/lib src/app

# src/lib/math.ts — pure arithmetic library with explicit return types.
cat > src/lib/math.ts <<'EOF'
/**
 * Pure arithmetic helpers with explicit return types (isolated declarations).
 */
export function add(a: number, b: number): number {
  return a + b;
}

export function multiply(a: number, b: number): number {
  return a * b;
}

export function subtract(a: number, b: number): number {
  return a - b;
}

export function square(n: number): number {
  return n * n;
}
EOF

cat > src/lib/index.ts <<'EOF'
export { add, multiply, subtract, square } from "./math";
EOF

# src/app/index.ts — imports from lib, explicit return types.
cat > src/app/index.ts <<'EOF'
import { add, multiply, square } from "../lib";

export function compute(x: number, y: number): string {
  const sum: number = add(x, y);
  const product: number = multiply(x, y);
  const xSquared: number = square(x);
  return `${x} + ${y} = ${sum}, ${x} * ${y} = ${product}, ${x}^2 = ${xSquared}`;
}

export function main(): void {
  console.log(compute(3, 4));
}
EOF

# ---------------------------------------------------------------------------
# Step 1: run Gazelle to generate BUILD files for src/
# ---------------------------------------------------------------------------
echo "INFO: running gazelle..."
if ! bazel_run run //:gazelle 2>&1; then
    fail "bazel run //:gazelle exited non-zero"
fi
pass "bazel run //:gazelle"

# Verify Gazelle generated BUILD files
for dir in src/lib src/app; do
    if [[ ! -f "$dir/BUILD.bazel" ]]; then
        fail "Gazelle did not generate $dir/BUILD.bazel"
    fi
    pass "$dir/BUILD.bazel generated"
done

# ---------------------------------------------------------------------------
# Step 2: build the bundle
# ---------------------------------------------------------------------------
echo "INFO: running bazel build //tools:bundle..."
if ! bazel_run build //tools:bundle 2>&1; then
    fail "bazel build //tools:bundle exited non-zero"
fi
pass "bazel build //tools:bundle"

# ---------------------------------------------------------------------------
# Step 3: verify the bundle output exists
# ---------------------------------------------------------------------------
BAZEL_BIN="$(bazel_run info bazel-bin 2>/dev/null)"

# In Vite lib mode with format=esm, the output is:
#   <package>/<name>_bundle/<bundle_filename>.es.js
# bundle_name defaults to the rule name ("bundle"), format suffix for esm is "es".
# The bundle target lives in //tools, so the path is tools/bundle_bundle/bundle.es.js.
BUNDLE_DIR="$BAZEL_BIN/tools/bundle_bundle"
BUNDLE_JS="$BUNDLE_DIR/bundle.es.js"

if [[ ! -d "$BUNDLE_DIR" ]]; then
    fail "expected bundle directory not found: $BUNDLE_DIR"
fi
pass "bundle directory exists: tools/bundle_bundle/"

if [[ ! -f "$BUNDLE_JS" ]]; then
    fail "expected bundle file not found: $BUNDLE_JS"
fi
pass "bundle file exists: tools/bundle_bundle/bundle.es.js"

# Verify the bundle file is non-empty and looks like JavaScript.
BUNDLE_SIZE=$(wc -c < "$BUNDLE_JS")
if [[ "$BUNDLE_SIZE" -lt 50 ]]; then
    fail "bundle file is suspiciously small ($BUNDLE_SIZE bytes)"
fi
pass "bundle file is non-trivially sized ($BUNDLE_SIZE bytes)"

# Verify the bundle contains expected function names from our source.
if ! grep -q "add\|multiply\|compute" "$BUNDLE_JS"; then
    fail "bundle does not appear to contain expected function content"
fi
pass "bundle contains expected function content"

echo "ALL PASSED"
