load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

# gazelle:ignore
# gazelle:exclude testdata

go_library(
    name = "tsaction_lib",
    srcs = [
        "check.go",
        "emit.go",
        "main.go",
        "manifest.go",
        "paths.go",
        "showconfig.go",
        "tsgo.go",
    ],
    importpath = "github.com/mikn/rules_typescript/ts/tools/tsaction",
    visibility = ["//visibility:private"],
    deps = [
        "//ts/tools/explainfiles",
        "//ts/tools/tsconfig",
    ],
)

go_binary(
    name = "tsaction",
    embed = [":tsaction_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "tsaction_test",
    size = "small",
    srcs = [
        "check_test.go",
        "emit_test.go",
        "manifest_test.go",
        "paths_test.go",
        "showconfig_test.go",
        "tsgo_test.go",
    ],
    data = glob(["testdata/**"]),
    embed = [":tsaction_lib"],
)
