#!/usr/bin/env bash
# --- begin runfiles.bash initialization v3 ---
# Copy-pasted from the Bazel Bash runfiles library v3.
set -uo pipefail; set +e; f=bazel_tools/tools/bash/runfiles/runfiles.bash
# shellcheck disable=SC1090
source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d' ')" 2>/dev/null || \
  source "$0.runfiles/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.exe.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
  { echo>&2 "ERROR: cannot find $f"; exit 1; }; f=; set -e
# --- end runfiles.bash initialization v3 ---

# Adds npm packages via hermetic pnpm, appending --lockfile-only so pnpm
# updates pnpm-lock.yaml without creating a node_modules directory.
#
# Usage (via Bazel):
#   bazel run //:add_package -- zod
#   bazel run //:add_package -- -D typescript
#   bazel run //:add_package -- react react-dom

if [[ -z "${BUILD_WORKSPACE_DIRECTORY:-}" ]]; then
  echo "ERROR: BUILD_WORKSPACE_DIRECTORY is not set." >&2
  echo "This script must be run via 'bazel run', not invoked directly." >&2
  exit 1
fi

if [[ -z "${PNPM_BIN:-}" ]]; then
  echo "ERROR: PNPM_BIN is not set. Was this target generated by ts_add_package()?" >&2
  exit 1
fi

pnpm_bin="$(rlocation "${PNPM_BIN}")" || pnpm_bin=""
if [[ ! -x "${pnpm_bin}" ]]; then
  echo "ERROR: Cannot locate pnpm binary in runfiles." >&2
  echo "  PNPM_BIN=${PNPM_BIN}" >&2
  echo "  rlocation returned: ${pnpm_bin:-<nothing>}" >&2
  exit 1
fi

cd "${BUILD_WORKSPACE_DIRECTORY}"
exec "${pnpm_bin}" add "$@" --lockfile-only
