#!/usr/bin/env bash
# --- begin runfiles.bash initialization v3 ---
# Copy-pasted from the Bazel Bash runfiles library v3.
set -uo pipefail; set +e; f=bazel_tools/tools/bash/runfiles/runfiles.bash
# shellcheck disable=SC1090
source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d' ')" 2>/dev/null || \
  source "$0.runfiles/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.exe.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
  { echo>&2 "ERROR: cannot find $f"; exit 1; }; f=; set -e
# --- end runfiles.bash initialization v3 ---

# Adds npm packages to one npm hub via hermetic pnpm. PNPM_HUB_DIR is the
# workspace-relative directory of that hub's lockfile, injected by
# ts_add_package(); --lockfile-only keeps pnpm from creating a node_modules
# directory.
#
# Usage (via Bazel):
#   bazel run //:add_package -- zod
#   bazel run //:add_package -- -D typescript
#   bazel run //:add_package -- react react-dom

if [[ -z "${BUILD_WORKSPACE_DIRECTORY:-}" ]]; then
  echo "ERROR: BUILD_WORKSPACE_DIRECTORY is not set." >&2
  echo "This script must be run via 'bazel run', not invoked directly." >&2
  exit 1
fi

if [[ -z "${PNPM_BIN:-}" ]]; then
  echo "ERROR: PNPM_BIN is not set. Was this target generated by ts_add_package()?" >&2
  exit 1
fi

if [[ -z "${PNPM_HUB_DIR:-}" ]]; then
  echo "ERROR: PNPM_HUB_DIR is not set. Was this target generated by ts_add_package()?" >&2
  echo "Without it pnpm would write a package.json and pnpm-lock.yaml at the" >&2
  echo "workspace root instead of into a hub." >&2
  exit 1
fi

hub_dir="${BUILD_WORKSPACE_DIRECTORY}/${PNPM_HUB_DIR}"
if [[ ! -f "${hub_dir}/package.json" ]]; then
  echo "ERROR: ${PNPM_HUB_DIR}/package.json does not exist, so pnpm would create one." >&2
  echo "PNPM_HUB_DIR comes from the pnpm_lock label on this target; point it at the" >&2
  echo "lockfile of a hub that has a package.json beside it." >&2
  exit 1
fi

pnpm_bin="$(rlocation "${PNPM_BIN}")" || pnpm_bin=""
if [[ ! -x "${pnpm_bin}" ]]; then
  echo "ERROR: Cannot locate pnpm binary in runfiles." >&2
  echo "  PNPM_BIN=${PNPM_BIN}" >&2
  echo "  rlocation returned: ${pnpm_bin:-<nothing>}" >&2
  exit 1
fi

cd "${BUILD_WORKSPACE_DIRECTORY}"
exec "${pnpm_bin}" add "$@" --lockfile-only --dir "${PNPM_HUB_DIR}"
