#!/usr/bin/env bash
# Convenience wrapper for adding npm packages via hermetic pnpm.
# Automatically appends --lockfile-only so pnpm updates pnpm-lock.yaml
# without creating a node_modules directory in the workspace.
#
# Usage (via Bazel):
#   bazel run //:add_package -- <package> [flags]
#
# Examples:
#   bazel run //:add_package -- zod
#   bazel run //:add_package -- -D typescript
#   bazel run //:add_package -- react react-dom

set -euo pipefail

if [[ -z "${BUILD_WORKSPACE_DIRECTORY:-}" ]]; then
  echo "ERROR: BUILD_WORKSPACE_DIRECTORY is not set." >&2
  echo "This script must be run via 'bazel run', not invoked directly." >&2
  exit 1
fi

if [[ -z "${PNPM_BIN:-}" ]]; then
  echo "ERROR: PNPM_BIN is not set. Was this target generated by ts_add_package()?" >&2
  exit 1
fi

if [[ "${0}" == /* ]]; then
  binary_dir="$(dirname "${0}")"
  binary_name="$(basename "${0}")"
else
  binary_dir="$(cd "$(dirname "${0}")" && pwd)"
  binary_name="$(basename "${0}")"
fi

runfiles_dir="${binary_dir}/${binary_name}.runfiles"

pnpm_rloc="${PNPM_BIN#../}"
pnpm_bin="${runfiles_dir}/${pnpm_rloc}"

if [[ ! -x "${pnpm_bin}" ]]; then
  if [[ -n "${RUNFILES_DIR:-}" ]]; then
    pnpm_bin="${RUNFILES_DIR}/${pnpm_rloc}"
  fi
fi

if [[ ! -x "${pnpm_bin}" ]]; then
  echo "ERROR: Cannot locate pnpm binary." >&2
  echo "  Looked at: ${runfiles_dir}/${pnpm_rloc}" >&2
  echo "  PNPM_BIN=${PNPM_BIN}" >&2
  exit 1
fi

cd "${BUILD_WORKSPACE_DIRECTORY}"
exec "${pnpm_bin}" add "$@" --lockfile-only
