#!/usr/bin/env bash
# Hermetic pnpm wrapper.
# Executes pnpm in the Bazel workspace source root ($BUILD_WORKSPACE_DIRECTORY)
# so that package.json and pnpm-lock.yaml are read from and written to the
# source tree, not the sandbox.
#
# Usage (via Bazel):
#   bazel run //:pnpm -- <pnpm args>
#
# Examples:
#   bazel run //:pnpm -- --version
#   bazel run //:pnpm -- add zod --lockfile-only
#   bazel run //:pnpm -- install --frozen-lockfile

set -euo pipefail

# $BUILD_WORKSPACE_DIRECTORY is set by Bazel when running a target with
# `bazel run`. It points to the root of the source workspace.
if [[ -z "${BUILD_WORKSPACE_DIRECTORY:-}" ]]; then
  echo "ERROR: BUILD_WORKSPACE_DIRECTORY is not set." >&2
  echo "This script must be run via 'bazel run', not invoked directly." >&2
  exit 1
fi

# $PNPM_BIN is injected by ts_pnpm() via env = { "PNPM_BIN": "$(rootpath ...)" }.
# $(rootpath) expands to the rlocation path of the pnpm binary, e.g.:
#   ../+npm+pnpm/linux_amd64/pnpm
if [[ -z "${PNPM_BIN:-}" ]]; then
  echo "ERROR: PNPM_BIN is not set. Was this target generated by ts_pnpm()?" >&2
  exit 1
fi

# Resolve the runfiles directory.
# rules_shell sh_binary places <binary>.runfiles/ next to the binary.
# $0 is the invocation path (e.g. bazel-out/.../bin/pnpm, a symlink to this
# script). We must NOT follow the symlink — we need the directory of the
# symlink itself, not the symlink's target.
#
# Determine the location of this binary in the Bazel output tree.
# If run via `bazel run`, $0 is an absolute path to the binary. The runfiles
# are located alongside it as <binary>.runfiles/.
if [[ "${0}" == /* ]]; then
  # $0 is absolute: use it directly.
  binary_dir="$(dirname "${0}")"
  binary_name="$(basename "${0}")"
else
  # $0 is relative: make it absolute relative to cwd.
  binary_dir="$(cd "$(dirname "${0}")" && pwd)"
  binary_name="$(basename "${0}")"
fi

runfiles_dir="${binary_dir}/${binary_name}.runfiles"

# Strip the leading "../" from the rlocation path.
# External repo rlocation format: "../<repo>/<path>" → "<repo>/<path>"
pnpm_rloc="${PNPM_BIN#../}"
pnpm_bin="${runfiles_dir}/${pnpm_rloc}"

if [[ ! -x "${pnpm_bin}" ]]; then
  # Fallback: try RUNFILES_DIR if provided by the environment.
  if [[ -n "${RUNFILES_DIR:-}" ]]; then
    pnpm_bin="${RUNFILES_DIR}/${pnpm_rloc}"
  fi
fi

if [[ ! -x "${pnpm_bin}" ]]; then
  echo "ERROR: Cannot locate pnpm binary." >&2
  echo "  Looked at: ${runfiles_dir}/${pnpm_rloc}" >&2
  echo "  PNPM_BIN=${PNPM_BIN}" >&2
  exit 1
fi

cd "${BUILD_WORKSPACE_DIRECTORY}"
exec "${pnpm_bin}" "$@"
