#!/usr/bin/env bash
# Renders oxc_cli/crates under RULES_RUST_FLOOR, the oldest rules_rust a
# consumer may hold (CONTRIBUTING.md § Vendoring the crates).
set -euo pipefail

RULES_RUST_FLOOR=0.70.0
FLOOR_SHA256=5ffd9ff1f6f2f14f2057b7cbaa91a5e6acd9a4cbded5ac81dad9beb36859601e

cd "$(git rev-parse --show-toplevel)"
# Under the workspace, not /tmp: the sandbox mounts an empty /tmp of its own.
dir="$PWD/.bazel/vendor_crates"
rm -rf "$dir"
mkdir -p "$dir/rules_rust"
trap 'rm -rf "$dir"' EXIT

release="https://github.com/bazelbuild/rules_rust/releases/download"
curl -fsSL -o "$dir/rules_rust.tar.gz" \
  "$release/$RULES_RUST_FLOOR/rules_rust-$RULES_RUST_FLOOR.tar.gz"
echo "$FLOOR_SHA256  $dir/rules_rust.tar.gz" | sha256sum -c --quiet
tar -xzf "$dir/rules_rust.tar.gz" -C "$dir/rules_rust"

"${BAZEL:-bazel}" run --lockfile_mode=off \
  --override_module="rules_rust=$dir/rules_rust" //oxc_cli:crates_vendor "$@"
rm oxc_cli/crates/crates.bzl oxc_cli/crates/alias_rules.bzl
sed '/^        "cargo-bazel[.]json",$/d; /^        "crates[.]bzl",$/d' \
  oxc_cli/crates/BUILD.bazel > "$dir/BUILD.bazel"
mv "$dir/BUILD.bazel" oxc_cli/crates/BUILD.bazel

# cargo-bazel 0.70.0 emits documentation excluded by the comment policy.
mkdir -p "$dir/normalized"
: > "$dir/defs-comments"
for file in oxc_cli/crates/BUILD*.bazel oxc_cli/crates/defs.bzl; do
  awk -v removed="$dir/defs-comments" '
    BEGIN {
      split("###############################################################################\n" \
        "# @generated\n" \
        "# DO NOT MODIFY: This file is auto-generated by a crate_universe tool. To\n" \
        "# regenerate this file, run the following:\n#\n" \
        "#     tools/vendor_crates.sh\n" \
        "###############################################################################", header, "\n")
    }
    function discard() {
      if (FILENAME ~ /\/defs[.]bzl$/) print $0 >> removed
    }
    FNR <= 7 {
      if ($0 != header[FNR]) exit 1
      discard()
      next
    }
    FILENAME ~ /\/defs[.]bzl$/ {
      if (/^[ ]*"""/) {
        doc = !doc
        discard()
        next
      }
      if (doc || /^[ ]*#/) { discard(); next }
    }
    $0 == "# Workspace Member Dependencies" { next }
    /^[ ]*"[^"\\#]*"([ ]*:[ ]*"[^"\\#]*")?,  # (cfg[(]|[a-z0-9_]+-)/ {
      sub(/  # .*/, "")
    }
    /^[[:space:]]*$/ { blank = 1; next }
    {
      if (blank && previous != "" && previous !~ /:$/) print ""
      print
      blank = 0
      previous = $0
    }
    END { if (doc || FNR < 7) exit 1 }
  ' "$file" > "$dir/normalized/${file##*/}" || {
    echo >&2 "cargo-bazel template changed; review comment normalization"
    exit 1
  }
done
defs_comments=c4a301f2fc4b3a53cfa1c424af4fe623c1b05768e1afb9a509f1062bb00a3224
echo "$defs_comments  $dir/defs-comments" | sha256sum -c --quiet || {
  echo >&2 "cargo-bazel defs documentation changed; review normalization"
  exit 1
}
for file in "$dir/normalized/"*; do
  mv "$file" "oxc_cli/crates/${file##*/}"
done
