load("@rules_typescript//ts:defs.bzl", "ts_compile", "ts_config", "ts_test")

ts_compile(
    name = "lib",
    srcs = [
        "index.ts",
        "math.ts",
    ],
    emit = True,  # keep
    node_modules = "//:node_modules",
    tsconfig = ":tsconfig",
    visibility = ["//visibility:public"],
)

ts_test(
    name = "lib_test",
    srcs = ["math.test.ts"],
    emit = True,  # keep
    node_modules = "//:node_modules",
    tsconfig = ":tsconfig",
    deps = [
        ":lib",
        "@npm//:vite",
        "@npm//:vitest",
    ],
)

ts_config(
    name = "tsconfig",
    src = "tsconfig.json",
    visibility = ["//visibility:public"],
    deps = ["//:tsconfig"],
)
