load("//ts:defs.bzl", "ts_compile")

# gazelle:ignore

ts_compile(
    name = "wrapper",
    srcs = ["index.ts"],
    emit = True,  # keep
    node_modules = "//tests/source_mode:node_modules",
    package_scopes = ["package.json"],
    visibility = ["//tests/source_mode:__pkg__"],
    deps = ["//tests/source_mode:node_modules/native-source-fixture"],
)
