// Tailwind v4 through the bundler: the plugin has to run, and the native engine
// it drives has to be the one this host can load.
//
// Nothing in this package declares the utility classes index.html and entry.ts
// name. A rule for them in the emitted CSS can therefore only have been
// generated by @tailwindcss/oxide, which is a platform-specific native module
// the lockfile carries thirteen builds of -- so a rule in the output is also the
// assertion that the npm tree placed the right one of them.
package tailwind_test

import (
	"testing"

	"github.com/mikn/rules_typescript/tests/verify"
)

// Lib mode puts every extracted rule in one stylesheet and never references it
// from the JS, so nothing about the .js output implies it exists. It survives
// only because ts_bundle declares it -- an undeclared output is discarded with
// the sandbox, which is what made this look like "Vite drops CSS in lib mode".
func TestLibModeEmitsItsStylesheet(t *testing.T) {
	css := verify.New(t).File("tests/tailwind/lib_bundle/lib.css")
	css.Contains("display: flex", "align-items: center")
}

func TestTailwindGeneratesUtilitiesFromScannedSource(t *testing.T) {
	assets := verify.New(t).Dir("tests/tailwind/app_bundle/assets")
	// What `flex` and `items-center` compile to. Asserting the compiled
	// declaration rather than the class name keeps this about Tailwind having
	// run, not about the string surviving into some file.
	assets.AnyContains("*.css", "display: flex")
	assets.AnyContains("*.css", "align-items: center")
}
