// Tailwind v4 under the dev server, which is a different resolution problem from
// Tailwind under the bundler.
//
// `@import "tailwindcss"` is resolved from the CSS file's own directory by
// @tailwindcss/node, using enhanced-resolve rather than Node's own resolver. In
// dev the stylesheet is served from the source tree, which has no node_modules
// above it to walk up to, so the import resolves nowhere and the dev server
// answers 500 for that file -- a green `bazel build` and an unstyled page.
// enhanced-resolve reads NODE_PATH, which is why the launcher sets it.
package tailwind_test

import (
	"io"
	"net"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/mikn/rules_typescript/tests/verify"
)

func TestDevServerServesGeneratedTailwindCss(t *testing.T) {
	tree := verify.New(t)
	target := os.Getenv("DEV_TARGET")
	if target == "" {
		t.Fatal("DEV_TARGET is unset; the lane does not know which server to start")
	}
	launcher := tree.File("tests/tailwind/" + target + "_launcher")
	if !launcher.Exists() {
		t.FailNow()
	}

	port := freePort(t)
	ws := t.TempDir()
	logPath := filepath.Join(ws, "server.log")
	logFile, err := os.Create(logPath)
	if err != nil {
		t.Fatalf("create %s: %v", logPath, err)
	}
	defer logFile.Close()

	// Its own workspace, the same shape //tests/dev_server uses: the server serves
	// from here, and these are the files Tailwind has to scan. Serving the runfiles
	// tree instead lets Vite's static middleware answer the .css from disk without
	// running the plugin at all, which passes for the wrong reason.
	root := filepath.Join(ws, "workspace")
	mustMkdir(t, filepath.Join(root, "tests", "tailwind"))
	mustWrite(t, filepath.Join(root, "tests", "tailwind", "styles.css"),
		"@import \"tailwindcss\";\n@source \"./entry.js\";\n")
	// The compiled entry, as Bazel would have produced it. These class names exist
	// nowhere else, so a rule for them can only come from scanning this file.
	mustWrite(t, filepath.Join(root, "tests", "tailwind", "entry.js"),
		"export const classes = \"flex items-center gap-4\";\n")

	cmd := exec.Command(launcher.Abs(), "--port", strconv.Itoa(port))
	cmd.Dir = root
	cmd.Stdout = logFile
	cmd.Stderr = logFile
	cmd.Env = append(os.Environ(),
		"RUNFILES_DIR="+os.Getenv("RUNFILES_DIR"),
		"BUILD_WORKSPACE_DIRECTORY="+root,
	)
	if err := cmd.Start(); err != nil {
		t.Fatalf("start the dev server: %v", err)
	}
	t.Cleanup(func() {
		if cmd.Process != nil {
			_ = cmd.Process.Kill()
		}
		_, _ = cmd.Process.Wait()
	})

	base := "http://localhost:" + strconv.Itoa(port)
	url := base + "/tests/tailwind/styles.css"
	var body string
	var status int
	deadline := time.Now().Add(90 * time.Second)
	for time.Now().Before(deadline) {
		resp, err := (&http.Client{Timeout: 10 * time.Second}).Get(url)
		if err == nil {
			b, _ := io.ReadAll(resp.Body)
			resp.Body.Close()
			status, body = resp.StatusCode, string(b)
			// 500 is the failure this test exists for, and it is reported rather
			// than retried: the stylesheet does not become resolvable by waiting.
			if status != 0 {
				break
			}
		}
		time.Sleep(500 * time.Millisecond)
	}

	log, _ := os.ReadFile(logPath)
	if status != 200 {
		t.Fatalf("GET %s returned %d, want 200\nbody:\n%s\n--- server log ---\n%s",
			url, status, body, log)
	}
	// The compiled entry.js names these; nothing declares them, so a rule for
	// them can only have been generated by scanning it.
	for _, want := range []string{"display: flex", "align-items: center"} {
		if !strings.Contains(body, want) {
			t.Errorf("the served stylesheet has no %q, so Tailwind generated nothing "+
				"from the scanned source\nbody:\n%s\n--- server log ---\n%s",
				want, body, log)
		}
	}
}

func freePort(t *testing.T) int {
	t.Helper()
	l, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("reserve a port: %v", err)
	}
	defer l.Close()
	return l.Addr().(*net.TCPAddr).Port
}

func mustMkdir(t *testing.T, dir string) {
	t.Helper()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("mkdir %s: %v", dir, err)
	}
}

func mustWrite(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}
