"""Per-resolution npm repositories: one external repo per snapshot, plus an alias hub.

Why this shape rather than one big repo
---------------------------------------
A single repository holding every package has to download and extract all of
them before it can generate any BUILD file, because it reads `bin` and `exports`
out of each extracted `package.json`. On a real 2731-package lockfile that is
~5 minutes and ~5 GB, paid in full even by a target whose only npm dependency is
vitest, in one serial Starlark loop with no resume: a single bad tarball restarts
everything.

The unit is one pnpm SNAPSHOT -- a package as resolved for one peer set -- not
one `name@version`. pnpm resolves a package once per distinct peer set and gives
each outcome its own dependency edges, so two snapshots can share a tarball and
disagree about what they depend on.

Here each snapshot is its own repository rule, so it reads its OWN package.json
and writes its OWN BUILD file. Bazel then fetches repositories on demand, which
gives four things the monolith cannot:

  - Laziness. Only packages in the requested targets' transitive closure are
    fetched. `@npm//:vitest` pulls vitest's subtree, not the lockfile.
  - Parallelism. Bazel fetches independent repositories concurrently instead of
    looping in Starlark.
  - Per-package caching and invalidation. Bumping one package invalidates one
    repository, not all of them.
  - Isolated failure. A malformed tarball fails its own package.

`npm_hub` is the stable label surface. Its root package is the whole-lockfile
namespace (`@npm//:zod`, `@npm//:types_react`, `@npm//:vitest_bin`), and it holds
one further package per workspace member (`@npm//apps/web:react`) carrying that
member's own resolution -- which the root package cannot, because a Bazel package
has one namespace and two members can resolve one name differently. It contains
only `alias` targets and downloads nothing, so it is cheap to regenerate whenever
the lockfile changes. Repositories created by one module extension can reference
each other by apparent name, which is what lets the hub point at spokes without
constructing canonical repo names.

What still lives in the extension, not here
-------------------------------------------
The extension parses the lockfile once (no network) and hands each spoke a
resolved, ACYCLIC dependency list. Cycle breaking cannot move into the spokes:
npm has genuine circular peer dependencies, Bazel target graphs may not cycle,
and a spoke only knows about itself. Multi-version label assignment and @types
pairing stay there for the same reason -- they are whole-graph decisions.

Platform is the exception that does NOT get decided there. Which platforms a
tarball is built for is whole-graph knowledge, but which of them applies is a
property of the build, so the extension partitions the dep lists and the spoke
emits a select(). Deciding it in the extension would mean reading the host, and
the extension's result is recorded in MODULE.bazel.lock -- a committed file.
"""

_NPM_BUILD_HEADER = '''# Generated by npm_import. Do not edit.
load("@rules_typescript//ts/private:ts_npm_package.bzl", "ts_npm_package")
'''

def _tarball_prefix(rctx, staging):
    """Returns the archive's single top-level directory, or "" if it has none.

    npm tarballs conventionally extract under `package/`, but DefinitelyTyped
    ships `<name>/` and some ship `<name> v<major>.<minor>/`. Predicting the
    prefix from the package name means maintaining a table of exceptions, and a
    miss is not a warning -- it aborts the fetch, uncatchably. So the archive
    itself decides, by being extracted and listed. `watch = "no"` because the
    listing is of a path inside the repository being fetched, which can never be
    an input to that fetch.
    """
    entries = rctx.path(staging).readdir(watch = "no")
    if len(entries) == 1 and entries[0].is_dir:
        return entries[0].basename

    names = sorted([entry.basename for entry in entries])
    if "package.json" in names:
        return ""
    fail(
        "npm: the tarball for {} at {} is not shaped like an npm package: npm ".format(
            rctx.attr.package,
            rctx.attr.url,
        ) +
        "puts everything under one top-level directory, and this archive's top " +
        "level is [{}] with no package.json among it.\n".format(", ".join(names)) +
        "Check that the url resolves to a published npm tarball rather than a " +
        "git archive or a registry error page, then re-run `pnpm install` so the " +
        "lockfile records the registry's own resolution.",
    )

def _expand_env(value, getenv):
    """Substitutes ${VAR} from the fetch environment, the way npm does.

    This is the supported way to keep a token out of the workspace: the .npmrc
    that Bazel tracks names an environment variable, and the value only ever
    exists inside one fetch. rctx.getenv registers the variable, so changing it
    refetches.
    """
    out = ""
    rest = value
    for _ in range(16):
        start = rest.find("${")
        if start == -1:
            break
        end = rest.find("}", start)
        if end == -1:
            break
        out += rest[:start] + getenv(rest[start + 2:end], "")
        rest = rest[end + 1:]
    return out + rest

def _auth_scope(url):
    """The `//host/path/` form npm keys credentials by, for a URL or an .npmrc key."""
    for scheme in ("https://", "http://"):
        if url.startswith(scheme):
            url = url[len(scheme):]
            break
    if not url.startswith("//"):
        url = "//" + url
    return url if url.endswith("/") else url + "/"

def _npmrc_auth_fields(content, url):
    """The credential fields of the .npmrc scope that best matches a URL.

    npm keys credentials by `//host/path/` and applies the LONGEST matching
    prefix, so a registry mounted on a path (an Artifactory repo, say) carries its
    own token without claiming the whole host.

    Returns:
        (scope, {field: raw_value}) -- raw because ${VAR} is expanded by the
        caller, which is the only place the environment is available.
    """
    request_scope = _auth_scope(url)
    best_scope = ""
    fields = {}
    for raw in content.split("\n"):
        line = raw.strip()
        if not line or line.startswith("#") or line.startswith(";") or line.startswith("["):
            continue
        key, sep, value = line.partition("=")
        if not sep or not key.strip().startswith("//"):
            continue
        scope, _, field = key.strip().rpartition(":")
        scope = _auth_scope(scope)
        if not request_scope.startswith(scope) or len(scope) < len(best_scope):
            continue
        if scope != best_scope:
            best_scope = scope
            fields = {}
        fields[field] = value.strip().strip("'\"")
    return (best_scope, fields)

def _npmrc_auth(content, url, getenv, npmrc_label = ".npmrc"):
    """The `auth` dict rctx.download needs for one tarball URL, or {}.

    Built at fetch time, never in the module extension: an extension's result is
    serialised into MODULE.bazel.lock, a committed file, and a repository rule's
    attribute values go into it verbatim. What this repository records is the
    .npmrc's label; the token exists only for the duration of the fetch.
    """
    scope, fields = _npmrc_auth_fields(content, url)

    token = _expand_env(fields.get("_authToken", ""), getenv)
    if token:
        return {url: {"type": "pattern", "pattern": "Bearer <password>", "login": "", "password": token}}

    basic = _expand_env(fields.get("_auth", ""), getenv)
    if basic:
        return {url: {"type": "pattern", "pattern": "Basic <password>", "login": "", "password": basic}}

    if "_password" in fields:
        fail(
            "npm: {} configures `username`/`_password` for {}, which this ruleset ".format(
                npmrc_label,
                scope,
            ) +
            "cannot use: npm stores `_password` base64-encoded and Starlark has no way " +
            "to decode it (there is no chr()). Use `_authToken=` or `_auth=` instead -- " +
            "`npm config set //host/:_authToken` writes the first, and `_auth` is the " +
            "same base64 blob you already have.",
        )
    return {}

def _auth_for_fetch(rctx, url):
    if not rctx.attr.npmrc:
        return {}

    # An attr.label is not by itself an input to the fetch: without watching it,
    # rotating a token in .npmrc would leave the fetched repository in place.
    rctx.watch(rctx.attr.npmrc)
    return _npmrc_auth(rctx.read(rctx.attr.npmrc), url, rctx.getenv, str(rctx.attr.npmrc))

def _bin_entries(pkg_json):
    """Normalises package.json `bin` into {name: relative_path}.

    npm allows either a string (implying the package's own name) or a mapping.
    """
    raw = pkg_json.get("bin")
    if not raw:
        return {}
    if type(raw) == "string":
        name = pkg_json.get("name", "")
        if name.startswith("@") and "/" in name:
            name = name.split("/")[-1]
        return {name: raw} if name else {}
    if type(raw) == "dict":
        return {k: v for k, v in raw.items() if type(v) == "string"}
    return {}

_DECLARATION_EXTENSIONS = (".d.ts", ".d.mts", ".d.cts")

_JS_TO_DECLARATION = {".js": ".d.ts", ".mjs": ".d.mts", ".cjs": ".d.cts"}

# Conditions a declaration lookup descends into, matched against the exports
# map's own key order because that is the order a resolver tries them in. "node"
# is among them: without it a `{"node": ..., "default": ...}` package answers
# with the declarations of its browser build.
_TYPE_CONDITIONS = ("types", "typings", "node", "import", "require", "default")

_WALK_STEPS = 64

def _root_export(exports):
    """The `exports` subtree describing the package's own entry point, or None.

    A map with no subpath keys IS that subtree -- npm's shorthand for a package
    that exports nothing but itself.
    """
    if type(exports) == "string":
        return exports
    if type(exports) != "dict":
        return None
    if "." in exports:
        return exports["."]
    for key in exports.keys():
        if key.startswith("."):
            return None
    return exports

def _export_targets(root):
    """Every file exports["."] can designate, in the order a resolver tries them.

    Iterative because Starlark has no recursion. Children go to the front, so a
    condition's whole subtree is tried before the next condition is looked at,
    which is the order a resolver descends in.
    """
    pending = [root]
    targets = []
    for _ in range(_WALK_STEPS):
        if not pending:
            break
        node = pending.pop(0)
        kind = type(node)
        if kind == "string":
            targets.append(node)
        elif kind == "list":
            pending = list(node) + pending
        elif kind == "dict":
            pending = [node[key] for key in node.keys() if key in _TYPE_CONDITIONS] + pending
    return targets

def _declaration_at(target, has_file):
    """The declaration one exports target designates, if the package ships it."""
    path = target.removeprefix("./")
    if not path or "*" in path:
        return ""
    for extension in _DECLARATION_EXTENSIONS:
        if path.endswith(extension):
            return path if has_file(path) else ""
    for js, declaration in _JS_TO_DECLARATION.items():
        if path.endswith(js):
            beside = path[:-len(js)] + declaration
            return beside if has_file(beside) else ""
    return ""

def _declaration_field(value, has_file):
    """The declaration a `types`/`typings` field names, if the package ships it."""
    named = _declaration_at(value, has_file)
    if named:
        return named
    extended = value.removeprefix("./") + ".d.ts"
    return extended if has_file(extended) else ""

def _exports_types(pkg_json, has_file):
    """The .d.ts a package's own metadata designates as its entry point, or "".

    The order is every resolver's, TypeScript's included. `exports` first, in the
    key order the map itself is written in: a package that ships one has declared
    there which files it means to be entered through, conditions and all. Then
    `typings` and `types`, in that order because readPackageJsonTypesFields reads
    them in it, which is where a package with no `exports`, or one whose `exports`
    names no declarations, publishes them -- most of npm.

    So the exports map is authoritative about what it designates and silent about
    the rest, and this reads it that way rather than treating the silence as an
    answer. Every candidate is checked against the extracted package, because a
    manifest that names a declaration it does not ship would otherwise become a
    target with a missing source.

    Args:
        pkg_json: The package's decoded package.json.
        has_file: Predicate on a package-relative path.
    """
    for target in _export_targets(_root_export(pkg_json.get("exports"))):
        designated = _declaration_at(target, has_file)
        if designated:
            return designated
    for field in ("typings", "types"):
        value = pkg_json.get(field)
        if type(value) == "string":
            named = _declaration_field(value, has_file)
            if named:
                return named

    # A manifest that designates nothing has not said there are no declarations.
    # TypeScript's own resolution ends at <pkg>/index.d.ts, and a types-only
    # package can therefore ship one and no `types` field at all --
    # @cloudflare/workers-types is exactly that. Without this, asking for it in
    # compilerOptions.types resolves to nothing and its globals never join the
    # program, which no error mentions.
    return "index.d.ts" if has_file("index.d.ts") else ""

def _exports_subpath_types(pkg_json, has_file):
    """The declaration each non-root `exports` subpath designates, keyed by subpath.

    The root entry is `_exports_types`' business; this is every other subpath,
    which is where a package puts declarations that are not its entry point.
    Ambient module declarations in particular: a package cannot put
    `declare module "cloudflare:test"` in its entry point without forcing it on
    every importer, so it ships a subpath nothing imports and the consumer names
    that subpath instead.

    tsconfig `types` cannot reach one of those under Bazel. TypeScript resolves a
    `types` entry by walking node_modules for the package and reading its
    manifest, and this ruleset has no node_modules to walk -- npm packages reach
    the compiler through `paths`, which `types` does not consult. So the subpath
    is resolved here, where the manifest is, and the file it names is put in the
    consumer's `files`.

    A subpath with a wildcard is skipped: it designates a pattern rather than a
    file, and `_declaration_at` cannot name one.
    """
    exports = pkg_json.get("exports")
    if type(exports) != "dict":
        return {}
    out = {}
    for key in exports.keys():
        if not key.startswith("./") or "*" in key:
            continue
        for target in _export_targets(exports[key]):
            designated = _declaration_at(target, has_file)
            if designated:
                out[key] = designated
                break
    return out

def _directive_value(line, attribute):
    for quote in ('"', "'"):
        marker = " " + attribute + "=" + quote
        start = line.find(marker)
        if start < 0:
            continue
        start += len(marker)
        end = line.find(quote, start)
        if end > start:
            return line[start:end]
    return ""

def _triple_slash_directives(content):
    """`(attribute, value)` for each `/// <reference ...>` in a file's header.

    TypeScript reads a directive only above the first statement, so the scan
    stops at the first line that is neither blank, a comment nor a directive.
    Only `types` and `path` are reported: `lib` names a file of the compiler's
    own and `no-default-lib` names none.
    """
    out = []
    in_block = False
    for line in content.split("\n"):
        stripped = line.strip()
        if in_block:
            end = stripped.find("*/")
            if end < 0:
                continue
            in_block = False
            if stripped[end + 2:].strip():
                break
            continue
        if not stripped:
            continue
        if stripped.startswith("///"):
            if stripped[3:].lstrip().startswith("<reference"):
                for attribute in ("types", "path"):
                    value = _directive_value(stripped, attribute)
                    if value:
                        out.append((attribute, value))
            continue
        if stripped.startswith("//"):
            continue
        if stripped.startswith("/*"):
            end = stripped.find("*/", 2)
            if end < 0:
                in_block = True
            elif stripped[end + 2:].strip():
                break
            continue
        break
    return out

def _sibling_path(path, relative):
    """`relative`, written in `path`'s directory, as a package-relative path; "" above the root."""
    parts = []
    for part in path.split("/")[:-1] + relative.split("/"):
        if part in ("", "."):
            continue
        if part != "..":
            parts.append(part)
        elif parts:
            parts.pop()
        else:
            return ""
    return "/".join(parts)

# A worklist bound Starlark's for-loop needs, not a size any package approaches.
_MAX_REFERENCED_FILES = 4096

def _referenced_types(read, entry):
    """The packages `entry`'s `/// <reference types=...>` directives name, sorted.

    A `path` directive pulls a sibling into the program along with `entry`, so
    the walk follows those within the package and reads each sibling's header
    too. `read` returns a package-relative file's text, or None for no such file.
    """
    names = {}
    seen = {entry: True}
    pending = [entry]
    for _ in range(_MAX_REFERENCED_FILES):
        if not pending:
            return sorted(names.keys())
        path = pending.pop()
        content = read(path)
        if content == None:
            continue
        for attribute, value in _triple_slash_directives(content):
            if attribute == "types":
                names[value] = True
                continue
            sibling = _sibling_path(path, value)
            if sibling and sibling not in seen:
                seen[sibling] = True
                pending.append(sibling)
    fail("npm_import: more than {} declarations reachable through /// <reference path> from {}".format(
        _MAX_REFERENCED_FILES,
        entry,
    ))

def _type_references(read, declarations):
    """Each of `declarations` whose header names a package, mapped to the names.

    TypeScript resolves `/// <reference types="x" />` through `typeRoots` and a
    node_modules walk from the referencing file, never through `paths`, and a
    consumer's sandbox has neither. So the names are read here, where the file
    is, and the consumer resolves each against this package's deps -- the same
    route as `subpath_types`, for the same reason.
    """
    out = {}
    for path in declarations:
        names = _referenced_types(read, path)
        if names:
            out[path] = names
    return out

def _rctx_has_file(rctx):
    def has_file(path):
        return rctx.path(path).exists

    return has_file

def _rctx_read(rctx):
    def read(path):
        p = rctx.path(path)
        return rctx.read(p) if p.exists and not p.is_dir else None

    return read

def _primary_bin_name(package, bins):
    """The bin a bare `bazel run @npm//:<pkg>_bin` should mean.

    npm's own convention: the entry named after the package, else the only one.
    An ambiguous multi-bin package has no primary; callers name the script.
    """
    if not bins:
        return ""
    unscoped = package.split("/")[-1] if package.startswith("@") else package
    if unscoped in bins:
        return unscoped
    if len(bins) == 1:
        return list(bins.keys())[0]
    return ""

def _quote_list(items, indent = "        "):
    return "".join(['{}"{}",\n'.format(indent, i) for i in items])

def _label_list_expr(rctx_name, platforms, common, by_platform, indent = "        "):
    """Renders a label list that is partly platform-conditional.

    npm ships native code as `optionalDependencies` constrained by `os`/`cpu`,
    so which of them belongs in a dep list is a property of the TARGET platform,
    not of the machine that read the lockfile. Deciding it here -- in generated
    text, as a select() -- is what keeps the module extension's result, and
    therefore MODULE.bazel.lock, free of the host it ran on.

    The select has a branch for every platform rules_typescript names and no
    default, so an unsupported target platform is an error that says so rather
    than a silently short dependency list. The platform vocabulary arrives as an
    attribute rather than a load of //platforms: a spoke repository generated by
    the extension has no business knowing more about the ruleset than the
    extension told it.
    """
    parts = []
    if common:
        parts.append("[\n" + _quote_list(common, indent + "    ") + indent + "]")
    if by_platform:
        branches = [indent + "select({\n"]
        for platform in platforms:
            labels = by_platform.get(platform, [])
            branches.append('{}    "@rules_typescript//platforms:is_{}": [\n'.format(indent, platform))
            branches.append(_quote_list(labels, indent + "        "))
            branches.append(indent + "    ],\n")
        branches.append(
            indent + '}, no_match_error = "' + rctx_name +
            ": npm packages here are platform-specific and this target platform is none of " +
            ", ".join(platforms) + '")',
        )
        parts.append("".join(branches).lstrip())
    if not parts:
        return ""
    return " + ".join(parts)

def _package_relative_label(path):
    """A path inside the package, written so a label attribute reads it as one.

    A first segment starting with `@` -- formdata-node keeps its declarations in
    a directory called `@type` -- is otherwise a repository reference, and Bazel
    rejects the entire generated repository rather than the one attribute.
    """
    return ":" + path

def _package_stanza(attrs, target_name, package_name, deps_expr, declaration_entry, subpath_declarations, type_references):
    """The ts_npm_package call for one name this package is imported under."""
    stanza = [
        "ts_npm_package(",
        '    name = "{}",'.format(target_name),
        '    package_name = "{}",'.format(package_name),
        '    package_version = "{}",'.format(attrs.version),
    ]
    if attrs.peer_id:
        stanza.append('    peer_id = "{}",'.format(attrs.peer_id))
    stanza += [
        '    package_dir = ":package.json",',
        '    package_files = glob(["**/*"], exclude_directories = 1, allow_empty = True),',
    ]
    if deps_expr:
        stanza.append("    deps = {},".format(deps_expr))
    if attrs.types_dep:
        stanza.append('    types_dep = "{}",'.format(attrs.types_dep))
    if attrs.is_types_package:
        stanza.append("    is_types_package = True,")
    if declaration_entry:
        stanza.append('    exports_types = "{}",'.format(_package_relative_label(declaration_entry)))
    if subpath_declarations:
        stanza.append("    subpath_types = {")
        for subpath in sorted(subpath_declarations.keys()):
            stanza.append('        "{}": "{}",'.format(subpath, subpath_declarations[subpath]))
        stanza.append("    },")
    if type_references:
        stanza.append("    type_references = {")
        for path in sorted(type_references.keys()):
            stanza.append('        "{}": [{}],'.format(
                path,
                ", ".join(['"{}"'.format(name) for name in type_references[path]]),
            ))
        stanza.append("    },")
    stanza.append(")\n")
    return "\n".join(stanza)

def _apply_patch(rctx):
    """Applies the package's pnpm patch, failing the fetch if it does not land.

    The tarball just downloaded is byte-identical to the unpatched publish, so a
    patch that quietly fails to apply leaves nothing downstream able to tell the
    difference until production. Hence two loud gates: the digest below, and
    rctx.patch itself, which fails on any hunk that does not apply.
    """
    patch = rctx.attr.patch

    # An attr.label is not by itself a dependency of the fetch, and neither is
    # rctx.path on it: without this, editing a patch file leaves the already
    # fetched repository in place and the build keeps the old patch.
    rctx.watch(patch)

    if not rctx.attr.patch_sha256:
        rctx.patch(patch, strip = 1)
        return

    # Copied through the downloader purely to get its digest -- Starlark has no
    # hashing builtin. Deliberately WITHOUT download's own sha256 argument: a
    # checksummed request is served from the content-addressed repository cache
    # without reading the file at all, so an edited patch would be silently
    # replaced by the locked bytes on a warm cache and rejected on a cold one.
    local = "_pnpm.patch"
    result = rctx.download(url = "file://" + str(rctx.path(patch)), output = local)
    if result.sha256 != rctx.attr.patch_sha256:
        fail(
            "npm: {} does not match the sha256 recorded for {} in the lockfile's ".format(
                patch,
                rctx.attr.package,
            ) +
            "patchedDependencies:\n  lockfile: {}\n  file:     {}\n".format(
                rctx.attr.patch_sha256,
                result.sha256,
            ) +
            "pnpm records that digest when it writes the patch, so the two disagreeing " +
            "means the patch changed without `pnpm install` being re-run. Bazel would " +
            "apply a patch pnpm never saw.",
        )
    rctx.patch(local, strip = 1)
    rctx.delete(local)

def _npm_import_impl(rctx):
    tarball = "_pkg.tgz"
    auth = _auth_for_fetch(rctx, rctx.attr.url)
    rctx.download(url = rctx.attr.url, output = tarball, integrity = rctx.attr.integrity, auth = auth)

    # Extracted twice deliberately: the strip prefix is only knowable by looking
    # inside, and Starlark cannot catch the failure a wrong one would raise.
    staging = "_stage"
    rctx.extract(archive = tarball, output = staging)
    prefix = _tarball_prefix(rctx, staging)
    rctx.delete(staging)

    rctx.extract(archive = tarball, stripPrefix = prefix)
    rctx.delete(tarball)

    # Before package.json is read: a patch may change `bin` or `exports`, and
    # pnpm links the patched manifest, so the generated targets must describe
    # the patched package rather than the published one.
    if rctx.attr.patch:
        _apply_patch(rctx)

    pkg_json = {}
    pkg_json_path = rctx.path("package.json")
    if pkg_json_path.exists:
        pkg_json = json.decode(rctx.read(pkg_json_path))

    lines = [_NPM_BUILD_HEADER]
    bins = _bin_entries(pkg_json)
    if bins:
        lines.append('load("@rules_typescript//npm/private:npm_bin.bzl", "npm_bin")\n')
    lines.append('package(default_visibility = ["//visibility:public"])\n')
    lines.append('exports_files(["package.json"])\n')

    declaration_entry = _exports_types(pkg_json, _rctx_has_file(rctx))
    subpath_declarations = _exports_subpath_types(pkg_json, _rctx_has_file(rctx))
    type_references = _type_references(
        _rctx_read(rctx),
        ([declaration_entry] if declaration_entry else []) + sorted(subpath_declarations.values()),
    )

    deps_expr = _label_list_expr(
        rctx.attr.package,
        rctx.attr.platforms,
        rctx.attr.deps,
        rctx.attr.platform_deps,
    )
    lines.append(_package_stanza(
        rctx.attr,
        "pkg",
        rctx.attr.package,
        deps_expr,
        declaration_entry,
        subpath_declarations,
        type_references,
    ))

    # An npm alias (`h3-v2: npm:h3@2.0.1`) is the same files installed under a
    # second name. package_name is what the node_modules tree builder writes on
    # disk, so the alias needs its own target: node_modules/h3-v2 is where
    # `import "h3-v2"` looks, and pointing a Bazel alias at :pkg would produce
    # node_modules/h3 instead.
    for target_name, alias_package in rctx.attr.aliases.items():
        lines.append(_package_stanza(
            rctx.attr,
            target_name,
            alias_package,
            deps_expr,
            declaration_entry,
            subpath_declarations,
            type_references,
        ))

    # Native binaries a bin script resolves at runtime live in sibling
    # repositories, so they are declared as targets rather than located by
    # directory name inside one shared repository.
    optional_expr = _label_list_expr(
        rctx.attr.package,
        rctx.attr.platforms,
        rctx.attr.optional_dep_packages,
        rctx.attr.platform_optional_dep_packages,
    )
    for bin_name, bin_path in bins.items():
        bin_stanza = [
            "npm_bin(",
            '    name = "{}",'.format(bin_name),
            '    entry_script = "{}",'.format(bin_path.removeprefix("./")),
            '    package_files = glob(["**/*"], exclude_directories = 1, allow_empty = True),',
        ]
        if optional_expr:
            bin_stanza.append("    optional_dep_packages = {},".format(optional_expr))
        bin_stanza.append(")\n")
        lines.append("\n".join(bin_stanza))

    # The hub aliases <label>_bin without being able to see whether a package has
    # a bin -- knowing that is exactly what downloading it would cost. So the
    # package exposes a fixed ":bin" name for its primary script, and the hub's
    # alias resolves only if something actually asks for it.
    primary_bin = _primary_bin_name(rctx.attr.package, bins)
    if primary_bin:
        lines.append('alias(\n    name = "bin",\n    actual = ":{}",\n)\n'.format(primary_bin))

    rctx.file("BUILD.bazel", "\n".join(lines))

npm_import = repository_rule(
    implementation = _npm_import_impl,
    attrs = {
        "package": attr.string(mandatory = True, doc = "npm package name, e.g. '@types/react'."),
        "version": attr.string(mandatory = True, doc = "Resolved version."),
        "peer_id": attr.string(
            doc = "Filesystem-safe token naming this snapshot's peer set, empty for a " +
                  "package pnpm resolved only one way. The repository name already carries " +
                  "it; this passes it on to the providers, which is where a node_modules " +
                  "tree can act on it.",
        ),
        "url": attr.string(mandatory = True, doc = "Tarball URL."),
        "integrity": attr.string(
            mandatory = True,
            doc = "SRI hash from the lockfile's resolution.integrity. Mandatory: an " +
                  "unverified npm fetch should not be expressible, and the extension " +
                  "rejects a lockfile entry that cannot supply one.",
        ),
        "deps": attr.string_list(
            doc = "Apparent labels of sibling npm_import repos this package depends on " +
                  "on every platform, already cycle-broken by the extension.",
        ),
        "platforms": attr.string_list(
            doc = "The PLATFORMS keys a platform select() must cover, supplied by the " +
                  "extension so the generated BUILD file needs no load of //platforms.",
        ),
        "platform_deps": attr.string_list_dict(
            doc = "PLATFORMS key -> the deps that only apply when building for that " +
                  "platform. Rendered as a select(), so the choice happens at analysis " +
                  "time rather than in the extension.",
        ),
        "types_dep": attr.string(doc = "Apparent label of the @types/* package for this one."),
        "is_types_package": attr.bool(default = False),
        "optional_dep_packages": attr.string_list(
            doc = "Apparent labels of sibling npm_import repos holding native binaries " +
                  "this package's bin scripts resolve at runtime on every platform.",
        ),
        "platform_optional_dep_packages": attr.string_list_dict(
            doc = "PLATFORMS key -> the runtime sidecar packages that only apply when " +
                  "building for that platform.",
        ),
        "aliases": attr.string_dict(
            doc = "Target name -> npm package name for each additional name this package " +
                  "is imported under (npm alias specifiers). The extension names the " +
                  "targets so the hub and the spoke agree without duplicating the " +
                  "name-to-label rule.",
        ),
        "patch": attr.label(
            allow_single_file = True,
            doc = "The pnpm patch to apply to this package, from patchedDependencies.",
        ),
        "npmrc": attr.label(
            allow_single_file = True,
            doc = "The workspace .npmrc, read at fetch time for the credentials of the " +
                  "registry this package's url points at. A label rather than the parsed " +
                  "values, so no token is ever an attribute value -- attribute values are " +
                  "written to MODULE.bazel.lock.",
        ),
        "patch_sha256": attr.string(
            doc = "sha256 of the patch file as recorded in the lockfile's " +
                  "patchedDependencies. Empty when the lockfile records the digest " +
                  "in some other form, which skips the content check.",
        ),
    },
    doc = "Fetches one npm package into its own repository and generates its BUILD file.",
)

def _alias_block(alias_names, aliases):
    lines = []
    for alias_name in sorted(alias_names):
        lines.append("alias(")
        lines.append('    name = "{}",'.format(alias_name))
        lines.append('    actual = "{}",'.format(aliases[alias_name]))
        lines.append(")")
        lines.append("")
    return lines

_LINK_LOAD = 'load("@rules_typescript//npm/private:workspace_package.bzl", "npm_workspace_package")'

# ─── pnpm `link:` members: which Bazel package builds one ────────────────────

_TARGET_NAME_DIRECTIVE = "# gazelle:ts_target_name"

def _negated_depth(dir_path):
    return -len(dir_path.split("/"))

def _link_candidate_dirs(member, entries):
    """The directories that could hold a member's target, innermost first.

    A member is a directory; what has to be depended on is the target that
    compiles it, and which directory holds that target is not the member's to
    say. `ts_package_boundary` decides it -- the default gives every directory
    holding sources its own package, `tsconfig` rolls the subtree up into the
    directory holding tsconfig.json -- so `packages/foo` with
    `main: src/index.ts` builds from `packages/foo/src:src` under one mode and
    from `packages/foo:foo` under another.

    Both modes are declared in BUILD files, which is why this returns candidates
    rather than an answer: the caller looks them up, innermost first, and the one
    that declares the target wins.

    A manifest can designate several entry points -- a `main` and an `exports`
    map that disagree, or one `exports` condition per output format -- so every
    directory any of them sits in is a candidate. The order is by depth over all
    of them together rather than one chain at a time: taken chain by chain, the
    member root would come ahead of a deeper directory named by a later entry
    point, and the root is the candidate that must be tried last.

    Args:
        member: The member's path from the repo root, e.g. "packages/foo".
        entries: The entry points the member designates, in resolver order.
    """
    dirs = [member]
    for entry in entries:
        current = member
        for part in entry.strip("./").split("/")[:-1]:
            if not part:
                continue
            current = current + "/" + part
            if current not in dirs:
                dirs.append(current)
    return sorted(dirs, key = _negated_depth)

def _target_name_in(build_text, dir_path):
    """The name the ts_compile in a directory carries: its own, or the directive's."""
    for line in build_text.split("\n"):
        line = line.strip()
        if not line.startswith(_TARGET_NAME_DIRECTIVE):
            continue
        value = line[len(_TARGET_NAME_DIRECTIVE):].strip()
        if value:
            return value
    return dir_path.split("/")[-1]

def _names_a_target(build_text, target):
    return (
        'name = "{}"'.format(target) in build_text or
        'name="{}"'.format(target) in build_text or
        "name = '{}'".format(target) in build_text or
        "name='{}'".format(target) in build_text
    )

def _read_if_present(rctx, path):
    """The file's text, or None -- watching a file that is not there yet.

    Absence is a load-bearing answer here: a directory becomes a Bazel package
    the moment Gazelle writes a BUILD file into it, and that has to refetch this
    repository.
    """
    if path.exists:
        return rctx.read(path)
    rctx.watch(path)
    return None

def _manifest_entries(pkg_json):
    """Every entry point a workspace member's manifest designates, resolver order.

    `main` and `module`, then what `exports["."]` names. A package that ships an
    exports map and no `main` designates its entry point there and nowhere else,
    and reading only `main` leaves such a member with its own root as the sole
    candidate -- which is the directory a `tsconfig` boundary would have rolled
    it up into and not the one the default boundary puts its target in.

    The exports map is read by `_root_export` and `_export_targets`, the same two
    readers the published-package path uses: a plain string, `{".": ...}`, the
    subpath-free condition shorthand, nested condition maps keyed by
    types/typings/node/import/require/default, and fallback arrays. A condition
    outside that set (`browser`, `development`) is not followed, and a target
    holding a `*` is dropped -- it designates a pattern, whose directory is a
    pattern too.

    Args:
        pkg_json: The member's decoded package.json.
    """
    entries = []
    for field in ("main", "module"):
        value = pkg_json.get(field)
        if type(value) == "string" and value:
            entries.append(value)
    for target in _export_targets(_root_export(pkg_json.get("exports"))):
        if target and "*" not in target and target not in entries:
            entries.append(target)
    return entries

def _member_entries(rctx, member_dir):
    """`_manifest_entries` of a member's package.json, or [] when it has none."""
    content = _read_if_present(rctx, member_dir.get_child("package.json"))
    if content == None:
        return []
    decoded = json.decode(content)
    if type(decoded) != "dict":
        return []
    return _manifest_entries(decoded)

def _build_file_text(rctx, root, dir_path):
    for name in ("BUILD.bazel", "BUILD"):
        text = _read_if_present(rctx, root.get_child(*(dir_path.split("/") + [name])))
        if text != None:
            return text
    return None

def _link_target_label(member, entries, build_text):
    """The label of the target that builds a workspace member, or None.

    A label only for a candidate directory that DECLARES the target. Nothing
    weaker earns one: a BUILD file that does not declare it is the statement that
    the target is not there, and the label would name a target Bazel cannot
    resolve -- which is far worse than a missing one, because it fails analysis
    for everything that reaches the hub while a missing target fails only what
    asks for the member. The hub declares no target for that name at all
    instead.

    Args:
        member: The member's path from the repo root, e.g. "packages/foo".
        entries: The entry points its manifest designates, in resolver order.
        build_text: Function from a candidate directory to the text of the BUILD
            file in it, or None when that directory holds none.
    """
    for dir_path in _link_candidate_dirs(member, entries):
        text = build_text(dir_path)
        if text == None:
            continue
        target = _target_name_in(text, dir_path)
        if _names_a_target(text, target):
            return "@@//{}:{}".format(dir_path, target)
    return None

def _repo_root(rctx):
    """The root the labels this rule writes are relative to.

    `@@//` is the main repository, so the member paths are resolved against it
    rather than against the lockfile's own directory -- the two coincide for a
    pnpm workspace, whose lockfile sits at its root.
    """
    root = rctx.path(rctx.attr.pnpm_lock).dirname
    package = rctx.attr.pnpm_lock.package
    for _ in (package.split("/") if package else []):
        root = root.dirname
    return root

def _member_targets(rctx):
    """Label per member path named by any `link:` in this lockfile, None if absent."""
    links = list(rctx.attr.links.values()) + list(rctx.attr.importer_links.values())
    if not links:
        return {}
    root = _repo_root(rctx)

    def build_text(dir_path):
        return _build_file_text(rctx, root, dir_path)

    targets = {}
    for link in links:
        _, _, member = link.partition("|")
        if member not in targets:
            entries = _member_entries(rctx, root.get_child(*member.split("/")))
            targets[member] = _link_target_label(member, entries, build_text)
    return targets

def _unresolved_link_note(package_name, member):
    return [
        "# NO TARGET for '{}'. No BUILD file under".format(package_name),
        "# {} declares one, so nothing here can name the".format(member),
        "# target that builds the member: run Gazelle over that directory. A label",
        "# written anyway would name a target Bazel cannot resolve, which fails analysis",
        "# for every consumer of this hub rather than for this name alone.",
        "",
    ]

def _link_block(links, targets, module_paths):
    """One target per pnpm `link:` dependency, carrying the name it is imported by.

    Not an alias: Bazel resolves an alias before any rule implementation runs, so
    the member would arrive at a consumer with no record of the npm name at all --
    which is why a workspace member used to have to restate it as `module_name`.

    What the member's own package.json says its specifiers resolve to travels with
    it, because that is written in a file nothing downstream can read.
    """
    lines = []
    for label_name in sorted(links):
        package_name, _, member = links[label_name].partition("|")
        target = targets.get(member)
        if not target:
            lines.extend(_unresolved_link_note(package_name, member))
            continue
        lines.append("npm_workspace_package(")
        lines.append('    name = "{}",'.format(label_name))
        lines.append('    package_name = "{}",'.format(package_name))
        lines.append('    target = "{}",'.format(target))
        declared = module_paths.get(label_name)
        if declared:
            member_dir, _, text = declared.partition("|")
            lines.append('    member_dir = "{}",'.format(member_dir))
            lines.append("    module_paths = {},".format(json.encode(text)))
        lines.append(")")
        lines.append("")
    return lines

_HUB_HEADER = [
    "# Generated by npm_hub. Do not edit.",
    "#",
    "# Aliases, plus one target per workspace link: this repository downloads",
    "# nothing, so it stays cheap to regenerate when the lockfile changes, and",
    "# referencing one alias fetches only that package's own repository.",
    'package(default_visibility = ["//visibility:public"])',
    "",
]

def _hub_lines(links, note = None):
    """The header, carrying the load a `link:` target needs and nothing else."""
    lines = list(_HUB_HEADER)
    if note:
        lines.insert(1, "# {}".format(note))
    return ([_LINK_LOAD, ""] + lines) if links else lines

def _npm_hub_impl(rctx):
    targets = _member_targets(rctx)
    module_paths_by_importer = {}
    for key, declared in rctx.attr.link_module_paths.items():
        path, _, label_name = key.rpartition("|")
        module_paths_by_importer.setdefault(path, {})[label_name] = declared

    lines = _hub_lines(rctx.attr.links)
    lines.extend(_alias_block(rctx.attr.aliases.keys(), rctx.attr.aliases))
    lines.extend(_link_block(rctx.attr.links, targets, module_paths_by_importer.get("", {})))
    if rctx.attr.broken_cycle_edges:
        lines.append("# Circular npm dependency edges removed for an acyclic target graph.")
        lines.append("# These packages rely on Node's CJS cycle tolerance at runtime.")
        for edge in rctx.attr.broken_cycle_edges:
            lines.append("#   CYCLE BROKEN: {}".format(edge))
    rctx.file("BUILD.bazel", "\n".join(lines) + "\n")

    # One package per workspace member, so `@npm//path/to/member:react` is the
    # snapshot THAT member resolved react to. The root package above is the
    # whole-lockfile namespace and has to pick one snapshot per name; a member's
    # own package does not, which is the only place per-importer resolution can
    # live given that a Bazel package has one namespace.
    by_importer = {}
    links_by_importer = {}
    for key, target in rctx.attr.importer_aliases.items():
        path, _, alias_name = key.rpartition("|")
        by_importer.setdefault(path, {})[alias_name] = target
    for key, entry in rctx.attr.importer_links.items():
        path, _, label_name = key.rpartition("|")
        by_importer.setdefault(path, {})
        links_by_importer.setdefault(path, {})[label_name] = entry

    for path, aliases in by_importer.items():
        links = links_by_importer.get(path, {})
        sub = _hub_lines(links, "Resolution as declared by the workspace member at {}.".format(path))
        sub.extend(_alias_block(aliases.keys(), aliases))
        sub.extend(_link_block(links, targets, module_paths_by_importer.get(path, {})))
        rctx.file("{}/BUILD.bazel".format(path), "\n".join(sub) + "\n")

npm_hub = repository_rule(
    implementation = _npm_hub_impl,
    attrs = {
        "aliases": attr.string_dict(
            mandatory = True,
            doc = "Label name -> apparent label of the target it forwards to.",
        ),
        "importer_aliases": attr.string_dict(
            doc = "'<importer path>|<label name>' -> apparent label, one entry per " +
                  "dependency a workspace member declared. Flattened into a string_dict " +
                  "because a repository rule attribute cannot nest dicts; '|' cannot " +
                  "occur in either a package path or a label name.",
        ),
        "links": attr.string_dict(
            doc = "Label name -> '<npm package name>|<path of the workspace member>' " +
                  "for each pnpm `link:` dependency. A path rather than a label: which " +
                  "directory of a member holds its target is decided by Gazelle " +
                  "directives in BUILD files, so it is looked up here at fetch time. The " +
                  "package name travels with it because it cannot be recovered from the " +
                  "label name: 'types_react' is the label of '@types/react' and of " +
                  "'types_react'.",
        ),
        "importer_links": attr.string_dict(
            doc = "'<importer path>|<label name>' -> the same '<package name>|<member " +
                  "path>' pair, for the `link:` dependencies one workspace member " +
                  "declared.",
        ),
        "pnpm_lock": attr.label(
            allow_single_file = True,
            doc = "The lockfile this hub was translated from, for the repository root " +
                  "the `link:` member paths are resolved against.",
        ),
        "link_module_paths": attr.string_dict(
            doc = "'<importer path>|<label name>' -> '<member directory>|<specifier " +
                  "to declarations JSON>', for every `link:` above whose member says " +
                  "how it is entered. The root importer's path is empty, and the " +
                  "FIRST '|' is the separator -- a directory cannot contain one, " +
                  "while the JSON that follows is a member's own strings and could. " +
                  "That is also why this is its own attribute instead of a third " +
                  "field on `links`, whose split is safe only because neither a " +
                  "package name nor a label can contain a '|' anywhere.",
        ),
        "broken_cycle_edges": attr.string_list(
            doc = "Human-readable record of edges the extension removed.",
        ),
    },
    doc = "Alias-only hub giving npm packages stable @npm//:<name> labels, plus one " +
          "package per workspace member holding that member's own resolution.",
)

# The `exports` shape, without the tarball: a workspace member's manifest has the
# same conditions and the same key order, and only what a designated target MEANS
# differs -- a member names a source Bazel has yet to compile, a tarball names a
# file it already ships. member_paths.bzl reads the shape with these and answers
# the rest itself, so one manifest cannot be read two ways.
root_export = _root_export
export_targets = _export_targets

# Exported for the tests that pin the credential rules, the declaration a package
# designates, which target a `link:` member resolves to, and the BUILD text all
# of it is written into; the paths above are the only production callers.
link_candidate_dirs = _link_candidate_dirs
manifest_entries = _manifest_entries
link_target_label = _link_target_label
link_block = _link_block
target_name_in = _target_name_in
exports_types = _exports_types
exports_subpath_types = _exports_subpath_types
triple_slash_directives = _triple_slash_directives
referenced_types = _referenced_types
type_references = _type_references
package_stanza = _package_stanza
npmrc_auth = _npmrc_auth
npmrc_auth_fields = _npmrc_auth_fields
