"""Rule for executable npm bin script targets.

npm_bin wraps a bin script from an npm package as a Bazel executable target.
It resolves Node.js from the js_runtime toolchain (or falls back to system node)
and invokes the specified script entry point with any provided arguments.

Generated by npm_import for each entry in a package's "bin" field.

Usage (generated by npm_import):
    npm_bin(
        name = "vitest",
        entry_script = "vitest.mjs",
        package_files = glob(["node_modules/vitest/**/*"], exclude_directories = 1, allow_empty = True),
    )

Users can then:
    bazel run @npm//:vitest_bin -- --version
"""

load("//tools/launcher:launcher.bzl", "LAUNCHER_ATTRS", "declare_launcher", "rlocation_path")
load("//ts/private:providers.bzl", "NpmPackageInfo")
load("//ts/private:runtime.bzl", "JS_RUNTIME_TOOLCHAIN_TYPE", "get_js_runtime")

def _npm_bin_impl(ctx):
    # Resolve the JS runtime from the toolchain or fall back to system node.
    runtime_binary = None
    runtime_args = []
    if ctx.file.runtime:
        runtime_binary = ctx.file.runtime
    else:
        js_runtime = get_js_runtime(ctx)
        if js_runtime:
            runtime_binary = js_runtime.runtime_binary
            runtime_args = js_runtime.args_prefix

    # Locate the entry script from the package files.
    # The package_dir attribute holds the package.json file; the entry script
    # is a sibling file (relative to the package root).
    entry_script_file = None
    entry_script = ctx.attr.entry_script
    for f in ctx.files.package_files:
        # Suffix match; the package sits under node_modules/<name> in its repository:
        # external/<repository>/node_modules/vitest/vitest.mjs.
        if f.basename == entry_script or f.path.endswith("/" + entry_script):
            entry_script_file = f
            break

    if not entry_script_file:
        available = [f.basename for f in ctx.files.package_files]
        fail(
            "npm_bin: entry script '{}' not found in package files for target '{}'.\n".format(
                entry_script,
                ctx.label,
            ) +
            "This usually means the npm package's 'bin' field references a file that " +
            "was not included in package_files, or the entry_script path is wrong.\n" +
            "Available files: {}".format(", ".join(available[:20]) + (" ..." if len(available) > 20 else "")),
        )

    # Some npm packages (e.g. oxlint) reach a platform-specific native binary
    # through require.resolve('@scope/platform-pkg/binary'), and Node resolves
    # that by walking parent directories looking for node_modules/. Inside a
    # runfiles tree or action sandbox there is no such directory, and with one
    # repository per npm package the sibling is not even nearby, so the sibling
    # identifies itself through NpmPackageInfo and its package.json locates its
    # root. The launcher links them into a temp dir, not the runfiles tree,
    # which is read-only for tools in action sandboxes and after `bazel run`.
    optional_deps = []
    optional_dep_pkg_files = []
    for dep in ctx.attr.optional_dep_packages:
        info = dep[NpmPackageInfo]
        if not info.package_dir:
            continue
        optional_deps.append({
            "name": info.package_name,
            "package_json": rlocation_path(ctx, info.package_dir),
        })
        optional_dep_pkg_files.append(info.all_files)

    config = {
        "label": str(ctx.label),
        "mode": "node",
        "workspace": ctx.workspace_name,
        "runtime_args": runtime_args,
        "node": {
            "entry": rlocation_path(ctx, entry_script_file),
            # The tools that run this bin script (ts_lint) pass absolute paths
            # and expect the runfiles root as the working directory.
            "chdir_runfiles": True,
            "optional_deps": optional_deps,
        },
    }
    if runtime_binary:
        config["runtime"] = rlocation_path(ctx, runtime_binary)

    launcher = declare_launcher(ctx, config, basename = "{}_bin_launcher".format(ctx.label.name))

    # Collect all runfiles: the launcher, entry script, all package files, and the runtime.
    runfiles_files = [entry_script_file] + launcher.files
    if runtime_binary:
        runfiles_files.append(runtime_binary)

    # Also include the full package files so Node can resolve modules inside the package.
    runfiles = ctx.runfiles(
        files = runfiles_files,
        transitive_files = depset(ctx.files.package_files, transitive = optional_dep_pkg_files),
        root_symlinks = launcher.root_symlinks,
    )

    return [
        DefaultInfo(
            executable = launcher.executable,
            runfiles = runfiles,
        ),
    ]

npm_bin = rule(
    implementation = _npm_bin_impl,
    executable = True,
    attrs = LAUNCHER_ATTRS | {
        "package_files": attr.label_list(
            doc = "All files in the npm package directory (from the ts_npm_package target).",
            allow_files = True,
        ),
        "entry_script": attr.string(
            doc = "The relative path within the package to the bin entry script (e.g. 'vitest.mjs').",
            mandatory = True,
        ),
        "optional_dep_packages": attr.label_list(
            providers = [[NpmPackageInfo]],
            doc = "Sibling npm package targets holding platform-specific native " +
                  "binaries this bin script resolves at runtime. The launcher creates " +
                  "node_modules/ symlinks for them so require.resolve() works inside " +
                  "action sandboxes and runfiles trees.",
        ),
        "runtime": attr.label(
            doc = "Per-target override for the JS runtime binary. " +
                  "When set, takes priority over the js_runtime toolchain.",
            allow_single_file = True,
            executable = True,
            cfg = "exec",
        ),
    },
    toolchains = [
        config_common.toolchain_type(JS_RUNTIME_TOOLCHAIN_TYPE, mandatory = False),
    ],
    doc = """Exposes an npm package's bin script as an executable Bazel target.

Generated by npm_import for each entry in the package's 'bin' field.
Resolves Node.js from the js_runtime toolchain (or falls back to system node).

Example usage:
    bazel run @npm//:vitest_bin -- --version
    bazel run @npm//:tsx -- script.ts
""",
)
