"""Per-resolution npm repositories: one external repo per snapshot, plus an alias hub.

Why this shape rather than one big repo
---------------------------------------
A single repository holding every package has to download and extract all of
them before it can generate any BUILD file, because it reads `bin` and `exports`
out of each extracted `package.json`. On a real 2731-package lockfile that is
~5 minutes and ~5 GB, paid in full even by a target whose only npm dependency is
vitest, in one serial Starlark loop with no resume: a single bad tarball restarts
everything.

The unit is one pnpm SNAPSHOT -- a package as resolved for one peer set -- not
one `name@version`. pnpm resolves a package once per distinct peer set and gives
each outcome its own dependency edges, so two snapshots can share a tarball and
disagree about what they depend on.

Here each snapshot is its own repository rule, so it reads its OWN package.json
and writes its OWN BUILD file. Bazel then fetches repositories on demand, which
gives four things the monolith cannot:

  - Laziness. Only packages in the requested targets' transitive closure are
    fetched. `@npm//:vitest` pulls vitest's subtree, not the lockfile.
  - Parallelism. Bazel fetches independent repositories concurrently instead of
    looping in Starlark.
  - Per-package caching and invalidation. Bumping one package invalidates one
    repository, not all of them.
  - Isolated failure. A malformed tarball fails its own package.

`npm_hub` is the stable label surface. Its root package is the whole-lockfile
namespace (`@npm//:zod`, `@npm//:types_react`, `@npm//:vitest_bin`), and it holds
one further package per workspace member (`@npm//apps/web:react`) carrying that
member's own resolution -- which the root package cannot, because a Bazel package
has one namespace and two members can resolve one name differently. It contains
only `alias` targets and downloads nothing, so it is cheap to regenerate whenever
the lockfile changes. Repositories created by one module extension can reference
each other by apparent name, which is what lets the hub point at spokes without
constructing canonical repo names.

What still lives in the extension, not here
-------------------------------------------
The extension parses the lockfile once (no network) and hands each spoke a
resolved, ACYCLIC dependency list. Cycle breaking cannot move into the spokes:
npm has genuine circular peer dependencies, Bazel target graphs may not cycle,
and a spoke only knows about itself. Multi-version label assignment and @types
pairing stay there for the same reason -- they are whole-graph decisions.

Platform is the exception that does NOT get decided there. Which platforms a
tarball is built for is whole-graph knowledge, but which of them applies is a
property of the build, so the extension partitions the dep lists and the spoke
emits a select(). Deciding it in the extension would mean reading the host, and
the extension's result is recorded in MODULE.bazel.lock -- a committed file.
"""

_NPM_BUILD_HEADER = '''# Generated by npm_import. Do not edit.
load("@rules_typescript//ts/private:ts_npm_package.bzl", "ts_npm_package")
'''

def _tarball_prefix(rctx, staging):
    """Returns the archive's single top-level directory, or "" if it has none.

    npm tarballs conventionally extract under `package/`, but DefinitelyTyped
    ships `<name>/` and some ship `<name> v<major>.<minor>/`. Predicting the
    prefix from the package name means maintaining a table of exceptions, and a
    miss is not a warning -- it aborts the fetch, uncatchably. So the archive
    itself decides, by being extracted and listed. `watch = "no"` because the
    listing is of a path inside the repository being fetched, which can never be
    an input to that fetch.
    """
    entries = rctx.path(staging).readdir(watch = "no")
    if len(entries) == 1 and entries[0].is_dir:
        return entries[0].basename

    names = sorted([entry.basename for entry in entries])
    if "package.json" in names:
        return ""
    fail(
        "npm: the tarball for {} at {} is not shaped like an npm package: npm ".format(
            rctx.attr.package,
            rctx.attr.url,
        ) +
        "puts everything under one top-level directory, and this archive's top " +
        "level is [{}] with no package.json among it.\n".format(", ".join(names)) +
        "Check that the url resolves to a published npm tarball rather than a " +
        "git archive or a registry error page, then re-run `pnpm install` so the " +
        "lockfile records the registry's own resolution.",
    )

def _expand_env(value, getenv):
    """Substitutes ${VAR} from the fetch environment, the way npm does.

    This is the supported way to keep a token out of the workspace: the .npmrc
    that Bazel tracks names an environment variable, and the value only ever
    exists inside one fetch. rctx.getenv registers the variable, so changing it
    refetches.
    """
    out = ""
    rest = value
    for _ in range(16):
        start = rest.find("${")
        if start == -1:
            break
        end = rest.find("}", start)
        if end == -1:
            break
        out += rest[:start] + getenv(rest[start + 2:end], "")
        rest = rest[end + 1:]
    return out + rest

def _auth_scope(url):
    """The `//host/path/` form npm keys credentials by, for a URL or an .npmrc key."""
    for scheme in ("https://", "http://"):
        if url.startswith(scheme):
            url = url[len(scheme):]
            break
    if not url.startswith("//"):
        url = "//" + url
    return url if url.endswith("/") else url + "/"

def _npmrc_auth_fields(content, url):
    """The credential fields of the .npmrc scope that best matches a URL.

    npm keys credentials by `//host/path/` and applies the LONGEST matching
    prefix, so a registry mounted on a path (an Artifactory repo, say) carries its
    own token without claiming the whole host.

    Returns:
        (scope, {field: raw_value}) -- raw because ${VAR} is expanded by the
        caller, which is the only place the environment is available.
    """
    request_scope = _auth_scope(url)
    best_scope = ""
    fields = {}
    for raw in content.split("\n"):
        line = raw.strip()
        if not line or line.startswith("#") or line.startswith(";") or line.startswith("["):
            continue
        key, sep, value = line.partition("=")
        if not sep or not key.strip().startswith("//"):
            continue
        scope, _, field = key.strip().rpartition(":")
        scope = _auth_scope(scope)
        if not request_scope.startswith(scope) or len(scope) < len(best_scope):
            continue
        if scope != best_scope:
            best_scope = scope
            fields = {}
        fields[field] = value.strip().strip("'\"")
    return (best_scope, fields)

def _npmrc_auth(content, url, getenv, npmrc_label = ".npmrc"):
    """The `auth` dict rctx.download needs for one tarball URL, or {}.

    Built at fetch time, never in the module extension: an extension's result is
    serialised into MODULE.bazel.lock, a committed file, and a repository rule's
    attribute values go into it verbatim. What this repository records is the
    .npmrc's label; the token exists only for the duration of the fetch.
    """
    scope, fields = _npmrc_auth_fields(content, url)

    token = _expand_env(fields.get("_authToken", ""), getenv)
    if token:
        return {url: {"type": "pattern", "pattern": "Bearer <password>", "login": "", "password": token}}

    basic = _expand_env(fields.get("_auth", ""), getenv)
    if basic:
        return {url: {"type": "pattern", "pattern": "Basic <password>", "login": "", "password": basic}}

    if "_password" in fields:
        fail(
            "npm: {} configures `username`/`_password` for {}, which this ruleset ".format(
                npmrc_label,
                scope,
            ) +
            "cannot use: npm stores `_password` base64-encoded and Starlark has no way " +
            "to decode it (there is no chr()). Use `_authToken=` or `_auth=` instead -- " +
            "`npm config set //host/:_authToken` writes the first, and `_auth` is the " +
            "same base64 blob you already have.",
        )
    return {}

def _auth_for_fetch(rctx, url):
    if not rctx.attr.npmrc:
        return {}

    # An attr.label is not by itself an input to the fetch: without watching it,
    # rotating a token in .npmrc would leave the fetched repository in place.
    rctx.watch(rctx.attr.npmrc)
    return _npmrc_auth(rctx.read(rctx.attr.npmrc), url, rctx.getenv, str(rctx.attr.npmrc))

def _bin_entries(pkg_json):
    """Normalises package.json `bin` into {name: relative_path}.

    npm allows either a string (implying the package's own name) or a mapping.
    """
    raw = pkg_json.get("bin")
    if not raw:
        return {}
    if type(raw) == "string":
        name = pkg_json.get("name", "")
        if name.startswith("@") and "/" in name:
            name = name.split("/")[-1]
        return {name: raw} if name else {}
    if type(raw) == "dict":
        return {k: v for k, v in raw.items() if type(v) == "string"}
    return {}

def _exports_types(pkg_json):
    """Returns the .d.ts that exports["."] designates, or "".

    Preferred over globbing every .d.ts because a package's own exports map is
    the only authority on which declaration is its entry point.
    """
    exports = pkg_json.get("exports")
    if type(exports) != "dict":
        return ""
    root = exports.get(".")
    if type(root) == "string":
        return ""
    if type(root) != "dict":
        return ""
    for key in ("types", "typings"):
        value = root.get(key)
        if type(value) == "string":
            return value.removeprefix("./")
        if type(value) == "dict":
            for nested in ("import", "require", "default"):
                inner = value.get(nested)
                if type(inner) == "string":
                    return inner.removeprefix("./")
    return ""

def _primary_bin_name(package, bins):
    """The bin a bare `bazel run @npm//:<pkg>_bin` should mean.

    npm's own convention: the entry named after the package, else the only one.
    An ambiguous multi-bin package has no primary; callers name the script.
    """
    if not bins:
        return ""
    unscoped = package.split("/")[-1] if package.startswith("@") else package
    if unscoped in bins:
        return unscoped
    if len(bins) == 1:
        return list(bins.keys())[0]
    return ""

def _quote_list(items, indent = "        "):
    return "".join(['{}"{}",\n'.format(indent, i) for i in items])

def _label_list_expr(rctx_name, platforms, common, by_platform, indent = "        "):
    """Renders a label list that is partly platform-conditional.

    npm ships native code as `optionalDependencies` constrained by `os`/`cpu`,
    so which of them belongs in a dep list is a property of the TARGET platform,
    not of the machine that read the lockfile. Deciding it here -- in generated
    text, as a select() -- is what keeps the module extension's result, and
    therefore MODULE.bazel.lock, free of the host it ran on.

    The select has a branch for every platform rules_typescript names and no
    default, so an unsupported target platform is an error that says so rather
    than a silently short dependency list. The platform vocabulary arrives as an
    attribute rather than a load of //platforms: a spoke repository generated by
    the extension has no business knowing more about the ruleset than the
    extension told it.
    """
    parts = []
    if common:
        parts.append("[\n" + _quote_list(common, indent + "    ") + indent + "]")
    if by_platform:
        branches = [indent + "select({\n"]
        for platform in platforms:
            labels = by_platform.get(platform, [])
            branches.append('{}    "@rules_typescript//platforms:is_{}": [\n'.format(indent, platform))
            branches.append(_quote_list(labels, indent + "        "))
            branches.append(indent + "    ],\n")
        branches.append(
            indent + '}, no_match_error = "' + rctx_name +
            ": npm packages here are platform-specific and this target platform is none of " +
            ", ".join(platforms) + '")',
        )
        parts.append("".join(branches).lstrip())
    if not parts:
        return ""
    return " + ".join(parts)

def _apply_patch(rctx):
    """Applies the package's pnpm patch, failing the fetch if it does not land.

    The tarball just downloaded is byte-identical to the unpatched publish, so a
    patch that quietly fails to apply leaves nothing downstream able to tell the
    difference until production. Hence two loud gates: the digest below, and
    rctx.patch itself, which fails on any hunk that does not apply.
    """
    patch = rctx.attr.patch

    # An attr.label is not by itself a dependency of the fetch, and neither is
    # rctx.path on it: without this, editing a patch file leaves the already
    # fetched repository in place and the build keeps the old patch.
    rctx.watch(patch)

    if not rctx.attr.patch_sha256:
        rctx.patch(patch, strip = 1)
        return

    # Copied through the downloader purely to get its digest -- Starlark has no
    # hashing builtin. Deliberately WITHOUT download's own sha256 argument: a
    # checksummed request is served from the content-addressed repository cache
    # without reading the file at all, so an edited patch would be silently
    # replaced by the locked bytes on a warm cache and rejected on a cold one.
    local = "_pnpm.patch"
    result = rctx.download(url = "file://" + str(rctx.path(patch)), output = local)
    if result.sha256 != rctx.attr.patch_sha256:
        fail(
            "npm: {} does not match the sha256 recorded for {} in the lockfile's ".format(
                patch,
                rctx.attr.package,
            ) +
            "patchedDependencies:\n  lockfile: {}\n  file:     {}\n".format(
                rctx.attr.patch_sha256,
                result.sha256,
            ) +
            "pnpm records that digest when it writes the patch, so the two disagreeing " +
            "means the patch changed without `pnpm install` being re-run. Bazel would " +
            "apply a patch pnpm never saw.",
        )
    rctx.patch(local, strip = 1)
    rctx.delete(local)

def _npm_import_impl(rctx):
    tarball = "_pkg.tgz"
    auth = _auth_for_fetch(rctx, rctx.attr.url)
    if rctx.attr.integrity:
        rctx.download(url = rctx.attr.url, output = tarball, integrity = rctx.attr.integrity, auth = auth)
    else:
        rctx.download(url = rctx.attr.url, output = tarball, auth = auth)

    # Extracted twice deliberately: the strip prefix is only knowable by looking
    # inside, and Starlark cannot catch the failure a wrong one would raise.
    staging = "_stage"
    rctx.extract(archive = tarball, output = staging)
    prefix = _tarball_prefix(rctx, staging)
    rctx.delete(staging)

    rctx.extract(archive = tarball, stripPrefix = prefix)
    rctx.delete(tarball)

    # Before package.json is read: a patch may change `bin` or `exports`, and
    # pnpm links the patched manifest, so the generated targets must describe
    # the patched package rather than the published one.
    if rctx.attr.patch:
        _apply_patch(rctx)

    pkg_json = {}
    pkg_json_path = rctx.path("package.json")
    if pkg_json_path.exists:
        pkg_json = json.decode(rctx.read(pkg_json_path))

    lines = [_NPM_BUILD_HEADER]
    bins = _bin_entries(pkg_json)
    if bins:
        lines.append('load("@rules_typescript//npm/private:npm_bin.bzl", "npm_bin")\n')
    lines.append('package(default_visibility = ["//visibility:public"])\n')
    lines.append('exports_files(["package.json"])\n')

    exports_types = _exports_types(pkg_json)

    def _package_stanza(target_name, package_name):
        stanza = [
            "ts_npm_package(",
            '    name = "{}",'.format(target_name),
            '    package_name = "{}",'.format(package_name),
            '    package_version = "{}",'.format(rctx.attr.version),
        ]
        if rctx.attr.peer_id:
            stanza.append('    peer_id = "{}",'.format(rctx.attr.peer_id))
        stanza += [
            '    package_dir = "package.json",',
            '    package_files = glob(["**/*"], exclude_directories = 1, allow_empty = True),',
        ]
        deps_expr = _label_list_expr(
            rctx.attr.package,
            rctx.attr.platforms,
            rctx.attr.deps,
            rctx.attr.platform_deps,
        )
        if deps_expr:
            stanza.append("    deps = {},".format(deps_expr))
        if rctx.attr.types_dep:
            stanza.append('    types_dep = "{}",'.format(rctx.attr.types_dep))
        if rctx.attr.is_types_package:
            stanza.append("    is_types_package = True,")
        if exports_types:
            stanza.append('    exports_types = "{}",'.format(exports_types))
        stanza.append(")\n")
        return "\n".join(stanza)

    lines.append(_package_stanza("pkg", rctx.attr.package))

    # An npm alias (`h3-v2: npm:h3@2.0.1`) is the same files installed under a
    # second name. package_name is what the node_modules tree builder writes on
    # disk, so the alias needs its own target: node_modules/h3-v2 is where
    # `import "h3-v2"` looks, and pointing a Bazel alias at :pkg would produce
    # node_modules/h3 instead.
    for target_name, alias_package in rctx.attr.aliases.items():
        lines.append(_package_stanza(target_name, alias_package))

    # Native binaries a bin script resolves at runtime live in sibling
    # repositories, so they are declared as targets rather than located by
    # directory name inside one shared repository.
    optional_expr = _label_list_expr(
        rctx.attr.package,
        rctx.attr.platforms,
        rctx.attr.optional_dep_packages,
        rctx.attr.platform_optional_dep_packages,
    )
    for bin_name, bin_path in bins.items():
        bin_stanza = [
            "npm_bin(",
            '    name = "{}",'.format(bin_name),
            '    entry_script = "{}",'.format(bin_path.removeprefix("./")),
            '    package_files = glob(["**/*"], exclude_directories = 1, allow_empty = True),',
        ]
        if optional_expr:
            bin_stanza.append("    optional_dep_packages = {},".format(optional_expr))
        bin_stanza.append(")\n")
        lines.append("\n".join(bin_stanza))

    # The hub aliases <label>_bin without being able to see whether a package has
    # a bin -- knowing that is exactly what downloading it would cost. So the
    # package exposes a fixed ":bin" name for its primary script, and the hub's
    # alias resolves only if something actually asks for it.
    primary_bin = _primary_bin_name(rctx.attr.package, bins)
    if primary_bin:
        lines.append('alias(\n    name = "bin",\n    actual = ":{}",\n)\n'.format(primary_bin))

    rctx.file("BUILD.bazel", "\n".join(lines))

npm_import = repository_rule(
    implementation = _npm_import_impl,
    attrs = {
        "package": attr.string(mandatory = True, doc = "npm package name, e.g. '@types/react'."),
        "version": attr.string(mandatory = True, doc = "Resolved version."),
        "peer_id": attr.string(
            doc = "Filesystem-safe token naming this snapshot's peer set, empty for a " +
                  "package pnpm resolved only one way. The repository name already carries " +
                  "it; this passes it on to the providers, which is where a node_modules " +
                  "tree can act on it.",
        ),
        "url": attr.string(mandatory = True, doc = "Tarball URL."),
        "integrity": attr.string(doc = "SRI hash from the lockfile's resolution.integrity."),
        "deps": attr.string_list(
            doc = "Apparent labels of sibling npm_import repos this package depends on " +
                  "on every platform, already cycle-broken by the extension.",
        ),
        "platforms": attr.string_list(
            doc = "The PLATFORMS keys a platform select() must cover, supplied by the " +
                  "extension so the generated BUILD file needs no load of //platforms.",
        ),
        "platform_deps": attr.string_list_dict(
            doc = "PLATFORMS key -> the deps that only apply when building for that " +
                  "platform. Rendered as a select(), so the choice happens at analysis " +
                  "time rather than in the extension.",
        ),
        "types_dep": attr.string(doc = "Apparent label of the @types/* package for this one."),
        "is_types_package": attr.bool(default = False),
        "optional_dep_packages": attr.string_list(
            doc = "Apparent labels of sibling npm_import repos holding native binaries " +
                  "this package's bin scripts resolve at runtime on every platform.",
        ),
        "platform_optional_dep_packages": attr.string_list_dict(
            doc = "PLATFORMS key -> the runtime sidecar packages that only apply when " +
                  "building for that platform.",
        ),
        "aliases": attr.string_dict(
            doc = "Target name -> npm package name for each additional name this package " +
                  "is imported under (npm alias specifiers). The extension names the " +
                  "targets so the hub and the spoke agree without duplicating the " +
                  "name-to-label rule.",
        ),
        "patch": attr.label(
            allow_single_file = True,
            doc = "The pnpm patch to apply to this package, from patchedDependencies.",
        ),
        "npmrc": attr.label(
            allow_single_file = True,
            doc = "The workspace .npmrc, read at fetch time for the credentials of the " +
                  "registry this package's url points at. A label rather than the parsed " +
                  "values, so no token is ever an attribute value -- attribute values are " +
                  "written to MODULE.bazel.lock.",
        ),
        "patch_sha256": attr.string(
            doc = "sha256 of the patch file as recorded in the lockfile's " +
                  "patchedDependencies. Empty when the lockfile records the digest " +
                  "in some other form, which skips the content check.",
        ),
    },
    doc = "Fetches one npm package into its own repository and generates its BUILD file.",
)

def _alias_block(alias_names, aliases):
    lines = []
    for alias_name in sorted(alias_names):
        lines.append("alias(")
        lines.append('    name = "{}",'.format(alias_name))
        lines.append('    actual = "{}",'.format(aliases[alias_name]))
        lines.append(")")
        lines.append("")
    return lines

_HUB_HEADER = [
    "# Generated by npm_hub. Do not edit.",
    "#",
    "# Aliases only: this repository downloads nothing, so it stays cheap to",
    "# regenerate when the lockfile changes, and referencing one alias fetches",
    "# only that package's own repository.",
    'package(default_visibility = ["//visibility:public"])',
    "",
]

def _npm_hub_impl(rctx):
    lines = list(_HUB_HEADER)
    lines.extend(_alias_block(rctx.attr.aliases.keys(), rctx.attr.aliases))
    if rctx.attr.broken_cycle_edges:
        lines.append("# Circular npm dependency edges removed for an acyclic target graph.")
        lines.append("# These packages rely on Node's CJS cycle tolerance at runtime.")
        for edge in rctx.attr.broken_cycle_edges:
            lines.append("#   CYCLE BROKEN: {}".format(edge))
    rctx.file("BUILD.bazel", "\n".join(lines) + "\n")

    # One package per workspace member, so `@npm//path/to/member:react` is the
    # snapshot THAT member resolved react to. The root package above is the
    # whole-lockfile namespace and has to pick one snapshot per name; a member's
    # own package does not, which is the only place per-importer resolution can
    # live given that a Bazel package has one namespace.
    by_importer = {}
    for key, target in rctx.attr.importer_aliases.items():
        path, _, alias_name = key.rpartition("|")
        by_importer.setdefault(path, {})[alias_name] = target

    for path, aliases in by_importer.items():
        sub = list(_HUB_HEADER)
        sub.insert(1, "# Resolution as declared by the workspace member at {}.".format(path))
        sub.extend(_alias_block(aliases.keys(), aliases))
        rctx.file("{}/BUILD.bazel".format(path), "\n".join(sub) + "\n")

npm_hub = repository_rule(
    implementation = _npm_hub_impl,
    attrs = {
        "aliases": attr.string_dict(
            mandatory = True,
            doc = "Label name -> apparent label of the target it forwards to.",
        ),
        "importer_aliases": attr.string_dict(
            doc = "'<importer path>|<label name>' -> apparent label, one entry per " +
                  "dependency a workspace member declared. Flattened into a string_dict " +
                  "because a repository rule attribute cannot nest dicts; '|' cannot " +
                  "occur in either a package path or a label name.",
        ),
        "broken_cycle_edges": attr.string_list(
            doc = "Human-readable record of edges the extension removed.",
        ),
    },
    doc = "Alias-only hub giving npm packages stable @npm//:<name> labels, plus one " +
          "package per workspace member holding that member's own resolution.",
)

# Exported for the tests that pin the credential rules; the fetch path above is
# the only production caller.
npmrc_auth = _npmrc_auth
npmrc_auth_fields = _npmrc_auth_fields
