"""Per-resolution npm repositories: one external repo per snapshot, plus an alias hub.

Why this shape rather than one big repo
---------------------------------------
A single repository holding every package has to download and extract all of
them before it can generate any BUILD file, because it reads `bin` and `exports`
out of each extracted `package.json`. On a real 2731-package lockfile that is
~5 minutes and ~5 GB, paid in full even by a target whose only npm dependency is
vitest, in one serial Starlark loop with no resume: a single bad tarball restarts
everything.

The unit is one pnpm SNAPSHOT -- a package as resolved for one peer set -- not
one `name@version`. pnpm resolves a package once per distinct peer set and gives
each outcome its own dependency edges, so two snapshots can share a tarball and
disagree about what they depend on.

Here each snapshot is its own repository rule, so it reads its OWN package.json
and writes its OWN BUILD file. Bazel then fetches repositories on demand, which
gives four things the monolith cannot:

  - Laziness. Only packages in the requested targets' transitive closure are
    fetched. `@npm//:vitest` pulls vitest's subtree, not the lockfile.
  - Parallelism. Bazel fetches independent repositories concurrently instead of
    looping in Starlark.
  - Per-package caching and invalidation. Bumping one package invalidates one
    repository, not all of them.
  - Isolated failure. A malformed tarball fails its own package.

`npm_hub` is the stable label surface. Its root package is the whole-lockfile
namespace (`@npm//:zod`, `@npm//:types_react`, `@npm//:vitest_bin`), and it holds
one further package per workspace member (`@npm//apps/web:react`) carrying that
member's own resolution -- which the root package cannot, because a Bazel package
has one namespace and two members can resolve one name differently. It contains
only `alias` targets and downloads nothing, so it is cheap to regenerate whenever
the lockfile changes. Repositories created by one module extension can reference
each other by apparent name, which is what lets the hub point at spokes without
constructing canonical repo names.

What still lives in the extension, not here
-------------------------------------------
The extension parses the lockfile once (no network) and hands each spoke a
resolved, ACYCLIC dependency list. Cycle breaking cannot move into the spokes:
npm has genuine circular peer dependencies, Bazel target graphs may not cycle,
and a spoke only knows about itself. Multi-version label assignment and @types
pairing stay there for the same reason -- they are whole-graph decisions.

Platform is the exception that does NOT get decided there. Which platforms a
tarball is built for is whole-graph knowledge, but which of them applies is a
property of the build, so the extension partitions the dep lists and the spoke
emits a select(). Deciding it in the extension would mean reading the host, and
the extension's result is recorded in MODULE.bazel.lock -- a committed file.
"""

load("//npm/private:npmrc_auth.bzl", _npmrc_auth = "npmrc_auth", _npmrc_auth_fields = "npmrc_auth_fields")

_NPM_BUILD_HEADER = '''# Generated by npm_import. Do not edit.
load("@rules_typescript//ts/private:ts_npm_package.bzl", "ts_npm_package")
'''

def _tarball_prefix(rctx, staging):
    """Returns the archive's single top-level directory, or "" if it has none.

    npm tarballs conventionally extract under `package/`, but DefinitelyTyped
    ships `<name>/` and some ship `<name> v<major>.<minor>/`. Predicting the
    prefix from the package name means maintaining a table of exceptions, and a
    miss is not a warning -- it aborts the fetch, uncatchably. So the archive
    itself decides, by being extracted and listed. `watch = "no"` because the
    listing is of a path inside the repository being fetched, which can never be
    an input to that fetch.
    """
    entries = rctx.path(staging).readdir(watch = "no")
    if len(entries) == 1 and entries[0].is_dir:
        return entries[0].basename

    names = sorted([entry.basename for entry in entries])
    if "package.json" in names:
        return ""
    fail(
        "npm: the tarball for {} at {} is not shaped like an npm package: npm ".format(
            rctx.attr.package,
            rctx.attr.url,
        ) +
        "puts everything under one top-level directory, and this archive's top " +
        "level is [{}] with no package.json among it.\n".format(", ".join(names)) +
        "Check that the url resolves to a published npm tarball rather than a " +
        "git archive or a registry error page, then re-run `pnpm install` so the " +
        "lockfile records the registry's own resolution.",
    )

def _auth_for_fetch(rctx, url):
    if not rctx.attr.npmrc:
        return {}

    # An attr.label is not by itself an input to the fetch: without watching it,
    # rotating a token in .npmrc would leave the fetched repository in place.
    rctx.watch(rctx.attr.npmrc)
    return _npmrc_auth(rctx.read(rctx.attr.npmrc), url, rctx.getenv, str(rctx.attr.npmrc))

def _bin_entries(pkg_json):
    """Normalises package.json `bin` into {name: relative_path}.

    npm allows either a string (implying the package's own name) or a mapping.
    """
    raw = pkg_json.get("bin")
    if not raw:
        return {}
    if type(raw) == "string":
        name = pkg_json.get("name", "")
        if name.startswith("@") and "/" in name:
            name = name.split("/")[-1]
        return {name: raw} if name else {}
    if type(raw) == "dict":
        return {k: v for k, v in raw.items() if type(v) == "string"}
    return {}

def _primary_bin_name(package, bins):
    """The bin a bare `bazel run @npm//:<pkg>_bin` should mean.

    npm's own convention: the entry named after the package, else the only one.
    An ambiguous multi-bin package has no primary; callers name the script.
    """
    if not bins:
        return ""
    unscoped = package.split("/")[-1] if package.startswith("@") else package
    if unscoped in bins:
        return unscoped
    if len(bins) == 1:
        return list(bins.keys())[0]
    return ""

def _quote_list(items, indent = "        "):
    return "".join(['{}"{}",\n'.format(indent, i) for i in items])

def _label_list_expr(rctx_name, platforms, common, by_platform, indent = "        "):
    """Renders a label list that is partly platform-conditional.

    npm ships native code as `optionalDependencies` constrained by `os`/`cpu`,
    so which of them belongs in a dep list is a property of the TARGET platform,
    not of the machine that read the lockfile. Deciding it here -- in generated
    text, as a select() -- is what keeps the module extension's result, and
    therefore MODULE.bazel.lock, free of the host it ran on.

    The select has a branch for every platform rules_typescript names and no
    default, so an unsupported target platform is an error that says so rather
    than a silently short dependency list. The platform vocabulary arrives as an
    attribute rather than a load of //platforms: a spoke repository generated by
    the extension has no business knowing more about the ruleset than the
    extension told it.
    """
    parts = []
    if common:
        parts.append("[\n" + _quote_list(common, indent + "    ") + indent + "]")
    if by_platform:
        branches = [indent + "select({\n"]
        for platform in platforms:
            labels = by_platform.get(platform, [])
            branches.append('{}    "@rules_typescript//platforms:is_{}": [\n'.format(indent, platform))
            branches.append(_quote_list(labels, indent + "        "))
            branches.append(indent + "    ],\n")
        branches.append(
            indent + '}, no_match_error = "' + rctx_name +
            ": npm packages here are platform-specific and this target platform is none of " +
            ", ".join(platforms) + '")',
        )
        parts.append("".join(branches).lstrip())
    if not parts:
        return ""
    return " + ".join(parts)

# TypeScript takes a `paths` match for a library file -- type-checked, never
# emitted, exempt from rootDir -- only when its path holds a node_modules segment.
def _package_root(package):
    return "node_modules/" + package

def _package_relative_label(package_root, path):
    """The label of a file inside the package, relative to the generated BUILD file."""
    return ":" + package_root + "/" + path

def _package_stanza(attrs, target_name, package_name, deps_expr):
    """The ts_npm_package call for one name this package is imported under."""
    package_root = _package_root(attrs.package)
    stanza = [
        "ts_npm_package(",
        '    name = "{}",'.format(target_name),
        '    package_name = "{}",'.format(package_name),
        '    package_version = "{}",'.format(attrs.version),
    ]
    if attrs.peer_id:
        stanza.append('    peer_id = "{}",'.format(attrs.peer_id))
    stanza += [
        '    package_dir = "{}",'.format(_package_relative_label(package_root, "package.json")),
        '    package_files = glob(["{}/**/*"], exclude_directories = 1, allow_empty = True),'.format(package_root),
    ]
    if deps_expr:
        stanza.append("    deps = {},".format(deps_expr))
    if attrs.types_dep:
        stanza.append('    types_dep = "{}",'.format(attrs.types_dep))
    stanza.append(")\n")
    return "\n".join(stanza)

def _apply_patch(rctx):
    """Applies the package's pnpm patch, failing the fetch if it does not land.

    The tarball just downloaded is byte-identical to the unpatched publish, so a
    patch that quietly fails to apply leaves nothing downstream able to tell the
    difference until production. Hence two loud gates: the digest below, and
    rctx.patch itself, which fails on any hunk that does not apply.
    """
    patch = rctx.attr.patch

    # An attr.label is not by itself a dependency of the fetch, and neither is
    # rctx.path on it: without this, editing a patch file leaves the already
    # fetched repository in place and the build keeps the old patch.
    rctx.watch(patch)

    if not rctx.attr.patch_sha256:
        rctx.patch(patch, strip = 1)
        return

    # Copied through the downloader purely to get its digest -- Starlark has no
    # hashing builtin. Deliberately WITHOUT download's own sha256 argument: a
    # checksummed request is served from the content-addressed repository cache
    # without reading the file at all, so an edited patch would be silently
    # replaced by the locked bytes on a warm cache and rejected on a cold one.
    local = "_pnpm.patch"
    result = rctx.download(url = "file://" + str(rctx.path(patch)), output = local)
    if result.sha256 != rctx.attr.patch_sha256:
        fail(
            "npm: {} does not match the sha256 recorded for {} in the lockfile's ".format(
                patch,
                rctx.attr.package,
            ) +
            "patchedDependencies:\n  lockfile: {}\n  file:     {}\n".format(
                rctx.attr.patch_sha256,
                result.sha256,
            ) +
            "pnpm records that digest when it writes the patch, so the two disagreeing " +
            "means the patch changed without `pnpm install` being re-run. Bazel would " +
            "apply a patch pnpm never saw.",
        )
    rctx.patch(local, strip = 1)
    rctx.delete(local)

# Bazel reads each as a package or repository boundary, which would take the
# package out of its own glob; at the repository root the generated file won.
_BOUNDARY_FILES = ("BUILD", "BUILD.bazel", "WORKSPACE", "WORKSPACE.bazel", "MODULE.bazel", "REPO.bazel")

def _move_package(rctx, package_root):
    """Moves the package from the repository root, where rctx.patch applies, to `package_root`.

    Staged, since a package can ship a node_modules of its own (@parcel/watcher-wasm).
    """
    staging = "_pkg"
    for entry in rctx.path(".").readdir(watch = "no"):
        rctx.rename(entry.basename, staging + "/" + entry.basename)
    rctx.rename(staging, package_root)
    for name in _BOUNDARY_FILES:
        rctx.delete(package_root + "/" + name)

def _npm_import_impl(rctx):
    tarball = "_pkg.tgz"
    auth = _auth_for_fetch(rctx, rctx.attr.url)
    rctx.download(url = rctx.attr.url, output = tarball, integrity = rctx.attr.integrity, auth = auth)

    # Extracted twice deliberately: the strip prefix is only knowable by looking
    # inside, and Starlark cannot catch the failure a wrong one would raise.
    staging = "_stage"
    rctx.extract(archive = tarball, output = staging)
    prefix = _tarball_prefix(rctx, staging)
    rctx.delete(staging)

    rctx.extract(archive = tarball, stripPrefix = prefix)
    rctx.delete(tarball)

    # Before package.json is read: a patch may change `bin` or `exports`, and
    # pnpm links the patched manifest, so the generated targets must describe
    # the patched package rather than the published one.
    if rctx.attr.patch:
        _apply_patch(rctx)

    package_root = _package_root(rctx.attr.package)
    _move_package(rctx, package_root)

    pkg_json = {}
    pkg_json_path = rctx.path(package_root + "/package.json")
    if pkg_json_path.exists:
        pkg_json = json.decode(rctx.read(pkg_json_path))

    lines = [_NPM_BUILD_HEADER]
    bins = _bin_entries(pkg_json)
    if bins:
        lines.append('load("@rules_typescript//npm/private:npm_bin.bzl", "npm_bin")\n')
    lines.append('package(default_visibility = ["//visibility:public"])\n')
    lines.append('exports_files(["{}/package.json"])\n'.format(package_root))

    deps_expr = _label_list_expr(
        rctx.attr.package,
        rctx.attr.platforms,
        rctx.attr.deps,
        rctx.attr.platform_deps,
    )
    lines.append(_package_stanza(rctx.attr, "pkg", rctx.attr.package, deps_expr))

    # An npm alias (`h3-v2: npm:h3@2.0.1`) is the same files installed under a
    # second name. package_name is what the node_modules tree builder writes on
    # disk, so the alias needs its own target: node_modules/h3-v2 is where
    # `import "h3-v2"` looks, and pointing a Bazel alias at :pkg would produce
    # node_modules/h3 instead.
    for target_name, alias_package in rctx.attr.aliases.items():
        lines.append(_package_stanza(rctx.attr, target_name, alias_package, deps_expr))

    # Native binaries a bin script resolves at runtime live in sibling
    # repositories, so they are declared as targets rather than located by
    # directory name inside one shared repository.
    optional_expr = _label_list_expr(
        rctx.attr.package,
        rctx.attr.platforms,
        rctx.attr.optional_dep_packages,
        rctx.attr.platform_optional_dep_packages,
    )
    for bin_name, bin_path in bins.items():
        bin_stanza = [
            "npm_bin(",
            '    name = "{}",'.format(bin_name),
            '    entry_script = "{}",'.format(bin_path.removeprefix("./")),
            '    package_files = glob(["{}/**/*"], exclude_directories = 1, allow_empty = True),'.format(package_root),
        ]
        if optional_expr:
            bin_stanza.append("    optional_dep_packages = {},".format(optional_expr))
        bin_stanza.append(")\n")
        lines.append("\n".join(bin_stanza))

    # The hub aliases <label>_bin without being able to see whether a package has
    # a bin -- knowing that is exactly what downloading it would cost. So the
    # package exposes a fixed ":bin" name for its primary script, and the hub's
    # alias resolves only if something actually asks for it.
    primary_bin = _primary_bin_name(rctx.attr.package, bins)
    if primary_bin:
        lines.append('alias(\n    name = "bin",\n    actual = ":{}",\n)\n'.format(primary_bin))

    rctx.file("BUILD.bazel", "\n".join(lines))

npm_import = repository_rule(
    implementation = _npm_import_impl,
    attrs = {
        "package": attr.string(mandatory = True, doc = "npm package name, e.g. '@types/react'."),
        "version": attr.string(mandatory = True, doc = "Resolved version."),
        "peer_id": attr.string(
            doc = "Filesystem-safe token naming this snapshot's peer set, empty for a " +
                  "package pnpm resolved only one way. The repository name already carries " +
                  "it; this passes it on to the providers, which is where a node_modules " +
                  "tree can act on it.",
        ),
        "url": attr.string(mandatory = True, doc = "Tarball URL."),
        "integrity": attr.string(
            mandatory = True,
            doc = "SRI hash from the lockfile's resolution.integrity. Mandatory: an " +
                  "unverified npm fetch should not be expressible, and the extension " +
                  "rejects a lockfile entry that cannot supply one.",
        ),
        "deps": attr.string_list(
            doc = "Apparent labels of sibling npm_import repos this package depends on " +
                  "on every platform, already cycle-broken by the extension.",
        ),
        "platforms": attr.string_list(
            doc = "The PLATFORMS keys a platform select() must cover, supplied by the " +
                  "extension so the generated BUILD file needs no load of //platforms.",
        ),
        "platform_deps": attr.string_list_dict(
            doc = "PLATFORMS key -> the deps that only apply when building for that " +
                  "platform. Rendered as a select(), so the choice happens at analysis " +
                  "time rather than in the extension.",
        ),
        "types_dep": attr.string(doc = "Apparent label of the @types/* package for this one."),
        "optional_dep_packages": attr.string_list(
            doc = "Apparent labels of sibling npm_import repos holding native binaries " +
                  "this package's bin scripts resolve at runtime on every platform.",
        ),
        "platform_optional_dep_packages": attr.string_list_dict(
            doc = "PLATFORMS key -> the runtime sidecar packages that only apply when " +
                  "building for that platform.",
        ),
        "aliases": attr.string_dict(
            doc = "Target name -> npm package name for each additional name this package " +
                  "is imported under (npm alias specifiers). The extension names the " +
                  "targets so the hub and the spoke agree without duplicating the " +
                  "name-to-label rule.",
        ),
        "patch": attr.label(
            allow_single_file = True,
            doc = "The pnpm patch to apply to this package, from patchedDependencies.",
        ),
        "npmrc": attr.label(
            allow_single_file = True,
            doc = "The workspace .npmrc, read at fetch time for the credentials of the " +
                  "registry this package's url points at. A label rather than the parsed " +
                  "values, so no token is ever an attribute value -- attribute values are " +
                  "written to MODULE.bazel.lock.",
        ),
        "patch_sha256": attr.string(
            doc = "sha256 of the patch file as recorded in the lockfile's " +
                  "patchedDependencies. Empty when the lockfile records the digest " +
                  "in some other form, which skips the content check.",
        ),
    },
    doc = "Fetches one npm package into its own repository and generates its BUILD file.",
)

def _alias_block(alias_names, aliases):
    lines = []
    for alias_name in sorted(alias_names):
        lines.append("alias(")
        lines.append('    name = "{}",'.format(alias_name))
        lines.append('    actual = "{}",'.format(aliases[alias_name]))
        lines.append(")")
        lines.append("")
    return lines

_LINK_LOAD = 'load("@rules_typescript//npm/private:workspace_package.bzl", "npm_workspace_package")'

# ─── Workspace members: the target that builds one ───────────────────────────

def _names_a_target(build_text, target):
    return (
        'name = "{}"'.format(target) in build_text or
        'name="{}"'.format(target) in build_text or
        "name = '{}'".format(target) in build_text or
        "name='{}'".format(target) in build_text
    )

def _read_if_present(rctx, path):
    """The file's text, or None -- watching a file that is not there yet.

    Absence is a load-bearing answer here: a directory becomes a Bazel package
    the moment Gazelle writes a BUILD file into it, and that has to refetch this
    repository.
    """
    if path.exists:
        return rctx.read(path)
    rctx.watch(path)
    return None

def _build_file_text(rctx, root, dir_path):
    for name in ("BUILD.bazel", "BUILD"):
        text = _read_if_present(rctx, root.get_child(*(dir_path.split("/") + [name])))
        if text != None:
            return text
    return None

def _link_target_label(member, build_text):
    """The label of the target that builds a workspace member, or None.

    A member's compiling target is `//<member>:<basename>`, and only a BUILD
    file there that DECLARES it earns the label: one naming a target Bazel
    cannot resolve fails analysis for everything that reaches the hub, while a
    missing target fails only what asks for the member.

    Args:
        member: The member's path from the repo root, e.g. "packages/foo".
        build_text: Function from a directory to the text of the BUILD file in
            it, or None when that directory holds none.
    """
    text = build_text(member)
    if text == None:
        return None
    target = member.split("/")[-1]
    if _names_a_target(text, target):
        return "@@//{}:{}".format(member, target)
    return None

def _repo_root(rctx):
    """The root the labels this rule writes are relative to.

    `@@//` is the main repository, so the member paths are resolved against it
    rather than against the lockfile's own directory -- the two coincide for a
    pnpm workspace, whose lockfile sits at its root.
    """
    root = rctx.path(rctx.attr.pnpm_lock).dirname
    package = rctx.attr.pnpm_lock.package
    for _ in (package.split("/") if package else []):
        root = root.dirname
    return root

def _member_targets(rctx):
    """Label per member directory of this lockfile, None where no target declares one."""
    if not rctx.attr.members:
        return {}
    root = _repo_root(rctx)

    def build_text(dir_path):
        return _build_file_text(rctx, root, dir_path)

    targets = {}
    for entry in rctx.attr.members.values():
        _, _, member = entry.partition("|")
        if member not in targets:
            targets[member] = _link_target_label(member, build_text)
    return targets

def _unresolved_link_note(package_name, member):
    return [
        "# NO TARGET for '{}'. No BUILD file in".format(package_name),
        "# {} declares a target of that name, so nothing".format(member),
        "# here can name the target that builds the member: run Gazelle over",
        "# that directory. A label",
        "# written anyway would name a target Bazel cannot resolve, which fails analysis",
        "# for every consumer of this hub rather than for this name alone.",
        "",
    ]

def _unresolved_manifest_note(package_name, member):
    return [
        "# NO MANIFEST for '{}'. {}/package.json is missing or".format(package_name, member),
        "# has no name, and the manifest is what the member's view carries: give the",
        "# member a package.json with a name.",
        "",
    ]

def _link_block(members, targets, manifests):
    """One view per workspace member, carrying the name it is imported by.

    Not an alias: Bazel resolves an alias before any rule implementation runs, so
    the member would arrive at a consumer with no record of the npm name at all.
    The member's package.json travels as text because nothing reads a file
    during analysis; the view rewrites its source-file targets to the emitted
    files, whose names the compiling target decides.
    """
    lines = []
    for label_name in sorted(members):
        package_name, _, member = members[label_name].partition("|")
        target = targets.get(member)
        if not target:
            lines.extend(_unresolved_link_note(package_name, member))
            continue
        manifest = manifests.get(label_name)
        if not manifest:
            lines.extend(_unresolved_manifest_note(package_name, member))
            continue
        lines.append("npm_workspace_package(")
        lines.append('    name = "{}",'.format(label_name))
        lines.append('    package_name = "{}",'.format(package_name))
        lines.append('    member_dir = "{}",'.format(member))
        lines.append('    target = "{}",'.format(target))
        lines.append("    manifest_json = {},".format(json.encode(manifest)))
        lines.append(")")
        lines.append("")
    return lines

_HUB_HEADER = [
    "# Generated by npm_hub. Do not edit.",
    "#",
    "# Aliases, plus one view per workspace member: this repository downloads",
    "# nothing, so it stays cheap to regenerate when the lockfile changes, and",
    "# referencing one alias fetches only that package's own repository.",
    'package(default_visibility = ["//visibility:public"])',
    "",
]

def _hub_lines(members, note = None):
    """The header, carrying the load a member's view needs and nothing else."""
    lines = list(_HUB_HEADER)
    if note:
        lines.insert(1, "# {}".format(note))
    return ([_LINK_LOAD, ""] + lines) if members else lines

def _npm_hub_impl(rctx):
    targets = _member_targets(rctx)

    lines = _hub_lines(rctx.attr.members)
    lines.extend(_alias_block(rctx.attr.aliases.keys(), rctx.attr.aliases))
    lines.extend(_link_block(rctx.attr.members, targets, rctx.attr.member_manifests))
    if rctx.attr.broken_cycle_edges:
        lines.append("# Circular npm dependency edges removed for an acyclic target graph.")
        lines.append("# These packages rely on Node's CJS cycle tolerance at runtime.")
        for edge in rctx.attr.broken_cycle_edges:
            lines.append("#   CYCLE BROKEN: {}".format(edge))
    rctx.file("BUILD.bazel", "\n".join(lines) + "\n")

    # One package per workspace member: `@npm//path/to/member:react` is that
    # member's resolution; the root has one namespace and one snapshot per name.
    by_importer = {}
    for key, target in rctx.attr.importer_aliases.items():
        path, _, alias_name = key.rpartition("|")
        by_importer.setdefault(path, {})[alias_name] = target

    for path, aliases in by_importer.items():
        sub = _hub_lines({}, "Resolution as declared by the workspace member at {}.".format(path))
        sub.extend(_alias_block(aliases.keys(), aliases))
        rctx.file("{}/BUILD.bazel".format(path), "\n".join(sub) + "\n")

npm_hub = repository_rule(
    implementation = _npm_hub_impl,
    attrs = {
        "aliases": attr.string_dict(
            mandatory = True,
            doc = "Label name -> apparent label of the target it forwards to.",
        ),
        "importer_aliases": attr.string_dict(
            doc = "'<importer path>|<label name>' -> apparent label, one entry per " +
                  "dependency a workspace member declared. Flattened into a string_dict " +
                  "because a repository rule attribute cannot nest dicts; '|' cannot " +
                  "occur in either a package path or a label name.",
        ),
        "members": attr.string_dict(
            doc = "Label name -> '<npm package name>|<path of the workspace member>' " +
                  "for each workspace member: every `link:` target and every named " +
                  "importer. A path rather than a label: the member's target " +
                  "is //<path>:<basename> when a BUILD file there declares " +
                  "it, read at fetch time since Gazelle may not have written " +
                  "it yet. The package name travels with it " +
                  "because it cannot be recovered from the label name: 'types_react' is " +
                  "the label of '@types/react' and of 'types_react'.",
        ),
        "member_manifests": attr.string_dict(
            doc = "Label name -> the member's package.json as text; the view " +
                  "rewrites every source-file target to the emitted file. A " +
                  "member missing here has no package.json with a name and " +
                  "gets a comment, no view.",
        ),
        "pnpm_lock": attr.label(
            allow_single_file = True,
            doc = "The lockfile this hub was translated from, for the repository root " +
                  "the member paths are resolved against.",
        ),
        "broken_cycle_edges": attr.string_list(
            doc = "Human-readable record of edges the extension removed.",
        ),
    },
    doc = "Alias-only hub giving npm packages stable @npm//:<name> labels, one view " +
          "per workspace member, plus one package per importer holding that " +
          "importer's own resolution.",
)

# Exported for the tests that pin the credential rules and the `link:` member
# resolution; the paths above are the only production callers.
link_target_label = _link_target_label
link_block = _link_block
npmrc_auth = _npmrc_auth
npmrc_auth_fields = _npmrc_auth_fields
