"""Rule for executable npm bin script targets.

npm_bin wraps a bin script from an npm package as a Bazel executable target.
It resolves Node.js from the js_runtime toolchain (or falls back to system node)
and invokes the specified script entry point with any provided arguments.

Generated by npm_import for each entry in a package's "bin" field.

Usage (generated by npm_import):
    npm_bin(
        name = "vitest",
        entry_script = "vitest.mjs",
        store = "@@//:node_modules/.pnpm/vitest@3.2.4/node_modules/vitest",
    )

Users can then:
    bazel run @npm//:vitest_bin -- --version
"""

load(
    "//tools/launcher:launcher.bzl",
    "LAUNCHER_TOOLCHAINS",
    "NATIVE_EXECUTABLE_ATTRS",
    "NATIVE_PROGRAM_ATTRS",
    "NativeExecutableInfo",
    "complete_native_executable",
    "declare_launcher",
    "declare_runnable",
    "rlocation_path",
)
load("//ts/private:providers.bzl", "NpmPackageInfo")
load("//ts/private:runtime.bzl", "JS_RUNTIME_TOOLCHAIN_TYPE", "get_js_runtime")
load("//ts/private:toolchain.bzl", "TOOLS_TOOLCHAIN_TYPE")
load(":store.bzl", "NpmStoreInfo")

def _npm_bin_impl(ctx):
    # Resolve the JS runtime from the toolchain or fall back to system node.
    runtime_binary = None
    runtime_args = []
    if ctx.file.runtime:
        runtime_binary = ctx.file.runtime
    else:
        js_runtime = get_js_runtime(ctx)
        if js_runtime:
            runtime_binary = js_runtime.runtime_binary
            runtime_args = js_runtime.args_prefix

    if ctx.attr.entry_missing:
        fail(ctx.attr.entry_missing)
    store = ctx.attr.store[NpmStoreInfo] if ctx.attr.store else None
    entry_script_file = None
    entry_script = ctx.attr.entry_script
    if not store:
        for f in ctx.files.package_files:
            # Suffix match; the package sits under node_modules/<name> in its repository:
            # external/<repository>/node_modules/vitest/vitest.mjs.
            if f.basename == entry_script or f.path.endswith("/" + entry_script):
                entry_script_file = f
                break

        if not entry_script_file:
            available = [f.basename for f in ctx.files.package_files]
            fail(
                "npm_bin: entry script '{}' not found in package files for target '{}'.\n".format(
                    entry_script,
                    ctx.label,
                ) +
                "This usually means the npm package's 'bin' field references a file that " +
                "was not included in package_files, or the entry_script path is wrong.\n" +
                "Available files: {}".format(", ".join(available[:20]) + (" ..." if len(available) > 20 else "")),
            )

    # Native package lookup needs optional siblings in a directory named node_modules.
    optional_deps = []
    optional_dep_pkg_files = []
    for dep in ctx.attr.optional_dep_packages:
        info = dep[NpmPackageInfo]
        if not info.package_dir:
            continue
        optional_deps.append({
            "name": info.package_name,
            "package_json": rlocation_path(ctx, info.store.tree) + "/package.json",
        })
        optional_dep_pkg_files.append(depset([info.store.tree]))

    entry = rlocation_path(ctx, store.tree) + "/" + entry_script if store else rlocation_path(ctx, entry_script_file)
    config = {
        "label": str(ctx.label),
        "mode": "node",
        "workspace": ctx.workspace_name,
        "runtime_args": runtime_args,
        "node": {
            "entry": entry,
            "optional_deps": optional_deps,
        },
    }
    if runtime_binary:
        config["runtime"] = rlocation_path(ctx, runtime_binary)

    runfiles_files = [entry_script_file] if entry_script_file else []

    # Also include the full package files so Node can resolve modules inside the package.
    runfiles = ctx.runfiles(
        files = runfiles_files,
        transitive_files = depset(ctx.files.package_files, transitive = optional_dep_pkg_files + ([store.transitive] if store else [])),
    )

    launcher = declare_launcher(ctx, config, basename = "{}_bin_launcher".format(ctx.label.name), runfiles = runfiles, runtime_file = runtime_binary)
    runfiles = runfiles.merge(ctx.runfiles(files = launcher.files + ([runtime_binary] if runtime_binary else []), root_symlinks = launcher.root_symlinks))

    return [
        DefaultInfo(
            executable = launcher.executable,
            runfiles = runfiles,
        ),
        NativeExecutableInfo(launcher = launcher, default_files = None),
    ]

def _npm_bin_executable_impl(ctx):
    return complete_native_executable(ctx, ctx.label.name + "_bin_launcher")

_BIN_ATTRS = {
    "package_files": attr.label_list(
        doc = "Every file of the package, for a target with no `store`.",
        allow_files = True,
    ),
    "entry_missing": attr.string(
        doc = "The error npm_import found at fetch time: the package lacks " +
              "entry_script. Reported when this target is analysed.",
    ),
    "store": attr.label(providers = [NpmStoreInfo]),
    "entry_script": attr.string(
        doc = "The relative path within the package to the bin entry script (e.g. 'vitest.mjs').",
        mandatory = True,
    ),
    "optional_dep_packages": attr.label_list(
        providers = [[NpmPackageInfo]],
        doc = "Sibling npm package targets holding platform-specific native " +
              "binaries this bin script resolves at runtime. The native view contains " +
              "node_modules/ symlinks for them so require.resolve() works inside " +
              "action sandboxes and runfiles trees.",
    ),
    "runtime": attr.label(
        doc = "Per-target override for the JS runtime binary. " +
              "When set, takes priority over the js_runtime toolchain.",
        allow_single_file = True,
        executable = True,
        cfg = "exec",
    ),
}

_npm_bin_program = rule(
    implementation = _npm_bin_impl,
    executable = True,
    fragments = ["platform"],
    attrs = _BIN_ATTRS | NATIVE_PROGRAM_ATTRS,
    toolchains = LAUNCHER_TOOLCHAINS + [
        TOOLS_TOOLCHAIN_TYPE,
        config_common.toolchain_type(JS_RUNTIME_TOOLCHAIN_TYPE, mandatory = False),
    ],
)

npm_bin = rule(
    implementation = _npm_bin_executable_impl,
    executable = True,
    attrs = _BIN_ATTRS | NATIVE_EXECUTABLE_ATTRS,
    toolchains = [TOOLS_TOOLCHAIN_TYPE],
    doc = """Exposes an npm package's bin script as an executable Bazel target.

Generated by npm_import for each entry in the package's 'bin' field.
Resolves Node.js from the js_runtime toolchain (or falls back to system node).

Example usage:
    bazel run @npm//:vitest_bin -- --version
    bazel run @npm//:tsx -- script.ts
""",
)

def npm_bin_macro(name, **kwargs):
    declare_runnable(name, _npm_bin_program, npm_bin, kwargs)
