"""The hub target for a pnpm `link:` dependency: a workspace member, named.

A `workspace:*` dependency resolves to a target in the consumer's own repository,
and the hub used to hold an `alias` to it. An alias cannot carry the name: Bazel
resolves it before any rule implementation runs, so `@npm//:shared` reaches
ts_compile as the aliased target itself and the only record that the member is
imported as `shared` is the alias label, which nothing can read. Every workspace
member therefore had to restate its own npm name as `module_name` -- a second
place for it to be wrong, in a file the lockfile does not reach.

This rule is that alias with the name attached: it forwards the member's
providers unchanged and re-declares TsModuleInfo under the name the lockfile
says the member is imported by.
"""

load("//ts/private:providers.bzl", "AssetInfo", "CssInfo", "CssModuleInfo", "JsInfo", "TsDeclarationInfo")
load("//ts/private:ts_compile.bzl", "TsModuleInfo")

_FORWARDED = [JsInfo, TsDeclarationInfo, CssInfo, CssModuleInfo, AssetInfo]

def _label_text(label):
    text = str(label)
    return text[2:] if text.startswith("@@//") else text

def _npm_workspace_package_impl(ctx):
    member = ctx.attr.target

    # A member with no TsModuleInfo has no name to attach -- a css_module or an
    # asset_library linked by `workspace:*` is a legitimate dependency, and the
    # alias this rule replaced forwarded it, so failing here would be a
    # regression rather than a diagnosis.
    if TsModuleInfo not in member:
        return [
            DefaultInfo(
                files = member[DefaultInfo].files,
                runfiles = member[DefaultInfo].default_runfiles,
            ),
        ] + [member[provider] for provider in _FORWARDED if provider in member]

    module = member[TsModuleInfo]

    providers = [
        DefaultInfo(
            files = member[DefaultInfo].files,
            runfiles = member[DefaultInfo].default_runfiles,
        ),
        TsModuleInfo(
            module_name = ctx.attr.package_name,
            label = _label_text(ctx.label),
            declaration_root = module.declaration_root,
            source_root = module.source_root,
            transitive_modules = depset(
                [struct(
                    module_name = ctx.attr.package_name,
                    label = _label_text(ctx.label),
                    declaration_root = module.declaration_root,
                    source_root = module.source_root,
                )],
                transitive = [module.transitive_modules],
            ),
        ),
    ]
    for provider in _FORWARDED:
        if provider in member:
            providers.append(member[provider])
    return providers

npm_workspace_package = rule(
    implementation = _npm_workspace_package_impl,
    attrs = {
        "package_name": attr.string(
            mandatory = True,
            doc = "The npm package name the lockfile imports the member under.",
        ),
        "target": attr.label(
            mandatory = True,
            doc = "The workspace member's own target, as the `link:` path names it.",
        ),
    },
    doc = "Generated by npm_hub for each pnpm `link:` dependency; not for hand use.",
)
