"""The hub's view of a pnpm workspace member: an npm package, named.

A `workspace:*` dependency resolves to a target in the consumer's own repository,
and the hub used to hold an `alias` to it. An alias cannot carry the name: Bazel
resolves it before any rule implementation runs, so `@npm//:shared` would reach a
consumer as the aliased target itself and the only record that the member is
imported as `shared` would be the alias label, which nothing can read.

This rule is that alias with the name attached. It forwards the member's TsInfo
unchanged and describes the member as an npm package: `NpmPackageInfo.store` is
the member's store tree (`npm_store_member`, docs/rules/node-modules.md § The
Store); `all_files` and `direct_deps` are what the forest links a member from
(§ Trees ts_compile and ts_test Generate there): the files that tree copies --
the manifest as built, the member's `.js`, `.js.map` and `.d.ts`, and its data
srcs, its own package.json excepted -- and the compiling target's direct npm
deps, so the forest places the member's own resolution of a name under it.

Two fields of NpmPackageInfo that assume an extracted tarball say otherwise:

  package_dir  is None. A member has no package.json in an external repository;
               its store writes the manifest as built.
  package_root is the member's directory under bazel-bin, where the compiling
               target's outputs hang off, and not that target's package: a
               member whose entry sits in a subdirectory is compiled by a target
               in that subdirectory, and its manifest names `src/index.js`.
"""

load("//npm/private:store.bzl", "MEMBER_VERSION", "NpmStoreInfo")
load("//ts/private:providers.bzl", "NpmPackageInfo", "TsInfo")

_WorkspaceNpmDeps = provider(
    doc = "The npm packages a workspace member depends on directly.",
    fields = {
        "direct": "list of NpmPackageInfo: the npm packages this target " +
                  "depends on directly.",
    },
)

def _workspace_npm_deps_impl(target, ctx):
    return [_WorkspaceNpmDeps(direct = [
        dep[NpmPackageInfo]
        for dep in getattr(ctx.rule.attr, "deps", [])
        if NpmPackageInfo in dep
    ])]

_workspace_npm_deps = aspect(
    implementation = _workspace_npm_deps_impl,
    doc = "Reads the member's direct npm deps: TsInfo carries the closure, " +
          "and the direct set, which the forest places under the member, " +
          "travels in no provider of the target's own.",
)

def _package_root(ctx, member):
    return "/".join([
        p
        for p in [ctx.bin_dir.path, member.label.workspace_root, ctx.attr.member_dir]
        if p
    ])

def _npm_package_info(ctx, member):
    store = ctx.attr.store[NpmStoreInfo]
    info = member[TsInfo]
    own = ctx.attr.member_dir + "/package.json"
    data = [f for f in info.data.to_list() if f.short_path != own]

    return NpmPackageInfo(
        package_name = ctx.attr.package_name,
        package_version = MEMBER_VERSION,
        peer_id = "",
        package_dir = None,
        package_root = _package_root(ctx, member),
        all_files = depset(
            [store.manifest] + data,
            transitive = [info.declarations, info.js, info.js_maps],
        ),
        direct_deps = member[_WorkspaceNpmDeps].direct,
        transitive_deps = info.npm_packages,
        store = store,
    )

def _npm_workspace_package_impl(ctx):
    member = ctx.attr.target

    return [
        DefaultInfo(
            files = member[DefaultInfo].files,
            runfiles = member[DefaultInfo].default_runfiles,
        ),
        _npm_package_info(ctx, member),
        member[TsInfo],
    ]

npm_workspace_package = rule(
    implementation = _npm_workspace_package_impl,
    attrs = {
        "package_name": attr.string(
            mandatory = True,
            doc = "The npm package name the member is imported by.",
        ),
        "member_dir": attr.string(
            mandatory = True,
            doc = "The member's directory from the workspace root: the directory its " +
                  "package.json sits in and its manifest's targets are relative to.",
        ),
        "target": attr.label(
            mandatory = True,
            aspects = [_workspace_npm_deps],
            providers = [TsInfo],
            doc = "The target that compiles the member, as npm_hub finds it.",
        ),
        "store": attr.label(
            mandatory = True,
            providers = [NpmStoreInfo],
            doc = "The member's npm_store_member target in the lockfile's " +
                  "package.",
        ),
    },
    doc = "Generated by npm_hub for each workspace member; not for hand use.",
)
