load("@rules_typescript//ts:defs.bzl", "ts_compile", "ts_config", "ts_test")

ts_compile(
    name = "hooks",
    srcs = [
        "index.ts",
        "useCounter.ts",
    ],
    emit = True,
    node_modules = "//:node_modules",
    tsconfig = ":tsconfig",
    visibility = ["//visibility:public"],
    deps = ["@npm//:react"],
)

ts_test(
    name = "hooks_test",
    srcs = ["useCounter.test.ts"],
    node_modules = "//:node_modules",
    tsconfig = ":tsconfig",
    deps = [
        ":hooks",
        "@npm//:happy-dom",
        "@npm//:react",
        "@npm//:react-dom",
        "@npm//:testing-library_dom",
        "@npm//:testing-library_react",
        "@npm//:types_react",
        "@npm//:types_react-dom",
        "@npm//:vite",
        "@npm//:vitest",
        "@npm//:zod",
    ],
)

ts_config(
    name = "tsconfig",
    src = "tsconfig.json",
    visibility = ["//visibility:public"],
    deps = ["//:tsconfig"],
)
