load("@rules_typescript//ts:defs.bzl", "ts_compile", "ts_test")

ts_compile(
    name = "hooks",
    srcs = [
        "index.ts",
        "useCounter.ts",
    ],
    node_modules = "//:node_modules",
    visibility = ["//visibility:public"],
    deps = ["@npm//:react"],
)

ts_test(
    name = "hooks_test",
    srcs = ["useCounter.test.ts"],
    node_modules = "//:node_modules",
    deps = [
        ":hooks",
        "@npm//:react",
        "@npm//:vitest",
    ],
)
